"""Shared schemas for A Step Forward."""

from .common import IDStr, Timestamp, Provenance, Citation, ConfidenceScore
from .memory import (
    MemoryType,
    MemoryAccessPolicy,
    MemoryRecord,
    MemoryWriteInput,
    MemorySearchInput,
    MemorySearchResult,
    MemoryUpdateInput,
    MemoryHealthReport,
)
from .learners import LearnerProfile, LearnerRole
from .learner_model import (
    AdaptiveLearnerProfile,
    LearnerProfileInput,
    StudentModel,
    classify_mastery,
    self_score_to_mastery,
)
from .progress import MasteryEntry, ProgressSummary
from .curriculum import (
    Assessment,
    AssessmentType,
    BloomsLevel,
    Concept,
    Course,
    CourseSummary,
    CurriculumFindForConceptInput,
    CurriculumGetCourseInput,
    CurriculumGetLessonInput,
    CurriculumListCoursesInput,
    CurriculumSuggestPathInput,
    LearningPathSuggestion,
    Lesson,
    LessonMatch,
    Level,
    Modality,
    Objective,
    PathStep,
    Question,
    QuestionType,
    Resource,
    ResourceKind,
    Unit,
)
from .curriculum_seed import CourseMeta, SeedBundle, UnitMeta, load_seed_course
from .errors import AppError, AuthError, ForbiddenError, NotFoundError, PolicyViolation, ValidationFailed

__all__ = [
    "IDStr",
    "Timestamp",
    "Provenance",
    "Citation",
    "ConfidenceScore",
    "MemoryType",
    "MemoryAccessPolicy",
    "MemoryRecord",
    "MemoryWriteInput",
    "MemorySearchInput",
    "MemorySearchResult",
    "MemoryUpdateInput",
    "MemoryHealthReport",
    "AppError",
    "AuthError",
    "NotFoundError",
    "ValidationFailed",
    "PolicyViolation",
    "ForbiddenError",
    "LearnerProfile",
    "LearnerRole",
    "AdaptiveLearnerProfile",
    "LearnerProfileInput",
    "StudentModel",
    "classify_mastery",
    "self_score_to_mastery",
    "MasteryEntry",
    "ProgressSummary",
    "Assessment",
    "AssessmentType",
    "BloomsLevel",
    "Concept",
    "Course",
    "CourseMeta",
    "CourseSummary",
    "CurriculumFindForConceptInput",
    "CurriculumGetCourseInput",
    "CurriculumGetLessonInput",
    "CurriculumListCoursesInput",
    "CurriculumSuggestPathInput",
    "LearningPathSuggestion",
    "Lesson",
    "LessonMatch",
    "Level",
    "Modality",
    "Objective",
    "PathStep",
    "Question",
    "QuestionType",
    "Resource",
    "ResourceKind",
    "SeedBundle",
    "Unit",
    "UnitMeta",
    "load_seed_course",
]
