# Companion data for _expand_collisions.py — merged via exec()
SECTION_BODIES.update({
    "worked_example_1": {
        "body_en_md": (
            "**Given:** A 2 kg cart moves at 3 m/s and collides with a 3 kg stationary cart. "
            "They stick together (perfectly inelastic). Find:\n"
            "(a) Final velocity $v_f$.\n"
            "(b) Kinetic energy lost.\n\n"
            "Perfectly inelastic means one unknown final velocity shared by both carts. "
            "Momentum conservation alone is sufficient — do **not** use KE conservation.\n\n"
            "### Move 1 — Momentum conservation\n"
            "$$m_1v_1 + m_2v_2 = (m_1+m_2)v_f.$$\n"
            "$$2(3) + 3(0) = (2+3)v_f.$$\n"
            "$$6 = 5v_f \\Rightarrow v_f = 1.2 \\text{ m/s}.$$\n\n"
            "### Move 2 — Energy before and after\n"
            "$$KE_i = \\tfrac{1}{2}(2)(3)^2 + 0 = 9 \\text{ J}.$$\n"
            "$$KE_f = \\tfrac{1}{2}(5)(1.2)^2 = \\tfrac{1}{2}(5)(1.44) = 3.6 \\text{ J}.$$\n"
            "$$\\Delta KE = 9 - 3.6 = 5.4 \\text{ J lost}.$$\n\n"
            "### Move 3 — Verify with closed-form formula\n"
            "$$\\Delta KE = \\frac{m_1m_2}{2(m_1+m_2)}(v_1-v_2)^2 = "
            "\\frac{2\\times3}{2\\times5}(3)^2 = \\frac{6}{10}\\times9 = 5.4 \\text{ J}. \\checkmark$$\n\n"
            "**Answer:** $v_f = 1.2$ m/s; $\\Delta KE = 5.4$ J lost.\n\n"
            "**Physical interpretation:** The combined mass (5 kg) moves at 1.2 m/s — "
            "slower than the incoming 2 kg cart (3 m/s) because momentum is shared among "
            "more mass. Over 60% of initial KE was dissipated as heat and deformation. "
            "This is the maximum possible energy loss for these initial conditions."
        ),
        "body_he_md": (
            "**נתון:** עגלה 2 ק\"ג ב-3 מ\"ש מתנגשת עם עגלה 3 ק\"ג נחה. "
            "הן נדבקות (לא-אלסטית מוחלטת). מצאו:\n"
            "(א) מהירות סופית $v_f$.\n"
            "(ב) אנרגיה קינטית שאבדה.\n\n"
            "לא-אלסטית מוחלטת = מהירות סופית אחת משותפת. "
            "שימור תנע בלבד מספיק — **אל** תשתמשו בשימור $K$.\n\n"
            "### צעד 1 — שימור תנע\n"
            "$$2(3)+3(0)=5v_f\\Rightarrow v_f=1.2\\text{ מ/ש}.$$\n\n"
            "### צעד 2 — אנרגיה לפני ואחרי\n"
            "$$KE_i=\\tfrac{1}{2}(2)(9)=9\\text{ ג'ול}.$$\n"
            "$$KE_f=\\tfrac{1}{2}(5)(1.44)=3.6\\text{ ג'ול}.$$\n"
            "$$\\Delta KE=5.4\\text{ ג'ול אבדו}.$$\n\n"
            "### צעד 3 — אימות בנוסחה\n"
            "$$\\Delta KE=\\frac{m_1m_2}{2(m_1+m_2)}(v_1-v_2)^2="
            "\\frac{6}{10}\\times9=5.4\\text{ ג'ול}. \\checkmark$$\n\n"
            "**תשובה:** $v_f=1.2$ מ\"ש; $\\Delta KE=5.4$ ג'ול אבדו.\n\n"
            "**פרשנות:** המסה המשולבת (5 ק\"ג) נעה ב-1.2 מ\"ש — "
            "לאט יותר מהעגלה הנכנסת (3 מ\"ש) כי התנע מתחלק על יותר מסה. "
            "מעל 60% מה-$KE$ הראשונית פוזרה כחום ועיוות. "
            "זהו אובדן האנרגיה המקסימלי האפשרי לתנאים התחלתיים אלה — "
            "תכונה של התנגשות לא-אלסטית מוחלטת."
        ),
    },
    "checkpoint_1": {
        "checkpoint_solution_en": (
            "**Step 1 — Momentum conservation (perfectly inelastic):**\n"
            "When objects stick together, they share one final velocity $v_f$. "
            "Total momentum before equals total momentum after:\n"
            "$$p_i = m_1v_1 = 1.5 \\times 4 = 6\\text{ kg·m/s}.$$\n"
            "$$v_f = \\frac{p_i}{m_1+m_2} = \\frac{6}{1.5+2.5} = \\frac{6}{4} = 1.5\\text{ m/s}.$$\n\n"
            "**Step 2 — Kinetic energy before and after:**\n"
            "KE is not conserved in inelastic collisions — compute it separately "
            "before and after to find the loss:\n"
            "$$KE_i = \\tfrac{1}{2}(1.5)(16) = 12\\text{ J}.$$\n"
            "$$KE_f = \\tfrac{1}{2}(4)(1.5)^2 = \\tfrac{1}{2}(4)(2.25) = 4.5\\text{ J}.$$\n"
            "$$\\Delta KE = 12 - 4.5 = 7.5\\text{ J lost}.$$\n\n"
            "**Step 3 — Percentage lost:**\n"
            "$$\\frac{\\Delta KE}{KE_i} \\times 100\\% = \\frac{7.5}{12} \\times 100\\% = 62.5\\%.$$\n\n"
            "**Answers:** (a) $v_f = 1.5$ m/s; (b) 62.5% of initial KE was lost.\n\n"
            "**Sanity check:** $v_f$ is between 0 and 4 m/s (lighter ball's speed) — "
            "correct for a sticking collision where the combined mass moves slower than "
            "the faster initial object. You can verify with the closed-form energy formula: "
            "$\\Delta KE = \\frac{m_1m_2}{2(m_1+m_2)}(v_1-v_2)^2 = 7.5$ J ✓."
        ),
        "checkpoint_solution_he": (
            "**שלב 1 — שימור תנע (לא-אלסטית מוחלטת):**\n"
            "בהתנגשות דביקה, שני הגופים נעים יחד במהירות $v_f$ משותפת. "
            "התנע הכולל לפני שווה לתנע אחרי:\n"
            "$$p_i=1.5\\times4=6\\text{ kg·m/s}.$$\n"
            "$$v_f=\\frac{p_i}{m_1+m_2}=\\frac{6}{4}=1.5\\text{ מ/ש}.$$\n\n"
            "**שלב 2 — אנרגיה קינטית לפני ואחרי:**\n"
            "$$KE_i=\\tfrac{1}{2}(1.5)(16)=12\\text{ ג'ול}.$$\n"
            "$$KE_f=\\tfrac{1}{2}(4)(2.25)=4.5\\text{ ג'ול}.$$\n"
            "$$\\Delta KE=7.5\\text{ ג'ול אבדו לחום ועיוות}.$$\n\n"
            "**שלב 3 — אחוז שאבד:**\n"
            "$$\\frac{7.5}{12}\\times100\\%=62.5\\%.$$\n\n"
            "**תשובות:** (א) $v_f=1.5$ מ\"ש; (ב) 62.5% מה-$KE$ הראשונית אבד.\n\n"
            "**בדיקת הגיון:** $v_f$ בין 0 ל-4 מ\"ש — נכון להתנגשות דביקה "
            "שבה המסה המשולבת (4 ק\"ג) נעה לאט יותר מהכדור המהיר. "
            "אימות: $\\Delta KE=\\frac{1.5\\times2.5}{2\\times4}(4)^2=7.5$ ג'ול ✓."
        ),
    },
    "worked_example_2": {
        "body_en_md": (
            "**Given:** Ball 1 (mass $m$) moves at velocity $v_0$ and collides **elastically** "
            "with Ball 2 (mass $m$) at rest. Show that they exchange velocities: "
            "Ball 1 stops and Ball 2 moves at $v_0$.\n\n"
            "This is the most important special case in 1D elastic collisions — "
            "memorize it for exams. It follows from solving momentum plus KE "
            "conservation simultaneously when both masses are equal.\n\n"
            "### Move 1 — Momentum\n"
            "$$mv_0 + m(0) = mv_1' + mv_2'.$$\n"
            "$$v_1' + v_2' = v_0. \\quad (1)$$\n\n"
            "### Move 2 — Kinetic energy\n"
            "$$\\tfrac{1}{2}mv_0^2 = \\tfrac{1}{2}mv_1'^2 + \\tfrac{1}{2}mv_2'^2.$$\n"
            "$$v_1'^2 + v_2'^2 = v_0^2. \\quad (2)$$\n\n"
            "### Move 3 — Algebraic solution\n"
            "From (1): $v_2' = v_0 - v_1'$. Substitute into (2) and expand:\n"
            "$$v_1'^2 + (v_0-v_1')^2 = v_0^2.$$\n"
            "$$2v_1'^2 - 2v_0 v_1' = 0 \\Rightarrow 2v_1'(v_1' - v_0) = 0.$$\n"
            "$$v_1' = 0 \\quad \\text{or} \\quad v_1' = v_0.$$\n\n"
            "$v_1' = v_0$ means Ball 1 passes through Ball 2 (no collision) — unphysical. So:\n"
            "$$v_1' = 0, \\quad v_2' = v_0.$$\n\n"
            "### Move 4 — Verify with general formula\n"
            "Substituting into the 1D elastic formulas confirms the result without "
            "solving the quadratic from scratch:\n"
            "$v_1' = \\frac{m-m}{m+m}v_0 + \\frac{2m}{m+m}(0) = 0$ ✓. "
            "$v_2' = \\frac{2m}{m+m}v_0 = v_0$ ✓.\n\n"
            "**Conclusion:** Equal-mass elastic collisions **exchange velocities**.\n\n"
            "**Why this matters:** On exams, recognizing equal-mass elastic collisions "
            "saves time — no algebra needed. Always reject the $v_1'=v_0$ solution "
            "physically (it means no collision occurred). Verify with the general "
            "formula as Move 4 confirms both results."
        ),
        "body_he_md": (
            "**נתון:** כדור 1 (מסה $m$) ב-$v_0$ מתנגש **אלסטית** עם כדור 2 ($m$) נח. "
            "הראו שהם מחליפים מהירויות: כדור 1 עוצר, כדור 2 נע ב-$v_0$.\n\n"
            "זה המקרה המיוחד החשוב ביותר בהתנגשות אלסטית 1D — שיננו לבחינות. "
            "הוא נובע מפתרון שימור תנע ו-$K$ יחד כששתי המסות שוות.\n\n"
            "### צעד 1 — תנע\n"
            "$$mv_0=mv_1'+mv_2'\\Rightarrow v_1'+v_2'=v_0. \\quad (1)$$\n\n"
            "### צעד 2 — אנרגיה קינטית\n"
            "$$v_1'^2+v_2'^2=v_0^2. \\quad (2)$$\n\n"
            "### צעד 3 — פתרון אלגברי\n"
            "מ-(1): $v_2'=v_0-v_1'$. הציבו ב-(2) ופתחו סוגריים:\n"
            "$$2v_1'^2-2v_0v_1'=0\\Rightarrow 2v_1'(v_1'-v_0)=0.$$\n"
            "$$v_1'=0 \\text{ או } v_1'=v_0.$$\n\n"
            "$v_1'=v_0$ = מעבר דרך (לא פיזיקלי). לכן:\n"
            "$$v_1'=0, \\quad v_2'=v_0.$$\n\n"
            "### צעד 4 — אימות בנוסחה הכללית\n"
            "הצבה בנוסחאות אלסטית 1D מאשרת את התוצאה בלי לפתור "
            "מחדש את המשוואה הריבועית:\n"
            "$v_1'=\\frac{m-m}{2m}v_0=0$ ✓. $v_2'=\\frac{2m}{2m}v_0=v_0$ ✓.\n\n"
            "**מסקנה:** התנגשות אלסטית בין מסות שוות — **חלפת מהירויות**.\n\n"
            "**למה זה חשוב:** בבחינות, זיהוי מסות שוות אלסטית חוסך זמן — "
            "בלי חישוב מסורבל. דחו תמיד את $v_1'=v_0$ (פירושו: לא הייתה התנגשות). "
            "אמתו בנוסחה הכללית כמו בצעד 4."
        ),
    },
    "checkpoint_2": {
        "checkpoint_solution_en": (
            "**Step 1 — Apply 1D elastic collision formulas:**\n"
            "$$v_1' = \\frac{m_1-m_2}{m_1+m_2}v_1 + \\frac{2m_2}{m_1+m_2}v_2.$$\n"
            "Ball 2 is at rest ($v_2=0$), so:\n"
            "$$v_1' = \\frac{3-1}{3+1}(6) = \\frac{2}{4}(6) = 3\\text{ m/s}$$\n"
            "(same direction as initial).\n\n"
            "**Step 2 — Second ball's velocity:**\n"
            "$$v_2' = \\frac{2m_1}{m_1+m_2}v_1 = \\frac{2(3)}{4}(6) = 9\\text{ m/s}.$$\n\n"
            "**Step 3 — Verify momentum and energy:**\n"
            "Momentum: $3(6) = 3(3) + 1(9) = 18$ kg·m/s ✓.\n"
            "KE: $\\tfrac{1}{2}(3)(36) = 54$ J before; "
            "$\\tfrac{1}{2}(3)(9) + \\tfrac{1}{2}(1)(81) = 13.5 + 40.5 = 54$ J after ✓.\n\n"
            "**Answers:** Ball 1: 3 m/s forward; Ball 2: 9 m/s forward.\n\n"
            "**Note:** The lighter ball receives more speed — this is typical when a heavy "
            "object hits a light stationary target elastically. The heavy ball slows but "
            "continues forward; the light ball is launched at three times the heavy ball's "
            "final speed in this mass ratio ($m_1:m_2=3:1$)."
        ),
        "checkpoint_solution_he": (
            "**שלב 1 — נוסחאות התנגשות אלסטית 1D:**\n"
            "בהתנגשות אלסטית חל שימור תנע **וגם** שימור $K$. "
            "כדור 2 נח ($v_2=0$), לכן:\n"
            "$$v_1'=\\frac{m_1-m_2}{m_1+m_2}v_1=\\frac{3-1}{4}(6)=3\\text{ מ/ש}$$\n"
            "(אותו כיוון — הכדור הכבד מאט אך ממשיך קדימה).\n\n"
            "**שלב 2 — מהירות הכדור השני:**\n"
            "$$v_2'=\\frac{2m_1}{m_1+m_2}v_1=\\frac{2(3)}{4}(6)=9\\text{ מ/ש}.$$\n\n"
            "**שלב 3 — אימות תנע ואנרגיה:**\n"
            "תנע: $3(6)=3(3)+1(9)=18$ kg·m/s ✓.\n"
            "$K$: $\\tfrac{1}{2}(3)(36)=54$ ג'ול לפני; "
            "$\\tfrac{1}{2}(3)(9)+\\tfrac{1}{2}(1)(81)=54$ ג'ול אחרי ✓.\n\n"
            "**תשובות:** כדור 1: 3 מ\"ש קדימה; כדור 2: 9 מ\"ש קדימה.\n\n"
            "**הערה:** הכדור הקל (1 ק\"ג) מקבל יותר מהירות — "
            "טיפוסי כשגוף כבד (3 ק\"ג) פוגע ביעד קל נח. "
            "יחס מסות $3:1$ נותן $v_2'=3v_1'$."
        ),
    },
    "worked_example_3": {
        "body_en_md": (
            "**Given:** A 3 kg ball moving at 4 m/s along the x-axis hits a stationary 2 kg ball. "
            "After the collision, the 3 kg ball moves at 2.5 m/s at 30° above the x-axis. "
            "Find the final speed and direction of the 2 kg ball.\n\n"
            "This is a **2D momentum** problem. We are given one final velocity vector, "
            "so two momentum equations (x and y) determine the unknown vector of ball 2. "
            "No coefficient of restitution or KE equation is needed because the post-collision "
            "state of ball 1 is fully specified.\n\n"
            "### Move 1 — x-component of momentum\n"
            "$$m_1v_1 = m_1v_1'\\cos30° + m_2v_2'\\cos\\theta_2.$$\n"
            "$$3(4) = 3(2.5)\\cos30° + 2v_2'\\cos\\theta_2.$$\n"
            "$$12 = 7.5(0.866) + 2v_2'\\cos\\theta_2 = 6.495 + 2v_2'\\cos\\theta_2.$$\n"
            "$$v_2'\\cos\\theta_2 = 2.753. \\quad (1)$$\n\n"
            "### Move 2 — y-component of momentum\n"
            "$$0 = m_1v_1'\\sin30° - m_2v_2'\\sin\\theta_2.$$\n"
            "$$2v_2'\\sin\\theta_2 = 3(2.5)(0.5) = 3.75.$$\n"
            "$$v_2'\\sin\\theta_2 = 1.875. \\quad (2)$$\n\n"
            "### Move 3 — Combine components\n"
            "Square and add the x and y components to find magnitude, then use arctangent "
            "for the direction angle:\n"
            "$$v_2' = \\sqrt{2.753^2 + 1.875^2} = \\sqrt{7.579 + 3.516} = \\sqrt{11.09} \\approx 3.33\\text{ m/s}.$$\n"
            "$$\\theta_2 = \\arctan\\left(\\frac{1.875}{2.753}\\right) \\approx 34.3° \\text{ below x-axis}.$$\n\n"
            "**Answer:** $v_2' \\approx 3.33$ m/s at $\\approx 34.3°$ below the x-axis.\n\n"
            "**Key insight:** When one final velocity is fully specified in 2D, "
            "momentum alone (two component equations) determines the other — "
            "no KE equation is needed unless elasticity is also given."
        ),
        "body_he_md": (
            "**נתון:** כדור 3 ק\"ג ב-4 מ\"ש (ציר x) מתנגש עם כדור 2 ק\"ג נח. "
            "אחרי ההתנגשות, כדור 3 ק\"ג נע ב-2.5 מ\"ש ב-30° מעל ציר x. "
            "מצאו מהירות וכיוון כדור 2 ק\"ג.\n\n"
            "זו בעיית **תנע דו-ממדית**. נתון וקטור מהירות סופי אחד, "
            "לכן שתי משוואות תנע ($x$ ו-$y$) קובעות את הוקטור הלא ידוע של כדור 2. "
            "אין צורך במקדם שחזור או משוואת $K$ כי מצב כדור 1 אחרי ההתנגשות "
            "מוגדר במלואו.\n\n"
            "### צעד 1 — רכיב x של תנע\n"
            "$$3(4)=3(2.5)\\cos30°+2v_2'\\cos\\theta_2.$$\n"
            "$$12=6.495+2v_2'\\cos\\theta_2\\Rightarrow v_2'\\cos\\theta_2=2.753. \\quad (1)$$\n\n"
            "### צעד 2 — רכיב y של תנע\n"
            "$$0=3(2.5)\\sin30°-2v_2'\\sin\\theta_2.$$\n"
            "$$v_2'\\sin\\theta_2=1.875. \\quad (2)$$\n\n"
            "### צעד 3 — שילוב רכיבים\n"
            "ריבוע וחיבור רכיבי x ו-y למציאת גודל, ואז arctangent לזווית:\n"
            "$$v_2'=\\sqrt{2.753^2+1.875^2}\\approx3.33\\text{ מ/ש}.$$\n"
            "$$\\theta_2=\\arctan(1.875/2.753)\\approx34.3°\\text{ מתחת ל-x}.$$\n\n"
            "**תשובה:** $v_2'\\approx3.33$ מ\"ש ב-$\\approx34.3°$ מתחת לציר x.\n\n"
            "**תובנה מרכזית:** כשנתון וקטור מהירות סופי אחד ב-2D, "
            "תנע בלבד (שתי משוואות רכיב) קובע את השני — "
            "אין צורך ב-$K$ אלא אם ניתנה גם אלסטיות."
        ),
    },
    "method_guide": {
        "body_en_md": (
            "Use this decision table on every collision problem — identifying the type "
            "first prevents applying the wrong conservation law.\n\n"
            "| Type | Known | Equations | Solvable? |\n"
            "|---|---|---|---|\n"
            "| 1D perfectly inelastic | $m_1,m_2,v_1,v_2$ | Momentum (1) | Yes — 1 unknown ($v_f$) |\n"
            "| 1D elastic | $m_1,m_2,v_1,v_2$ | Momentum + KE (2) | Yes — 2 unknowns |\n"
            "| 2D elastic, one angle given | masses, $v_1$, $\\theta_1'$ | Momentum (2) + KE (1) | Yes |\n"
            "| 2D inelastic, one final vector given | $v_1'$, $\\theta_1'$ | Momentum (2) | Yes — 2 unknowns |\n"
            "| 2D inelastic, nothing extra | 4 unknowns | Momentum (2) only | No — under-determined |\n\n"
            "**Step-by-step protocol:**\n"
            "1. Identify collision type (elastic / inelastic / perfectly inelastic).\n"
            "2. Draw before-and-after momentum diagrams with velocity arrows.\n"
            "3. Write momentum conservation: x-component AND y-component separately.\n"
            "4. If elastic, add KE conservation (scalar equation).\n"
            "5. Count equations vs unknowns — verify solvability before algebra.\n"
            "6. Solve; verify $p_{before}=p_{after}$ and (if elastic) $KE_{before}=KE_{after}$."
        ),
        "body_he_md": (
            "השתמשו בטבלת ההחלטה בכל בעיית התנגשות — זיהוי הסוג קודם "
            "מונע שימוש בחוק שימור שגוי.\n\n"
            "| סוג | ידוע | משוואות | פתיר? |\n"
            "|---|---|---|---|\n"
            "| 1D לא-אלסטית מוחלטת | $m$, $v$ | תנע (1) | כן — $v_f$ אחד |\n"
            "| 1D אלסטית | $m$, $v$ | תנע + $K$ (2) | כן — 2 נעלמים |\n"
            "| 2D אלסטית, $\\theta_1'$ נתון | — | 3 משוואות | כן |\n"
            "| 2D לא-אלסטית, $v_1',\\theta_1'$ נתון | — | תנע (2) | כן — 2 נעלמים |\n"
            "| 2D לא-אלסטית, ללא מידע | 4 נעלמים | תנע (2) בלבד | לא — לא מוגדר |\n\n"
            "**פרוטוקול שלב-שלב:**\n"
            "1. זהו סוג התנגשות (אלסטית / לא-אלסטית / לא-אלסטית מוחלטת).\n"
            "2. שרטטו דיאגרמות לפני ואחרי עם חיצי מהירות.\n"
            "3. כתבו שימור תנע: רכיב $x$ **וגם** רכיב $y$ בנפרד.\n"
            "4. אלסטית: הוסיפו שימור $K$ (משוואה נוספת).\n"
            "5. ספרו משוואות מול נעלמים — וודאו פתירות לפני החישוב.\n"
            "6. פתרו; אמתו $p_{לפני}=p_{אחרי}$ ו-(אם אלסטית) $K_{לפני}=K_{אחרי}$."
        ),
    },
    "exercise_set": {
        "body_en_md": (
            "Work through every exercise below. **Try each one before opening the solution** — "
            "the steps matter as much as the final answer. For each problem, first classify "
            "the collision type (elastic, inelastic, or perfectly inelastic), then choose "
            "the correct conservation laws before doing any arithmetic. Draw before-and-after "
            "diagrams for 2D problems and label velocity components. Check momentum (and KE "
            "if elastic) after every solution to catch sign errors early. Problems e9–e11 "
            "connect to nuclear scattering and the center-of-mass frame — preview of "
            "university-level applications. Start with easy problems to build confidence "
            "before tackling nuclear scattering in e9–e11."
        ),
        "body_he_md": (
            "פתרו את כל התרגילים למטה. **נסו כל תרגיל לפני שפותחים את הפתרון** — "
            "הצעדים חשובים לא פחות מהתשובה הסופית. בכל בעיה, קודם סווגו את סוג "
            "ההתנגשות (אלסטית, לא-אלסטית, או לא-אלסטית מוחלטת), ואז בחרו חוקי "
            "שימור נכונים לפני חישוב. שרטטו דיאגרמות לפני/אחרי לבעיות 2D "
            "וסמנו רכיבי מהירות. אמתו תנע (ו-$K$ אם אלסטית) אחרי כל פתרון "
            "כדי לתפוס שגיאות סימן מוקדם. תרגילים e9–e11 מקשרים לפיזור גרעיני "
            "ולמערכת מ\"מ — תצוגה מקדימה ליישומים אוניברסיטאיים. "
            "התחילו מהקלים לפני e9–e11."
        ),
    },
    "pitfall": {
        "body_en_md": (
            "1. **Forgetting momentum is a vector.** In 1D, assign positive and negative "
            "directions consistently. A ball moving left has negative momentum. "
            "Adding $mv$ and $m(-v)$ can give zero — that is correct, not an error.\n\n"
            "2. **Applying KE conservation to an inelastic collision.** Only elastic "
            "collisions conserve KE. For inelastic problems, use momentum only (plus any "
            "given information about the final state).\n\n"
            "3. **Not breaking 2D momentum into x and y components.** Momentum in 2D gives "
            "**two independent equations** — never try to solve with a single scalar equation.\n\n"
            "4. **Assuming equal masses always exchange velocities.** The exchange result "
            "applies ONLY to equal-mass **elastic** 1D collisions. For unequal masses, "
            "use the general formulas every time.\n\n"
            "5. **Neglecting to verify momentum after solving.** Always check "
            "$p_{before} = p_{after}$. This catches sign errors and algebraic mistakes "
            "that otherwise produce plausible-looking wrong numbers."
        ),
        "body_he_md": (
            "1. **תנע הוא וקטור.** ב-1D — הגדירו כיוון חיובי ושמרו עליו. "
            "כדור שנע שמאלה = תנע שלילי. $mv$ ו-$m(-v)$ יכולים להתאפס — זה נכון.\n\n"
            "2. **שימור $K$ בהתנגשות לא-אלסטית.** רק בהתנגשות **אלסטית** מתשמרת $K$. "
            "בלא-אלסטית — תנע בלבד (ועוד מידע על המצב הסופי).\n\n"
            "3. **2D — שני רכיבים נפרדים.** תנע ב-2D נותן **שתי משוואות עצמאיות** — "
            "אף פעם לא לפתור במשוואה יחידה (בלי פירוק לרכיבים).\n\n"
            "4. **חלפת מהירויות — רק למסות שוות אלסטית 1D.** למסות שונות — "
            "השתמשו בנוסחאות הכלליות בכל פעם.\n\n"
            "5. **לאמת תנע אחרי פתרון.** תמיד בדקו $p_{לפני}=p_{אחרי}$. "
            "זה תופס שגיאות סימן וחישוב שגוי שמייצרות מספרים שנראים סבירים."
        ),
    },
    "why_matters": {
        "body_en_md": (
            "Collisions are the bridge between Newton's laws and conservation principles — "
            "once you trust momentum conservation, you can solve impact problems without "
            "ever knowing the collision force or contact time.\n\n"
            "**Builds on:**\n"
            "- `concept:momentum` **Momentum & Impulse** — impulse-momentum theorem is the "
            "microscopic reason total momentum is conserved.\n\n"
            "**Unlocks:**\n"
            "- Nuclear scattering, rocket propulsion (recoil), and center-of-mass motion "
            "in multi-body systems.\n\n"
            "**Why it matters for exams:** Bagrut and university mechanics reward recognizing "
            "collision type instantly and choosing the right number of conservation equations. "
            "The equal-mass elastic exchange and perfectly-inelastic $v_f$ formula appear "
            "repeatedly — drill them until automatic."
        ),
        "body_he_md": (
            "התנגשויות הן הגשר בין חוקי ניוטון לעקרונות שימור — "
            "ברגע שסומכים על שימור תנע, אפשר לפתור בעיות פגיעה "
            "בלי לדעת כוח התנגשות או זמן מגע.\n\n"
            "**מבוסס על:**\n"
            "- `concept:momentum` **תנע ומתקף** — משפט מתקף-תנע הוא הסיבה "
            "המיקרוסקופית לשימור תנע כולל.\n\n"
            "**פותח:**\n"
            "- פיזור גרעיני, דחף (recoil), ותנועת מרכז מסה במערכות רב-גופיות.\n\n"
            "**למה חשוב לבחינות:** בבגרות ומכניקה אוניברסיטאית מעריכים זיהוי מיידי "
            "של סוג ההתנגשות ובחירת מספר משוואות שימור נכון. "
            "חלפת מהירויות אלסטית ונוסחת $v_f$ לא-אלסטית מוחלטת חוזרות — "
            "תרגלו עד שזה אוטומטי."
        ),
    },
    "before_exam": {
        "body_en_md": (
            "### Essential Formulas\n"
            "- **Momentum (always):** $m_1v_1+m_2v_2=m_1v_1'+m_2v_2'$\n"
            "- **Elastic 1D:** $v_1'=\\frac{m_1-m_2}{m_1+m_2}v_1+\\frac{2m_2}{m_1+m_2}v_2$; "
            "$v_2'=\\frac{2m_1}{m_1+m_2}v_1+\\frac{m_2-m_1}{m_1+m_2}v_2$\n"
            "- **Equal mass elastic:** $v_1'\\leftrightarrow v_2'$ (exchange)\n"
            "- **Perfectly inelastic:** $v_f=(m_1v_1+m_2v_2)/(m_1+m_2)$\n"
            "- **KE lost (perfectly inelastic):** "
            "$\\Delta KE=\\frac{m_1m_2}{2(m_1+m_2)}(v_1-v_2)^2$\n"
            "- **CM velocity:** $v_{cm}=(m_1v_1+m_2v_2)/(m_1+m_2)$\n"
            "- **Restitution:** $e=(v_2'-v_1')/(v_1-v_2)$\n\n"
            "### Typical Exam Questions\n"
            "1. Perfectly inelastic — find $v_f$ and $\\Delta KE$ or percentage lost.\n"
            "2. 1D elastic — find $v_1'$ and $v_2'$ (use formulas or CM frame).\n"
            "3. Equal-mass elastic — velocities exchange (instant answer).\n"
            "4. 2D — component momentum equations; combine with trig for magnitude/angle.\n"
            "5. Classify collision — compare $KE$ before and after."
        ),
        "body_he_md": (
            "### נוסחאות חיוניות\n"
            "- **תנע (תמיד):** $m_1v_1+m_2v_2=m_1v_1'+m_2v_2'$\n"
            "- **אלסטית 1D:** $v_1'=\\frac{m_1-m_2}{m_1+m_2}v_1+\\ldots$\n"
            "- **מסות שוות אלסטית:** חלפת מהירויות\n"
            "- **לא-אלסטית מוחלטת:** $v_f=(m_1v_1+m_2v_2)/(m_1+m_2)$\n"
            "- **$K$ שאבד:** $\\Delta KE=\\frac{m_1m_2}{2(m_1+m_2)}(v_1-v_2)^2$\n"
            "- **מהירות מ\"מ:** $v_{\\text{מ\"מ}}=(m_1v_1+m_2v_2)/(m_1+m_2)$\n"
            "- **מקדם שחזור:** $e=(v_2'-v_1')/(v_1-v_2)$\n\n"
            "### שאלות טיפוסיות\n"
            "1. לא-אלסטית מוחלטת — $v_f$ ו-$\\Delta KE$ או אחוז.\n"
            "2. אלסטית 1D — $v_1'$, $v_2'$.\n"
            "3. מסות שוות אלסטית — חלפת מהירויות (תשובה מיידית).\n"
            "4. 2D — משוואות רכיבים; טrig למגניטודה/זווית.\n"
            "5. סיווג — השוו $K$ לפני ואחרי."
        ),
    },
    "summary": {
        "body_en_md": (
            "- **Momentum always conserved** when external forces are negligible: "
            "$m_1v_1+m_2v_2=m_1v_1'+m_2v_2'$.\n"
            "- **Elastic collisions:** KE also conserved → 2 equations for 2 unknowns in 1D.\n"
            "- **Inelastic collisions:** KE not conserved → only momentum equations available.\n"
            "- **Perfectly inelastic:** objects stick, $v_f=(m_1v_1+m_2v_2)/(m_1+m_2)$; "
            "maximum KE loss.\n"
            "- **Equal mass elastic (1D):** velocities exchange — memorize this special case.\n"
            "- **2D collisions:** apply momentum conservation to x and y independently.\n"
            "- **CM frame:** total momentum = 0; elastic collision reverses CM-frame velocities."
        ),
        "body_he_md": (
            "- **תנע מתשמר תמיד** כשכוחות חיצוניים זניחים: "
            "$m_1v_1+m_2v_2=m_1v_1'+m_2v_2'$.\n"
            "- **אלסטית:** גם $K$ מתשמרת → 2 משוואות ל-2 נעלמים ב-1D.\n"
            "- **לא-אלסטית:** $K$ לא מתשמרת → רק משוואות תנע.\n"
            "- **לא-אלסטית מוחלטת:** $v_f$ משותף; אובדן $K$ מקסימלי.\n"
            "- **מסות שוות אלסטית 1D:** חלפת מהירויות — שיננו.\n"
            "- **2D:** שמרו על $x$ ו-$y$ בנפרד.\n"
            "- **מערכת מ\"מ:** תנע כולל = 0; אלסטית הופכת מהירויות במ\"מ."
        ),
    },
})

_QUESTION_EXPLANATIONS = [
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "Perfectly inelastic means the objects stick together, so one shared final "
            "velocity $v_f$ is the only unknown. Apply momentum conservation:\n"
            "$5(2)+3(0)=8v_f$, giving $v_f=10/8=1.25$ m/s.\n\n"
            "**How to think about it:**\n"
            "Identify \"stick together\" as the signal for perfectly inelastic — use "
            "momentum only, never KE conservation. The combined mass $(5+3=8$ kg) moves "
            "slower than the faster initial object (2 m/s).\n\n"
            "**Common slip:**\n"
            "Using elastic formulas or trying to find two separate final velocities. "
            "Dividing by $m_1$ instead of $(m_1+m_2)$.\n\n"
            "**Exam tip:**\n"
            "For any sticking collision, write $(m_1+m_2)v_f$ on the right side "
            "immediately — this pattern appears on every Bagrut mechanics section."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "לא-אלסטית מוחלטת = הגופים נדבקים, לכן מהירות סופית משותפת $v_f$ "
            "היא הנעלם היחיד. שימור תנע:\n"
            "$5(2)+3(0)=8v_f$, ולכן $v_f=10/8=1.25$ מ\"ש.\n\n"
            "**איך לחשוב על זה:**\n"
            "\"נדבקים\" = אות ללא-אלסטית מוחלטת — תנע בלבד, לא שימור $K$. "
            "המסה המשולבת (8 ק\"ג) נעה לאט יותר מהגוף המהיר (2 מ\"ש).\n\n"
            "**טעות נפוצה:**\n"
            "שימוש בנוסחאות אלסטיות או חיפוש שתי מהירויות נפרדות. "
            "חלוקה ב-$m_1$ במקום $(m_1+m_2)$.\n\n"
            "**טיפ לבחינה:**\n"
            "בכל התנגשות דביקה, כתבו מיד $(m_1+m_2)v_f$ בצד ימין — "
            "הדפוס חוזר בכל פרק מכניקה בבגרות."
        ),
    },
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "Equal masses ($m_1=m_2=4$ kg), elastic collision, one ball at rest — "
            "this is the velocity-exchange special case. Ball 1 stops (0 m/s); "
            "Ball 2 moves at 5 m/s to the right.\n\n"
            "**How to think about it:**\n"
            "Before calculating, check: equal mass + elastic + target at rest? "
            "If yes, answer is instant — velocities swap. Verify with momentum: "
            "$4(5)=4(0)+4(5)=20$ kg·m/s ✓.\n\n"
            "**Common slip:**\n"
            "Applying the general formula unnecessarily and making arithmetic errors. "
            "Assuming both balls keep moving forward at reduced speeds (that would "
            "violate KE conservation for equal masses).\n\n"
            "**Exam tip:**\n"
            "This special case saves 2–3 minutes on Bagrut. Recognize it before "
            "writing any equations — but always verify momentum if time permits."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "מסות שוות (4 ק\"ג), התנגשות אלסטית, כדור אחד נח — "
            "מקרה חלפת מהירויות. כדור 1: 0 מ\"ש; כדור 2: 5 מ\"ש ימינה.\n\n"
            "**איך לחשוב על זה:**\n"
            "לפני חישוב: מסות שוות + אלסטית + יעד נח? "
            "אם כן — תשובה מיידית: חילוף מהירויות. "
            "אימות תנע: $4(5)=20$ kg·m/s ✓.\n\n"
            "**טעות נפוצה:**\n"
            "שימוש בנוסחה הכללית מיותר ושגיאות חשבון. "
            "הנחה ששניהם ממשיכים קדימה לאט יותר (מפר שימור $K$ למסות שוות).\n\n"
            "**טיפ לבחינה:**\n"
            "המקרה המיוחד חוסך 2–3 דקות בבגרות. זהו לפני משוואות — "
            "אבל אמתו תנע אם יש זמן."
        ),
    },
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "First find $v_f=6(4)/8=3$ m/s from momentum. Then compute energies: "
            "$KE_i=\\frac{1}{2}(6)(16)=48$ J, $KE_f=\\frac{1}{2}(8)(9)=36$ J, "
            "so $\\Delta KE=12$ J lost.\n\n"
            "**How to think about it:**\n"
            "Perfectly inelastic problems often ask for energy lost — always find "
            "$v_f$ first via momentum, then compute $KE_i$ and $KE_f$ separately. "
            "You can also verify with $\\Delta KE=\\frac{m_1m_2}{2(m_1+m_2)}(v_1-v_2)^2"
            "=\\frac{36}{16}(16)=12$ J.\n\n"
            "**Common slip:**\n"
            "Using KE conservation (would give wrong $v_f$). Computing $\\Delta KE$ "
            "as $KE_i$ alone without subtracting $KE_f$.\n\n"
            "**Exam tip:**\n"
            "When asked for \"energy lost,\" the answer is always positive "
            "($KE_i - KE_f > 0$). Negative $\\Delta KE$ means you swapped before and after."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "קודם $v_f=6(4)/8=3$ מ\"ש מתנע. אז אנרגיות: "
            "$KE_i=48$ ג'ול, $KE_f=36$ ג'ול, $\\Delta KE=12$ ג'ול אבדו.\n\n"
            "**איך לחשוב על זה:**\n"
            "בלא-אלסטית מוחלטת שואלים לעיתים על אנרגיה — "
            "מצאו $v_f$ מתנע קודם, אז $KE_i$ ו-$KE_f$ בנפרד. "
            "אפשר לאמת: $\\Delta KE=\\frac{36}{16}(16)=12$ ג'ול.\n\n"
            "**טעות נפוצה:**\n"
            "שימור $K$ (יתן $v_f$ שגוי). $\\Delta KE$ כ-$KE_i$ בלבד בלי חיסור $KE_f$.\n\n"
            "**טיפ לבחינה:**\n"
            "כששואלים \"אנרגיה שאבדה\", התשובה תמיד חיובית "
            "($KE_i-KE_f>0$). $\\Delta KE$ שלילי = החלפתם לפני ואחרי. "
            "אפשר גם לאמת בנוסחה $\\Delta KE=\\frac{m_1m_2}{2(m_1+m_2)}(v_1-v_2)^2$ "
            "שמחזירה 12 ג'ול — אותה תשובה."
        ),
    },
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "First use momentum to find the unknown velocity: "
            "$2(6)=2(2)+3v_2'\\Rightarrow v_2'=8/3\\approx2.67$ m/s. "
            "Then compare KE: $KE_i=36$ J vs $KE_f=14.67$ J — not equal, "
            "so the collision is **inelastic**.\n\n"
            "**How to think about it:**\n"
            "This is a two-part question: (1) find missing velocity from momentum, "
            "(2) classify by comparing KE. Never assume elastic just because the "
            "problem doesn't say \"inelastic.\"\n\n"
            "**Common slip:**\n"
            "Answering \"elastic\" without computing KE. Using wrong momentum "
            "sign for the 2 kg ball's final velocity. Rounding $8/3$ too early "
            "and getting inconsistent KE values.\n\n"
            "**Exam tip:**\n"
            "\"Is it elastic?\" always means compute both $KE_i$ and $KE_f$ "
            "numerically — do not guess from the numbers in the stem."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "קודם תנע למהירות לא ידועה: "
            "$2(6)=2(2)+3v_2'\\Rightarrow v_2'\\approx2.67$ מ\"ש. "
            "אז השוו $K$: 36 ג'ול לעומת 14.67 ג'ול — לא שווה, "
            "לכן **לא-אלסטית**.\n\n"
            "**איך לחשוב על זה:**\n"
            "שאלה דו-חלקית: (1) מהירות חסרה מתנע, (2) סיווג בהשוואת $K$. "
            "אל תניחו אלסטית רק כי לא כתוב \"לא-אלסטית\".\n\n"
            "**טעות נפוצה:**\n"
            "\"אלסטית\" בלי חישוב $K$. סימן שגוי בתנע. "
            "עיגול $8/3$ מוקדם מדי ו-$K$ לא עקבי.\n\n"
            "**טיפ לבחינה:**\n"
            "\"האם אלסטית?\" = תמיד חשבו $KE_i$ ו-$KE_f$ — "
            "אל תנחשו מהמספרים בנתון."
        ),
    },
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "Apply 1D elastic formulas with $m_1=1$ kg, $m_2=3$ kg, $v_1=8$ m/s, "
            "$v_2=0$:\n"
            "$v_1'=\\frac{1-3}{4}(8)=-4$ m/s (bounces back). "
            "$v_2'=\\frac{2(1)}{4}(8)=4$ m/s forward.\n"
            "Check: momentum $1(8)=1(-4)+3(4)=8$ ✓; KE $32$ J before and after ✓.\n\n"
            "**How to think about it:**\n"
            "When the lighter object hits a heavier stationary target elastically, "
            "the lighter one rebounds (negative $v_1'$). The heavy target moves "
            "forward at a moderate speed.\n\n"
            "**Common slip:**\n"
            "Forgetting the negative sign on $v_1'$ (reporting +4 instead of −4). "
            "Using velocity-exchange rule — that applies only to equal masses.\n\n"
            "**Exam tip:**\n"
            "After solving, always verify both momentum AND KE — examiners give "
            "partial credit for correct method with sign errors, but full credit "
            "requires both checks."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "נוסחאות אלסטית 1D עם $m_1=1$, $m_2=3$, $v_1=8$:\n"
            "$v_1'=\\frac{-2}{4}(8)=-4$ מ\"ש (חוזר). $v_2'=4$ מ\"ש קדימה.\n"
            "אימות: תנע 8 ✓; $K$ 32 ג'ול ✓.\n\n"
            "**איך לחשוב על זה:**\n"
            "כשקל פוגע בכבד נח אלסטית, הקל חוזר ($v_1'$ שלילי). "
            "הכבד נע קדימה במהירות מתונה.\n\n"
            "**טעות נפוצה:**\n"
            "שכחת סימן מינוס ($v_1'=+4$). חלפת מהירויות — רק למסות שוות.\n\n"
            "**טיפ לבחינה:**\n"
            "אחרי פתרון, אמתו תנע **ו**-$K$ — נקודות חלקיות לשיטה נכונה "
            "עם שגיאת סימן, אך נקודות מלאות דורשות שני אימותים."
        ),
    },
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "Objects stick (perfectly inelastic). Momentum with signs: "
            "$2(5)+4(-1)=6v_f$, so $10-4=6v_f$, $v_f=1$ m/s. "
            "Energy: $KE_i=\\frac{1}{2}(2)(25)+\\frac{1}{2}(4)(1)=27$ J, "
            "$KE_f=\\frac{1}{2}(6)(1)=3$ J, $\\Delta KE=24$ J lost.\n\n"
            "**How to think about it:**\n"
            "Head-on collision with opposite velocities — assign signs carefully "
            "(+5 and −1). The combined mass moves in the direction of the larger "
            "momentum (object A here). \"Stick together\" = one $v_f$, momentum only.\n\n"
            "**Common slip:**\n"
            "Ignoring the negative sign on B's velocity (getting $v_f=3$ m/s). "
            "Using KE conservation. Forgetting to use combined mass 6 kg for $KE_f$.\n\n"
            "**Exam tip:**\n"
            "Draw a number line with velocity arrows before writing equations — "
            "sign errors are the #1 cause of lost points in head-on collision problems."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "נדבקים (לא-אלסטית מוחלטת). תנע עם סימנים: "
            "$2(5)+4(-1)=6v_f$, $v_f=1$ מ\"ש. "
            "אנרגיה: $KE_i=27$ ג'ול, $KE_f=3$ ג'ול, $\\Delta KE=24$ ג'ול.\n\n"
            "**איך לחשוב על זה:**\n"
            "התנגשות חזיתית עם מהירויות נגדיות — סימנים (+5 ו-$-1$). "
            "המסה המשולבת נעת בכיוון התנע הגדול (A כאן). "
            "\"נדבקים\" = $v_f$ אחד, תנע בלבד.\n\n"
            "**טעות נפוצה:**\n"
            "התעלמות מסימן B ($v_f=3$). שימור $K$. "
            "שכחת מסה משולבת 6 ק\"ג ל-$KE_f$.\n\n"
            "**טיפ לבחינה:**\n"
            "שרטטו קו מספרים עם חיצי מהירות לפני משוואות — "
            "שגיאות סימן = הסיבה #1 לאיבוד נקודות בהתנגשות חזיתית."
        ),
    },
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "Elastic collision: $m_p=m$, $m_{He}=4m$. "
            "$v_p'=\\frac{m-4m}{5m}v=-\\frac{3}{5}v$ (rebounds). "
            "$v_{He}'=\\frac{2m}{5m}v=\\frac{2}{5}v$. "
            "KE fraction to helium: $\\frac{8mv^2/25}{mv^2/2}=\\frac{16}{25}=64\\%$.\n\n"
            "**How to think about it:**\n"
            "Nuclear scattering problems use the same 1D elastic formulas with "
            "mass ratios. A light projectile hitting a heavy target transfers "
            "more KE when the mass ratio is closer to 1 — here 64% goes to helium.\n\n"
            "**Common slip:**\n"
            "Using $m_{He}=m$ by mistake. Computing fraction as $v_{He}'/v$ "
            "instead of $KE_{He}/KE_i$. Forgetting to square velocity in KE.\n\n"
            "**Exam tip:**\n"
            "For \"fraction of KE transferred,\" always compute "
            "$KE_{target}/KE_{projectile,initial}$ — never use velocity ratio alone."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "אלסטית: $m_p=m$, $m_{He}=4m$. "
            "$v_p'=-\\frac{3}{5}v$ (חוזר). $v_{He}'=\\frac{2}{5}v$. "
            "שבר $K$ לליום: $\\frac{16}{25}=64\\%$.\n\n"
            "**איך לחשוב על זה:**\n"
            "פיזור גרעיני = אותן נוסחאות אלסטית 1D עם יחסי מסות. "
            "קל פוגע בכבד — יותר $K$ עובר כשיחס המסות קרוב ל-1; "
            "כאן 64% לליום.\n\n"
            "**טעות נפוצה:**\n"
            "$m_{He}=m$ בטעות. שבר כ-$v_{He}'/v$ במקום $KE_{He}/KE_i$. "
            "שכחת ריבוע מהירות ב-$K$.\n\n"
            "**טיפ לבחינה:**\n"
            "\"שבר $K$ שהועבר\" = תמיד $KE_{יעד}/KE_{projectile,ראשוני}$ — "
            "לא יחס מהירויות בלבד. בדקו: הפרוטון חוזר ($v_p'<0$) "
            "כי הוא קל מגרעין הליום ($m_p \\ll m_{He}$)."
        ),
    },
    {
        "explanation_en": (
            "**Why this is correct:**\n"
            "2D momentum with equal masses. x: $2(6)=2(3\\cos30°)+2v_{2x}$, "
            "giving $v_{2x}=3.402$ m/s. y: $0=2(3\\sin30°)-2v_{2y}$, "
            "giving $v_{2y}=1.5$ m/s downward. "
            "Magnitude: $v_2=\\sqrt{3.402^2+1.5^2}=3.72$ m/s. "
            "Angle: $\\arctan(1.5/3.402)=23.8°$ below x.\n\n"
            "**How to think about it:**\n"
            "Given one final velocity vector in 2D, write separate x and y momentum "
            "equations. Combine components with Pythagoras and arctangent. "
            "No KE equation needed when the final state of one object is fully specified.\n\n"
            "**Common slip:**\n"
            "Using a single scalar momentum equation. Wrong trig sign for y-component "
            "(ball 2 must go below x-axis to balance ball 1's upward deflection).\n\n"
            "**Exam tip:**\n"
            "In 2D collisions, always sketch the \"after\" diagram first — "
            "the y-equation tells you which side of the x-axis each object lies on."
        ),
        "explanation_he": (
            "**למה זה נכון:**\n"
            "תנע 2D עם מסות שוות. $x$: $v_{2x}=3.402$ מ\"ש. "
            "$y$: $v_{2y}=1.5$ מ\"ש מטה. "
            "גודל: $v_2=3.72$ מ\"ש. זווית: $23.8°$ מתחת ל-x.\n\n"
            "**איך לחשוב על זה:**\n"
            "נתון וקטור מהירות סופי אחד ב-2D — כתבו משוואות $x$ ו-$y$ "
            "נפרדות. שלבו בנוסחת הריבועים ו-$\\arctan$. "
            "אין צורך ב-$K$ כשמצב סופי של גוף אחד מוגדר מלא.\n\n"
            "**טעות נפוצה:**\n"
            "משוואת תנע יחידה (בלי רכיבים). סימן שגוי ברכיב $y$ "
            "(כדור 2 חייב מתחת ל-x לאיזון נסיגת כדור 1).\n\n"
            "**טיפ לבחינה:**\n"
            "ב-2D, שרטטו \"אחרי\" קודם — משוואת $y$ קובעת "
            "באיזה צד של ציר x כל גוף נמצא."
        ),
    },
]
