#!/usr/bin/env python3
"""Author 7 Bagrut 4pt/5pt math lessons — full bilingual content."""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LESSONS_DIR = os.path.join(ROOT, "scripts", "seed_data", "lessons")
INDEX_PATH = os.path.join(ROOT, "apps", "web", "src", "lib", "lessons-index.generated.json")


def sec(kind, title_en, title_he, body_en, body_he):
    return {
        "kind": kind,
        "title_en": title_en,
        "title_he": title_he,
        "body_en_md": body_en,
        "body_he_md": body_he,
    }


def mcq(ord_, diff, stem_en, stem_he, opts_en, opts_he, correct, expl_en, expl_he):
    return {
        "ord": ord_,
        "kind": "mcq",
        "difficulty": diff,
        "stem_en": stem_en,
        "stem_he": stem_he,
        "options_en": opts_en,
        "options_he": opts_he,
        "correct_index": correct,
        "explanation_en": expl_en,
        "explanation_he": expl_he,
    }


def lesson(concept_id, subject, level, title_en, title_he, summary_en, summary_he, minutes, sections, questions, hints):
    return {
        "concept_id": concept_id,
        "subject": subject,
        "level": level,
        "math_track": [level],
        "title_en": title_en,
        "title_he": title_he,
        "summary_en": summary_en,
        "summary_he": summary_he,
        "est_minutes": minutes,
        "sections": sections,
        "questions": questions,
        "agent_hints": hints,
    }


LIMITS_4PT = lesson(
    "limits_4pt",
    "high_school_math_4pt",
    "4pt",
    "Limits — Intuitive Approach",
    "גבולות — גישה אינטואיטיבית",
    "Intuitive limits at 4 units: substitution, algebraic simplification, asymptotes, and the link to derivatives — core Bagrut 804 skills.",
    "גבולות אינטואיטיביים ב-4 יחידות: הצבה, פישוט אלגברי, אסימפטוטות וקשר לנגזרות — מיומנויות מרכזיות בבגרות 804.",
    25,
    [
        sec(
            "intro",
            "What is a limit?",
            "מהו גבול?",
            "The notation $\\lim_{x \\to a} f(x) = L$ means: as $x$ gets **arbitrarily close** to $a$ (without necessarily equalling $a$), the values $f(x)$ get arbitrarily close to $L$.\n\n**Key idea:** We care about the **approach**, not the value at $a$ itself.\n\n**Table of values** (for $f(x) = \\frac{x^2 - 4}{x - 2}$ near $x = 2$):\n\n| $x$ | 1.9 | 1.99 | 2.01 | 2.1 |\n|---|---|---|---|---|\n| $f(x)$ | 3.9 | 3.99 | 4.01 | 4.1 |\n\n$f(2)$ is **undefined** (division by zero), yet the limit as $x \\to 2$ is clearly **4**.\n\n**Limit vs function value:**\n- $\\lim_{x \\to 2} f(x) = 4$ ✓ (approach behaviour)\n- $f(2)$ undefined ✗ (plugging in fails)\n\n**Graph reading:** Trace the curve toward $x = a$ from left and right. If both sides approach the same height $L$, the limit exists.",
            "הסימון $\\lim_{x \\to a} f(x) = L$ פירושו: ככל ש-$x$ מתקרב **כל כך** ל-$a$ (בלי בהכרח להיות שווה ל-$a$), הערכים $f(x)$ מתקרבים **כל כך** ל-$L$.\n\n**רעיון מפתח:** אכפת לנו מה**התקרבות**, לא מהערך ב-$a$ עצמו.\n\n**טבלת ערכים** (ל-$f(x) = \\frac{x^2 - 4}{x - 2}$ ליד $x = 2$):\n\n| $x$ | 1.9 | 1.99 | 2.01 | 2.1 |\n|---|---|---|---|---|\n| $f(x)$ | 3.9 | 3.99 | 4.01 | 4.1 |\n\n$f(2)$ **לא מוגדר** (חילוק באפס), ובכל זאת הגבול כש-$x \\to 2$ הוא בבירור **4**.\n\n**גבול מול ערך הפונקציה:**\n- $\\lim_{x \\to 2} f(x) = 4$ ✓ (התנהגות בהתקרבות)\n- $f(2)$ לא מוגדר ✗ (הצבה נכשלת)\n\n**קריאה מגרף:** עקבו אחרי העקומה לכיוון $x = a$ משמאל ומימין. אם שני הצדדים מתקרבים לאותו גובה $L$, הגבול קיים.",
        ),
        sec(
            "theory",
            "Limits of polynomials and simple functions",
            "גבולות של פולינומים ופונקציות פשוטות",
            "When $f$ is **defined and continuous** at $a$, direct substitution works:\n\n$$\\lim_{x \\to 2} (3x^2 - 1) = 3(4) - 1 = 11.$$\n\n**Limits at infinity** (for rational functions): divide numerator and denominator by the **highest power** of $x$.\n\n$$\\lim_{x \\to \\infty} \\frac{2x + 1}{x - 3} = \\lim_{x \\to \\infty} \\frac{2 + \\frac{1}{x}}{1 - \\frac{3}{x}} = \\frac{2}{1} = 2.$$\n\n**Rules of thumb:**\n- Polynomial at finite $a$: substitute.\n- $\\lim_{x \\to \\infty} \\frac{\\text{deg } n}{\\text{deg } m}$: if $n < m$ → $0$; if $n = m$ → ratio of leading coefficients; if $n > m$ → $\\pm\\infty$.",
            "כאשר $f$ **מוגדרת ורציפה** ב-$a$, הצבה ישירה עובדת:\n\n$$\\lim_{x \\to 2} (3x^2 - 1) = 3(4) - 1 = 11.$$\n\n**גבולות באינסוף** (לפונקציות רציונליות): חלקו מונה ומכנה ב**חזקה הגבוהה ביותר** של $x$.\n\n$$\\lim_{x \\to \\infty} \\frac{2x + 1}{x - 3} = \\lim_{x \\to \\infty} \\frac{2 + \\frac{1}{x}}{1 - \\frac{3}{x}} = \\frac{2}{1} = 2.$$\n\n**כללי אצבע:**\n- פולינום ב-$a$ סופי: הצבה.\n- $\\lim_{x \\to \\infty} \\frac{\\text{מעלה } n}{\\text{מעלה } m}$: אם $n < m$ → $0$; אם $n = m$ → יחס מקדמי ההובלה; אם $n > m$ → $\\pm\\infty$.",
        ),
        sec(
            "worked_example",
            "Limits with $\\frac{0}{0}$ — algebraic simplification",
            "גבולות עם $\\frac{0}{0}$ — פישוט אלגברי",
            "**Factoring and cancelling:**\n\n$$\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2} = \\lim_{x \\to 2} \\frac{(x-2)(x+2)}{x-2} = \\lim_{x \\to 2}(x+2) = 4.$$\n\n**Rationalizing (conjugate):**\n\n$$\\lim_{x \\to 0} \\frac{\\sqrt{x+1} - 1}{x} = \\lim_{x \\to 0} \\frac{(\\sqrt{x+1}-1)(\\sqrt{x+1}+1)}{x(\\sqrt{x+1}+1)} = \\lim_{x \\to 0} \\frac{x}{x(\\sqrt{x+1}+1)} = \\lim_{x \\to 0} \\frac{1}{\\sqrt{x+1}+1} = \\frac{1}{2}.$$\n\n**Bagrut strategy:** When direct substitution gives $\\frac{0}{0}$, try (1) factor, (2) rationalize, (3) combine fractions — then cancel the common factor.",
            "**פירוק לגורמים וביטול:**\n\n$$\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2} = \\lim_{x \\to 2} \\frac{(x-2)(x+2)}{x-2} = \\lim_{x \\to 2}(x+2) = 4.$$\n\n**הגיון (צמוד):**\n\n$$\\lim_{x \\to 0} \\frac{\\sqrt{x+1} - 1}{x} = \\lim_{x \\to 0} \\frac{(\\sqrt{x+1}-1)(\\sqrt{x+1}+1)}{x(\\sqrt{x+1}+1)} = \\lim_{x \\to 0} \\frac{1}{\\sqrt{x+1}+1} = \\frac{1}{2}.$$\n\n**אסטרטגיית בגרות:** כשהצבה נותנת $\\frac{0}{0}$, נסו (1) פירוק, (2) הגיון, (3) איחוד שברים — ואז בטלו את הגורם המשותף.",
        ),
        sec(
            "theory",
            "Asymptotes from limits",
            "אסימפטוטות מגבולות",
            "**Horizontal asymptote (HA):** If $\\lim_{x \\to \\pm\\infty} f(x) = L$, then $y = L$ is a horizontal asymptote.\n\n**Vertical asymptote (VA):** If $\\lim_{x \\to a} f(x) = \\pm\\infty$, then $x = a$ is a vertical asymptote.\n\n**Example:** $f(x) = \\frac{x^2 - 1}{x - 2}$.\n\n- VA: $x = 2$ (denominator → 0, numerator ≠ 0).\n- At $\\infty$: divide by $x$ → $\\lim_{x \\to \\infty} \\frac{x^2-1}{x-2} = \\lim \\frac{x - 1/x}{1 - 2/x} = \\infty$ → no HA (degree numerator > denominator).\n- Oblique asymptote (4pt preview): long division gives $f(x) = x + 2 + \\frac{3}{x-2}$, so $y = x + 2$ as $x \\to \\infty$.",
            "**אסימפטוטה אופקית:** אם $\\lim_{x \\to \\pm\\infty} f(x) = L$, אז $y = L$ היא אסימפטוטה אופקית.\n\n**אסימפטוטה אנכית:** אם $\\lim_{x \\to a} f(x) = \\pm\\infty$, אז $x = a$ היא אסימפטוטה אנכית.\n\n**דוגמה:** $f(x) = \\frac{x^2 - 1}{x - 2}$.\n\n- אנכית: $x = 2$ (מכנה → 0, מונה ≠ 0).\n- ב-$\\infty$: חלוקה ב-$x$ → $\\lim_{x \\to \\infty} \\frac{x^2-1}{x-2} = \\infty$ → אין אופקית (מעלה מונה > מכנה).\n- אלכסונית (תצוגה מקדימה): חלוקה ארוכה נותנת $f(x) = x + 2 + \\frac{3}{x-2}$, כלומר $y = x + 2$ כש-$x \\to \\infty$.",
        ),
        sec(
            "summary",
            "Connection to derivatives",
            "קשר לנגזרות",
            "The derivative is defined as a **limit of the difference quotient**:\n\n$$f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}.$$\n\n**Geometric meaning:** $f'(a)$ is the slope of the **tangent line** at $(a, f(a))$ — the limit of secant slopes as the second point slides toward the first.\n\n**Preview:** Limits let us define instantaneous rate of change. In the next lessons you will use $f'(x) = 0$ for extrema and $f''(x)$ for concavity — all built on limits.",
            "הנגזרת מוגדרת כ**גבול מנה ההפרשים**:\n\n$$f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}.$$\n\n**משמעות גיאומטרית:** $f'(a)$ הוא שיפוע **המשיק** ב-$(a, f(a))$ — גבול שיפועי המיתרים כשהנקודה השנייה מתקרבת לראשונה.\n\n**תצוגה מקדימה:** גבולות מאפשרים להגדיר קצב שינוי רגעי. בשיעורים הבאים תשתמשו ב-$f'(x) = 0$ לקיצון וב-$f''(x)$ לקעירות — הכל בנוי על גבולות.",
        ),
    ],
    [
        mcq(1, "easy", "Evaluate $\\lim_{x \\to 3} (2x^2 - x + 1)$.", "חשבו $\\lim_{x \\to 3} (2x^2 - x + 1)$.",
            ["$16$", "$17$", "$18$", "$19$"], ["$16$", "$17$", "$18$", "$19$"], 0,
            "Direct substitution: $2(9) - 3 + 1 = 18 - 3 + 1 = 16$.", "הצבה ישירה: $2(9) - 3 + 1 = 16$."),
        mcq(2, "medium", "Find $\\lim_{x \\to \\infty} \\frac{3x + 2}{x - 5}$.", "מצאו $\\lim_{x \\to \\infty} \\frac{3x + 2}{x - 5}$.",
            ["$0$", "$3$", "$\\infty$", "$-3$"], ["$0$", "$3$", "$\\infty$", "$-3$"], 1,
            "Divide by $x$: $\\frac{3 + 2/x}{1 - 5/x} \\to 3$.", "חלוקה ב-$x$: $\\frac{3 + 2/x}{1 - 5/x} \\to 3$."),
        mcq(3, "medium", "Evaluate $\\lim_{x \\to 1} \\frac{x^2 - 1}{x - 1}$.", "חשבו $\\lim_{x \\to 1} \\frac{x^2 - 1}{x - 1}$.",
            ["$0$", "$1$", "$2$", "Does not exist"], ["$0$", "$1$", "$2$", "לא קיים"], 2,
            "Factor: $\\frac{(x-1)(x+1)}{x-1} = x+1 \\to 2$.", "פירוק: $\\frac{(x-1)(x+1)}{x-1} = x+1 \\to 2$."),
        mcq(4, "medium", "What is the horizontal asymptote of $f(x) = \\frac{5x + 1}{2x - 3}$?", "מהי האסימפטוטה האופקית של $f(x) = \\frac{5x + 1}{2x - 3}$?",
            ["$y = 5$", "$y = \\frac{5}{2}$", "$y = 0$", "$x = \\frac{3}{2}$"], ["$y = 5$", "$y = \\frac{5}{2}$", "$y = 0$", "$x = \\frac{3}{2}$"], 1,
            "Equal degrees → ratio of leading coefficients: $\\frac{5}{2}$.", "מעלות שוות → יחס מקדמי ההובלה: $\\frac{5}{2}$."),
        mcq(5, "hard", "Using the limit definition, find $f'(2)$ for $f(x) = x^2$.", "בעזרת הגדרת הגבול, מצאו $f'(2)$ עבור $f(x) = x^2$.",
            ["$2$", "$4$", "$8$", "$1$"], ["$2$", "$4$", "$8$", "$1$"], 1,
            "$f'(2) = \\lim_{h\\to 0}\\frac{(2+h)^2-4}{h} = \\lim_{h\\to 0}(4+h) = 4$.", "$f'(2) = \\lim_{h\\to 0}\\frac{(2+h)^2-4}{h} = 4$."),
    ],
    "At 4pt, limits are intuitive — never ε-δ. Students confuse limit with function value; always show a table or graph when f(a) is undefined. For 0/0 forms, factor or rationalize before cancelling. Horizontal asymptotes come from x→±∞ limits; vertical from x→a with ±∞. The derivative-as-limit preview connects to lesson:derivatives_intro.",
)

FUNCTION_ANALYSIS_4PT = lesson(
    "function_analysis_4pt",
    "high_school_math_4pt",
    "4pt",
    "Function Analysis at 4pt Level",
    "חקירת פונקציה — רמת 4 יחידות",
    "Standard Bagrut function investigation: domain, intercepts, monotonicity from f', extrema, asymptotes, and optimization.",
    "חקירת פונקציה סטנדרטית בבגרות: תחום, חיתוכים, חד-מונוטוניות מ-f', קיצון, אסימפטוטות ואופטימיזציה.",
    30,
    [
        sec("intro", "Function families at 4pt", "משפחות פונקציות ב-4 יחידות",
            "At 4 units you investigate four main families:\n\n1. **Polynomials** $f(x) = ax^n + \\cdots$ — smooth, defined everywhere.\n2. **Rational** $f(x) = \\frac{P(x)}{Q(x)}$ — domain excludes zeros of $Q$; vertical asymptotes possible.\n3. **Exponential** $f(x) = a^x$, $a > 0$ — always positive, horizontal asymptote often at $y = 0$.\n4. **Logarithmic** $f(x) = \\log_a x$ — domain $x > 0$, vertical asymptote at $x = 0$.\n\nEach family has characteristic behaviour: where it is defined, how it grows, and what asymptotes to expect.",
            "ב-4 יחידות חוקרים ארבע משפחות עיקריות:\n\n1. **פולינומים** — חלקים, מוגדרים בכל מקום.\n2. **רציונליות** $\\frac{P(x)}{Q(x)}$ — תחום ללא אפסי $Q$; אסימפטוטות אנכיות אפשריות.\n3. **מעריכיות** $a^x$ — תמיד חיוביות, לעיתים אסימפטוטה אופקית ב-$y = 0$.\n4. **לוגריתמיות** — תחום $x > 0$, אסימפטוטה אנכית ב-$x = 0$.\n\nלכל משפחה התנהגות אופיינית: תחום, צמיחה ואסימפטוטות."),
        sec("theory", "Standard investigation steps", "שלבי חקירה סטандартיים",
            "The classic Bagrut question **\"חקור את הפונקציה ושרטט את גרפה\"** follows this checklist:\n\n1. **Domain** — where is $f$ defined?\n2. **Intercepts** — $f(0)$ (y-axis); solve $f(x) = 0$ (x-axis).\n3. **Derivative** $f'(x)$ — find critical points ($f' = 0$ or undefined).\n4. **Monotonicity** — sign chart of $f'$: $+$ → increasing, $-$ → decreasing.\n5. **Local extrema** — max/min at sign changes of $f'$.\n6. **Asymptotes** — from limits (horizontal/vertical/oblique).\n7. **Sketch** — connect all features with a smooth curve.",
            "שאלת הבגרות הקלאסית **\"חקור את הפונקציה ושרטט את גרפה\"** עוקבת אחרי רשימה:\n\n1. **תחום הגדרה**\n2. **חיתוכים** — $f(0)$; פתרון $f(x) = 0$\n3. **נגזרת** $f'(x)$ — נקודות קריטיות\n4. **חד-מונוטוניות** — טבלת סימן של $f'$\n5. **קיצון מקומי** — מקס/מין בשינוי סימן\n6. **אסימפטוטות** — מגבולות\n7. **סקיצה** — חיבור כל המאפיינים"),
        sec("worked_example", "Worked example: rational function", "דוגמה פתורה: פונקציה רציונלית",
            "$f(x) = \\frac{x^2 - 1}{x + 1}$. For $x \\neq -1$, factor: $f(x) = \\frac{(x-1)(x+1)}{x+1} = x - 1$.\n\n- **Domain:** $\\mathbb{R} \\setminus \\{-1\\}$.\n- **Hole (removable discontinuity):** at $x = -1$ the simplified form gives $y = -2$, but original undefined → **hole** at $(-1, -2)$.\n- **$f'(x) = 1$** — always increasing on each interval of domain.\n- **No local extrema** ($f'$ never zero).\n- **Oblique asymptote:** as $x \\to \\pm\\infty$, $f(x) \\to x - 1$, so $y = x - 1$.\n- **Sketch:** straight line $y = x - 1$ with a hole at $(-1, -2)$.",
            "$f(x) = \\frac{x^2 - 1}{x + 1}$. ל-$x \\neq -1$: $f(x) = x - 1$.\n\n- **תחום:** $\\mathbb{R} \\setminus \\{-1\\}$.\n- **חור:** ב-$x = -1$ הצורה המפושטת נותנת $y = -2$, אך המקורית לא מוגדרת → **חור** ב-$(-1, -2)$.\n- **$f'(x) = 1$** — תמיד עולה.\n- **אין קיצון מקומי**.\n- **אסימפטוטה אלכסונית:** $y = x - 1$.\n- **סקיצה:** ישר $y = x - 1$ עם חור ב-$(-1, -2)$."),
        sec("worked_example", "Worked example: exponential", "דוגמה פתורה: מעריכית",
            "$f(x) = xe^{-x}$.\n\n- **Domain:** $\\mathbb{R}$.\n- **$f(0) = 0$** — passes through origin.\n- **$f'(x) = e^{-x}(1 - x)$** → $f' = 0$ at $x = 1$ (**local maximum**).\n- **$f''(x) = e^{-x}(x - 2)$** → $f'' = 0$ at $x = 2$ (**inflection point**).\n- **$\\lim_{x \\to \\infty} f(x) = 0$** — horizontal asymptote $y = 0$.\n- **$\\lim_{x \\to -\\infty} f(x) = -\\infty$**.\n- **Sketch:** rises to max at $(1, e^{-1})$, then decays toward $y = 0$.",
            "$f(x) = xe^{-x}$.\n\n- **תחום:** $\\mathbb{R}$.\n- **$f(0) = 0$**.\n- **$f'(x) = e^{-x}(1 - x)$** → מקסימום ב-$x = 1$.\n- **$f''(x) = e^{-x}(x - 2)$** → נקודת פיתול ב-$x = 2$.\n- **$\\lim_{x \\to \\infty} f(x) = 0$** — אסימפטוטה אופקית $y = 0$.\n- **סקיצה:** עולה למקס ב-$(1, e^{-1})$, יורדת ל-$y = 0$."),
        sec("summary", "Word problems and optimization", "בעיות מילוליות ואופטימיזציה",
            "**Classic Bagrut box problem:** An open box is made from a $12 \\times 12$ cm square by cutting squares of side $x$ from each corner.\n\n- Base: $(12 - 2x) \\times (12 - 2x)$\n- Height: $x$\n- Volume: $V(x) = x(12 - 2x)^2$, domain $0 < x < 6$\n\nExpand: $V(x) = 4x^3 - 48x^2 + 144x$.\n\n$V'(x) = 12x^2 - 96x + 144 = 12(x^2 - 8x + 12) = 12(x-2)(x-6)$.\n\nCritical point in domain: $x = 2$ → **maximum volume** $V(2) = 2 \\cdot 8^2 = 128$ cm³.",
            "**בעיית הקופסה הקלאסית:** קופסה פתוחה מ-$12 \\times 12$ ס\"מ — חותכים ריבועים צלע $x$ מכל פינה.\n\n- בסיס: $(12 - 2x)^2$, גובה: $x$\n- נפח: $V(x) = x(12 - 2x)^2$, תחום $0 < x < 6$\n\n$V'(x) = 12(x-2)(x-6)$ → נקודה קריטית: $x = 2$ → **נפח מקסימלי** $128$ סמ\"ק."),
    ],
    [
        mcq(1, "easy", "What is the domain of $f(x) = \\frac{x + 1}{x^2 - 4}$?", "מהו תחום ההגדרה של $f(x) = \\frac{x + 1}{x^2 - 4}$?",
            ["$\\mathbb{R}$", "$\\mathbb{R} \\setminus \\{-2, 2\\}$", "$x > 0$", "$\\mathbb{R} \\setminus \\{2\\}$"],
            ["$\\mathbb{R}$", "$\\mathbb{R} \\setminus \\{-2, 2\\}$", "$x > 0$", "$\\mathbb{R} \\setminus \\{2\\}$"], 1,
            "Denominator $x^2 - 4 = (x-2)(x+2) \\neq 0$ → exclude $x = \\pm 2$.", "מכנה ≠ 0 → פרט $x = \\pm 2$."),
        mcq(2, "medium", "If $f'(x) = (x-1)(x-3)$, where is $f$ increasing?", "אם $f'(x) = (x-1)(x-3)$, היכן $f$ עולה?",
            ["$1 < x < 3$", "$x < 1$ or $x > 3$", "$x > 1$ only", "Everywhere"], ["$1 < x < 3$", "$x < 1$ or $x > 3$", "$x > 1$ only", "בכל מקום"], 1,
            "$f' > 0$ when both factors same sign: $x < 1$ or $x > 3$.", "$f' > 0$ כששני הגורמים באותו סימן: $x < 1$ או $x > 3$."),
        mcq(3, "medium", "If $f''(x) = x - 2$, where is $f$ concave up?", "אם $f''(x) = x - 2$, היכן $f$ קעירה למעלה?",
            ["$x < 2$", "$x > 2$", "$x = 2$ only", "Nowhere"], ["$x < 2$", "$x > 2$", "$x = 2$ בלבד", "בשום מקום"], 1,
            "Concave up when $f'' > 0$ → $x > 2$.", "קעירות למעלה כש-$f'' > 0$ → $x > 2$."),
        mcq(4, "medium", "A rational function has $\\lim_{x \\to \\infty} f(x) = 3$. This indicates:", "לפונקציה רציונלית $\\lim_{x \\to \\infty} f(x) = 3$. זה מצביע על:",
            ["Vertical asymptote $x = 3$", "Horizontal asymptote $y = 3$", "Hole at $(3, 0)$", "Local max at $y = 3$"],
            ["אסימפטוטה אנכית $x = 3$", "אסימפטוטה אופקית $y = 3$", "חור ב-$(3, 0)$", "מקס מקומי ב-$y = 3$"], 1,
            "Limit at infinity equals constant L → horizontal asymptote y = L.", "גבול באינסוף = קבוע L → אסימפטוטה אופקית y = L."),
        mcq(5, "hard", "Open box: $V(x) = x(12-2x)^2$. Which $x$ maximizes volume (domain $0 < x < 6$)?", "קופסה פתוחה: $V(x) = x(12-2x)^2$. איזה $x$ ממקסם נפח?",
            ["$x = 6$", "$x = 4$", "$x = 2$", "$x = 3$"], ["$x = 6$", "$x = 4$", "$x = 2$", "$x = 3$"], 2,
            "$V'(x) = 12(x-2)(x-6) = 0$ → $x = 2$ in domain; sign change + to − → max.", "$V'(x) = 12(x-2)(x-6)$ → $x = 2$; שינוי סימן → מקס."),
    ],
    "Function investigation is THE signature 4pt Bagrut task. Students skip domain or forget holes in rationals. f' sign chart is more reliable than second derivative test at 4pt. Optimization: define V(x), state domain, set V'=0, verify max/min. Link asymptotes back to lesson:limits_4pt.",
)

INTEGRALS_4PT = lesson(
    "integrals_4pt",
    "high_school_math_4pt",
    "4pt",
    "Integration at 4pt Level",
    "אינטגרציה — רמת 4 יחידות",
    "Antiderivatives, definite integrals, area under and between curves, and velocity/distance applications at Bagrut 4 units.",
    "פונקציה קדומה, אינטגרל מסוים, שטח מתחת ושטח בין עקומות, ויישומי מהירות/מרחק ב-4 יחידות.",
    30,
    [
        sec("intro", "Antiderivative review", "חזרה על פונקציה קדומה",
            "If $F'(x) = f(x)$, then $F$ is an **antiderivative** of $f$ and we write:\n\n$$\\int f(x)\\,dx = F(x) + C$$\n\n**Power rule:** $\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C$ ($n \\neq -1$).\n\n**Linearity:** $\\int [af(x) + bg(x)]\\,dx = a\\int f + b\\int g$.\n\n**Standard integrals (4pt):**\n- $\\int e^x\\,dx = e^x + C$\n- $\\int \\frac{1}{x}\\,dx = \\ln|x| + C$ (for $x > 0$ in 4pt: $\\ln x + C$)",
            "אם $F'(x) = f(x)$, אז $F$ היא **פונקציה קדומה** של $f$:\n\n$$\\int f(x)\\,dx = F(x) + C$$\n\n**כלל החזקה:** $\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C$.\n\n**לינאריות:** $\\int [af + bg]\\,dx = a\\int f + b\\int g$.\n\n**אינטגרלs סטנדרטיים:**\n- $\\int e^x\\,dx = e^x + C$\n- $\\int \\frac{1}{x}\\,dx = \\ln x + C$ (ל-$x > 0$)"),
        sec("theory", "Definite integrals and area", "אינטגרל מסוים ושטח",
            "**Fundamental Theorem:** If $F' = f$, then\n\n$$\\int_a^b f(x)\\,dx = F(b) - F(a).$$\n\n**Signed area:** regions where $f(x) < 0$ contribute **negative** area.\n\n**Total area** on $[a,b]$: split at zeros, then\n\n$$\\text{Area} = \\int_a^b |f(x)|\\,dx.$$\n\n**Worked example:** $\\int_0^3 (x^2 - x)\\,dx$.\n\nAntiderivative: $\\frac{x^3}{3} - \\frac{x^2}{2}$.\n\n$\\left[\\frac{x^3}{3} - \\frac{x^2}{2}\\right]_0^3 = 9 - \\frac{9}{2} = \\frac{9}{2}$.\n\nSince $x^2 - x = x(x-1) \\geq 0$ on $[0,3]$, this equals the geometric area.",
            "**משפט יסוד:** אם $F' = f$:\n\n$$\\int_a^b f(x)\\,dx = F(b) - F(a).$$\n\n**שטח מסומן:** אזורים עם $f(x) < 0$ תורמים שטח **שלילי**.\n\n**שטח כולל:** $\\int_a^b |f(x)|\\,dx$.\n\n**דוגמה:** $\\int_0^3 (x^2 - x)\\,dx = \\frac{9}{2}$."),
        sec("worked_example", "Integration of rational and exponential functions", "אינטגרציה של רציונליות ומעריכיות",
            "When degree of numerator $\\geq$ degree of denominator, use **polynomial long division** first.\n\n$$\\int \\frac{2x + 1}{x - 1}\\,dx: \\quad \\frac{2x+1}{x-1} = 2 + \\frac{3}{x-1}$$\n\n$$\\int = 2x + 3\\ln|x-1| + C.$$\n\n**Simple exponential:** $\\int e^{2x}\\,dx$. Let $u = 2x$, $du = 2\\,dx$:\n\n$$\\int e^{2x}\\,dx = \\frac{1}{2}e^{2x} + C.$$\n\nAt 4pt this is the only substitution you need — full u-sub is 5pt.",
            "כשמעלה המונה $\\geq$ מעלה המכנה — **חלוקת פולינומים**.\n\n$$\\int \\frac{2x + 1}{x - 1}\\,dx = 2x + 3\\ln|x-1| + C.$$\n\n**מעריכית:** $\\int e^{2x}\\,dx = \\frac{1}{2}e^{2x} + C$ (הצבה $u = 2x$).\n\nב-4 יח' זו ההצבה היחידה — u-sub מלא ב-5 יח'."),
        sec("worked_example", "Area between curves", "שטח בין עקומות",
            "If $f(x) \\geq g(x)$ on $[a,b]$:\n\n$$\\text{Area} = \\int_a^b [f(x) - g(x)]\\,dx.$$\n\n**Bagrut example:** Area between $y = x^2$ and $y = 2x$.\n\nIntersection: $x^2 = 2x \\Rightarrow x(x-2) = 0$ → $x = 0, 2$.\n\nOn $[0,2]$: $2x \\geq x^2$ (check at $x=1$: $2 > 1$).\n\n$$\\text{Area} = \\int_0^2 (2x - x^2)\\,dx = \\left[x^2 - \\frac{x^3}{3}\\right]_0^2 = 4 - \\frac{8}{3} = \\frac{4}{3}.$$\n\nAlways: find intersections, identify top curve, integrate (top − bottom).",
            "אם $f(x) \\geq g(x)$ ב-$[a,b]$:\n\n$$\\text{Area} = \\int_a^b [f(x) - g(x)]\\,dx.$$\n\n**דוגמה:** שטח בין $y = x^2$ ו-$y = 2x$.\n\nחיתוך: $x = 0, 2$. ב-$[0,2]$: $2x \\geq x^2$.\n\n$$\\text{Area} = \\int_0^2 (2x - x^2)\\,dx = \\frac{4}{3}.$$\n\nתמיד: מצאו חיתוכים, זהו עקומה עליונה, אינטגרציה (עליון − תחתון)."),
        sec("summary", "Applications: distance and total change", "יישומים: מרחק ושינוי כולל",
            "If $v(t)$ is velocity:\n- **Displacement:** $\\int_a^b v(t)\\,dt$ (signed — direction matters).\n- **Total distance:** $\\int_a^b |v(t)|\\,dt$.\n\n**Example:** $v(t) = 3 - t$ on $[0, 4]$. Zero at $t = 3$.\n\nDisplacement: $\\int_0^4 (3-t)\\,dt = [3t - t^2/2]_0^4 = 12 - 8 = 4$ m.\n\nTotal distance: $\\int_0^3 (3-t)\\,dt + \\int_3^4 (t-3)\\,dt = 4.5 + 0.5 = 5$ m.\n\n**Profit:** if $R'(t)$ is marginal revenue rate, total profit over $[a,b]$ is $\\int_a^b R'(t)\\,dt = R(b) - R(a)$.",
            "אם $v(t)$ מהירות:\n- **העתקה:** $\\int_a^b v(t)\\,dt$ (מסומן).\n- **מרחק כולל:** $\\int_a^b |v(t)|\\,dt$.\n\n**דוגמה:** $v(t) = 3 - t$ ב-$[0, 4]$. אפס ב-$t = 3$.\n\nהעתקה = 4 מ'. מרחק כולל = 5 מ'.\n\n**רווח:** $\\int R'(t)\\,dt = R(b) - R(a)$."),
    ],
    [
        mcq(1, "easy", "Find $\\int (3x^2 + 2x)\\,dx$.", "מצאו $\\int (3x^2 + 2x)\\,dx$.",
            ["$x^3 + x^2 + C$", "$6x + 2 + C$", "$x^3 + 2x^2 + C$", "$3x^3 + x^2 + C$"],
            ["$x^3 + x^2 + C$", "$6x + 2 + C$", "$x^3 + 2x^2 + C$", "$3x^3 + x^2 + C$"], 0,
            "$\\int 3x^2 = x^3$, $\\int 2x = x^2$.", "$\\int 3x^2 = x^3$, $\\int 2x = x^2$."),
        mcq(2, "medium", "Evaluate $\\int_0^2 x^2\\,dx$.", "חשבו $\\int_0^2 x^2\\,dx$.",
            ["$\\frac{8}{3}$", "$4$", "$2$", "$\\frac{4}{3}$"], ["$\\frac{8}{3}$", "$4$", "$2$", "$\\frac{4}{3}$"], 0,
            "$\\left[\\frac{x^3}{3}\\right]_0^2 = \\frac{8}{3}$.", "$\\left[\\frac{x^3}{3}\\right]_0^2 = \\frac{8}{3}$."),
        mcq(3, "medium", "Area under $y = x$ from $x = 0$ to $x = 3$:", "שטח מתחת ל-$y = x$ מ-$0$ עד $3$:",
            ["$3$", "$\\frac{9}{2}$", "$6$", "$9$"], ["$3$", "$\\frac{9}{2}$", "$6$", "$9$"], 1,
            "$\\int_0^3 x\\,dx = \\frac{x^2}{2}\\big|_0^3 = \\frac{9}{2}$.", "$\\int_0^3 x\\,dx = \\frac{9}{2}$."),
        mcq(4, "hard", "Area between $y = x^2$ and $y = x$ on $[0,1]$:", "שטח בין $y = x^2$ ו-$y = x$ ב-$[0,1]$:",
            ["$\\frac{1}{6}$", "$\\frac{1}{3}$", "$\\frac{1}{2}$", "$1$"], ["$\\frac{1}{6}$", "$\\frac{1}{3}$", "$\\frac{1}{2}$", "$1$"], 0,
            "$\\int_0^1 (x - x^2)\\,dx = \\frac{1}{2} - \\frac{1}{3} = \\frac{1}{6}$.", "$\\int_0^1 (x - x^2)\\,dx = \\frac{1}{6}$."),
        mcq(5, "hard", "Velocity $v(t) = 2t$ m/s for $0 \\leq t \\leq 3$. Displacement?", "מהירות $v(t) = 2t$ מ'/ש' ל-$0 \\leq t \\leq 3$. העתקה?",
            ["$3$ m", "$6$ m", "$9$ m", "$18$ m"], ["$3$ מ'", "$6$ מ'", "$9$ מ'", "$18$ מ'"], 2,
            "$\\int_0^3 2t\\,dt = t^2\\big|_0^3 = 9$ m.", "$\\int_0^3 2t\\,dt = 9$ מ'."),
    ],
    "4pt integration stops at polynomial long division + simple exp substitution. Students forget +C on indefinite integrals and confuse signed area with total area. For between-curves problems, always find intersection points first. Links to lesson:derivatives_intro for FTC intuition.",
)

IMPLICIT_DIFFERENTIATION = lesson(
    "implicit_differentiation",
    "high_school_math_5pt",
    "5pt",
    "Implicit Differentiation",
    "גזירה סתומה",
    "Differentiate curves defined implicitly, find tangent lines, and solve related-rates problems — core 5pt Bagrut calculus.",
    "גזירה של עקומות מוגדרות באופן סתום, משיקים ובעיות קצבי שינוי קשורים — ליבת חשבון 5 יח'.",
    25,
    [
        sec("intro", "Explicit vs implicit functions", "פונקציה מפורשת מול סתומה",
            "**Explicit:** $y = f(x)$ — $y$ is isolated (e.g. $y = x^2 + 1$).\n\n**Implicit:** $F(x, y) = 0$ — relationship not solved for $y$ (e.g. $x^2 + y^2 = r^2$).\n\nCircles, ellipses, and many curves are easier **implicitly**. The idea: differentiate **both sides** with respect to $x$, treating $y$ as a function of $x$.",
            "**מפורשת:** $y = f(x)$.\n\n**סתומה:** $F(x, y) = 0$ — הקשר לא פתור ל-$y$ (למשל $x^2 + y^2 = r^2$).\n\nמעגלים, אליפסות ועקומות רבות קלים יותר **בצורה סתומה**. הרעיון: גזרו **שני אגפים** ב-$x$, מתייחסים ל-$y$ כפונקציה של $x$."),
        sec("theory", "The chain rule for $\\frac{d}{dx}[g(y)]$", "כלל השרשרת ל-$\\frac{d}{dx}[g(y)]$",
            "Since $y = y(x)$, by the chain rule:\n\n$$\\frac{d}{dx}[y^2] = 2y \\cdot \\frac{dy}{dx}, \\quad \\frac{d}{dx}[\\sin y] = \\cos y \\cdot \\frac{dy}{dx}.$$\n\n**General pattern:** $\\frac{d}{dx}[f(y)] = f'(y) \\cdot y'$.\n\nWrite $y' = \\frac{dy}{dx}$ for brevity. This is the **key step** in every implicit differentiation problem.",
            "מכיוון ש-$y = y(x)$, לפי כלל השרשרת:\n\n$$\\frac{d}{dx}[y^2] = 2y \\cdot y', \\quad \\frac{d}{dx}[\\sin y] = \\cos y \\cdot y'.$$\n\n**כלל כללי:** $\\frac{d}{dx}[f(y)] = f'(y) \\cdot y'$.\n\nזה **השלב המפתח** בכל בעיית גזירה סתומה."),
        sec("worked_example", "Worked example: circle", "דוגמה פתורה: מעגל",
            "$x^2 + y^2 = 25$. Differentiate:\n\n$$2x + 2y \\cdot y' = 0 \\Rightarrow y' = -\\frac{x}{y}.$$\n\n**Tangent at $(3, 4)$:** slope $= -\\frac{3}{4}$.\n\n$$y - 4 = -\\frac{3}{4}(x - 3).$$\n\n**Geometric check:** radius from origin to $(3,4)$ has slope $\\frac{4}{3}$; tangent slope $-\\frac{3}{4}$ — **perpendicular** ✓.",
            "$x^2 + y^2 = 25$. גזירה:\n\n$$2x + 2y \\cdot y' = 0 \\Rightarrow y' = -\\frac{x}{y}.$$\n\n**משיק ב-$(3, 4)$:** שיפוע $= -\\frac{3}{4}$.\n\n$$y - 4 = -\\frac{3}{4}(x - 3).$$\n\n**בדיקה גאומטרית:** רדיוס ⟂ משיק ✓."),
        sec("worked_example", "More worked examples", "דוגמאות נוספות",
            "**Folium of Descartes:** $x^3 + y^3 = 6xy$.\n\n$$3x^2 + 3y^2 y' = 6y + 6xy' \\Rightarrow y' = \\frac{2y - x^2}{y^2 - 2x}.$$\n\n**Ellipse** $\\frac{x^2}{9} + \\frac{y^2}{4} = 1$ at $\\left(\\frac{3}{\\sqrt{2}}, \\sqrt{2}\\right)$:\n\nImplicit diff: $\\frac{2x}{9} + \\frac{2y}{4}y' = 0$ → $y' = -\\frac{4x}{9y}$.\n\nAt the point: $y' = -\\frac{4 \\cdot 3/\\sqrt{2}}{9\\sqrt{2}} = -\\frac{2}{3}$.",
            "**עליון של דקארט:** $x^3 + y^3 = 6xy$ → $y' = \\frac{2y - x^2}{y^2 - 2x}$.\n\n**אליפסה** $\\frac{x^2}{9} + \\frac{y^2}{4} = 1$ ב-$\\left(\\frac{3}{\\sqrt{2}}, \\sqrt{2}\\right)$:\n\n$y' = -\\frac{4x}{9y} = -\\frac{2}{3}$."),
        sec("summary", "Related rates", "קצבי שינוי קשורים",
            "When variables depend on time $t$, differentiate with respect to $t$:\n\n**Ladder problem:** 10 m ladder, foot slides away at 2 m/s. How fast does the top slide down when foot is 6 m from wall?\n\n$x^2 + y^2 = 100$. Differentiate w.r.t. $t$:\n\n$$2x\\dot{x} + 2y\\dot{y} = 0 \\Rightarrow \\dot{y} = -\\frac{x}{y}\\dot{x}.$$\n\nAt $x = 6$: $y = 8$, $\\dot{x} = 2$ → $\\dot{y} = -\\frac{6}{8}(2) = -1.5$ m/s (top slides **down** at 1.5 m/s).",
            "כשמשתנים תלויים בזמן $t$, גזרו ב-$t$:\n\n**בעיית הסולם:** סולם 10 מ', בסיס זז 2 מ'/ש'. כמה מהר הראש יורד כשהבסיס 6 מ' מהקיר?\n\n$x^2 + y^2 = 100$ → $2x\\dot{x} + 2y\\dot{y} = 0$.\n\nב-$x = 6$, $y = 8$, $\\dot{x} = 2$ → $\\dot{y} = -1.5$ מ'/ש'."),
    ],
    [
        mcq(1, "easy", "If $x^2 + y^2 = 16$, what is $\\frac{dy}{dx}$?", "אם $x^2 + y^2 = 16$, מה $\\frac{dy}{dx}$?",
            ["$-\\frac{x}{y}$", "$\\frac{x}{y}$", "$-\\frac{y}{x}$", "$2x + 2y$"],
            ["$-\\frac{x}{y}$", "$\\frac{x}{y}$", "$-\\frac{y}{x}$", "$2x + 2y$"], 0,
            "$2x + 2yy' = 0$ → $y' = -x/y$.", "$2x + 2yy' = 0$ → $y' = -x/y$."),
        mcq(2, "medium", "Slope of tangent to $x^2 + y^2 = 25$ at $(3, 4)$:", "שיפוע משיק ל-$x^2 + y^2 = 25$ ב-$(3, 4)$:",
            ["$\\frac{3}{4}$", "$-\\frac{3}{4}$", "$-\\frac{4}{3}$", "$\\frac{4}{3}$"],
            ["$\\frac{3}{4}$", "$-\\frac{3}{4}$", "$-\\frac{4}{3}$", "$\\frac{4}{3}$"], 1,
            "$y' = -x/y = -3/4$.", "$y' = -3/4$."),
        mcq(3, "hard", "For $x^3 + y^3 = 3xy$, find $y'$:", "ל-$x^3 + y^3 = 3xy$, מצאו $y'$:",
            ["$\\frac{y - x^2}{y^2 - x}$", "$\\frac{y - x^2}{y^2 - 2x}$", "$\\frac{x^2 - y}{y^2 - x}$", "$\\frac{2y - x^2}{y^2 - 2x}$"],
            ["$\\frac{y - x^2}{y^2 - x}$", "$\\frac{y - x^2}{y^2 - 2x}$", "$\\frac{x^2 - y}{y^2 - x}$", "$\\frac{2y - x^2}{y^2 - 2x}$"], 3,
            "Collect $y'$ terms: $y'(3y^2 - 6x) = 6y - 3x^2$.", "איסוף $y'$: $y'(3y^2 - 6x) = 6y - 3x^2$."),
        mcq(4, "hard", "Tangent to $x^2 + y^2 = 25$ at $(3,4)$ has equation:", "משיק ל-$x^2 + y^2 = 25$ ב-$(3,4)$:",
            ["$y = -\\frac{3}{4}x + \\frac{25}{4}$", "$3x + 4y = 25$", "$y = \\frac{3}{4}x + \\frac{7}{4}$", "$4x + 3y = 25$"],
            ["$y = -\\frac{3}{4}x + \\frac{25}{4}$", "$3x + 4y = 25$", "$y = \\frac{3}{4}x + \\frac{7}{4}$", "$4x + 3y = 25$"], 0,
            "$y - 4 = -\\frac{3}{4}(x-3)$ → $y = -\\frac{3}{4}x + \\frac{25}{4}$.", "$y - 4 = -\\frac{3}{4}(x-3)$."),
        mcq(5, "hard", "Ladder 10 m, foot moves 2 m/s, foot 6 m from wall. Top speed?", "סולם 10 מ', בסיס 2 מ'/ש', 6 מ' מהקיר. מהירות הראש?",
            ["$1.5$ m/s downward", "$2$ m/s downward", "$1.5$ m/s upward", "$0.75$ m/s downward"],
            ["$1.5$ מ'/ש' למטה", "$2$ מ'/ש' למטה", "$1.5$ מ'/ש' למעלה", "$0.75$ מ'/ש' למטה"], 0,
            "$\\dot{y} = -(x/y)\\dot{x} = -(6/8)(2) = -1.5$ m/s.", "$\\dot{y} = -1.5$ מ'/ש'."),
    ],
    "Students forget the y' factor when differentiating g(y). Always collect y' terms on one side. For tangents, verify perpendicularity to radius on circles. Related rates: draw diagram, label rates, differentiate w.r.t. t, then substitute. Prerequisite: lesson:derivatives_intro chain rule.",
)

DERIVATIVES_TRIG_EXP = lesson(
    "derivatives_trig_exp",
    "high_school_math_5pt",
    "5pt",
    "Derivatives of Trigonometric & Exponential Functions",
    "נגזרות של פונקציות טריגונומטריות ומעריכיות",
    "Sin, cos, exp, log derivatives with chain/product/quotient rules and full function investigation — classic 5pt Bagrut.",
    "נגזרות sin, cos, exp, log עם כללי שרשרת/מכפלה/מנה וחקירת פונקציה מלאה — בגרות 5 יח' קלאסית.",
    30,
    [
        sec("intro", "Derivative of $\\sin x$ and $\\cos x$", "נגזרת $\\sin x$ ו-$\\cos x$",
            "$$(\\sin x)' = \\cos x, \\quad (\\cos x)' = -\\sin x.$$\n\n**Proof sketch:** $\\lim_{h\\to 0}\\frac{\\sin(x+h)-\\sin x}{h}$ uses angle addition and the key limit $\\lim_{h\\to 0}\\frac{\\sin h}{h} = 1$.\n\n**Extended table (5pt):**\n- $(\\tan x)' = \\sec^2 x = \\frac{1}{\\cos^2 x}$\n- $(\\cot x)' = -\\csc^2 x$",
            "$$(\\sin x)' = \\cos x, \\quad (\\cos x)' = -\\sin x.$$\n\n**סקיצת הוכחה:** משתמשת ב-$\\lim_{h\\to 0}\\frac{\\sin h}{h} = 1$.\n\n**טבלה מורחבת:**\n- $(\\tan x)' = \\sec^2 x$\n- $(\\cot x)' = -\\csc^2 x$"),
        sec("theory", "Derivative of $e^x$ and $\\ln x$", "נגזרת $e^x$ ו-$\\ln x$",
            "$$(e^x)' = e^x \\quad \\text{(unique!)}$$\n$$(a^x)' = a^x \\ln a, \\quad (\\ln x)' = \\frac{1}{x}, \\quad (\\log_a x)' = \\frac{1}{x \\ln a}.$$\n\nThese are essential for investigating exponential and logarithmic functions at 5pt.",
            "$$(e^x)' = e^x$$\n$$(a^x)' = a^x \\ln a, \\quad (\\ln x)' = \\frac{1}{x}.$$\n\nחיוניות לחקירת פונקציות מעריכיות ולוגריתמיות ב-5 יח'."),
        sec("worked_example", "Chain rule with trig/exp", "כלל שרשרת עם trig/exp",
            "$(\\sin(3x^2+1))' = \\cos(3x^2+1) \\cdot 6x$.\n\n$(e^{x^2})' = 2x e^{x^2}$.\n\n$(e^{\\sin x})' = e^{\\sin x} \\cos x$.\n\n$(\\ln(x^2+1))' = \\frac{2x}{x^2+1}$.\n\n**Pattern:** outer derivative × inner derivative.",
            "$(\\sin(3x^2+1))' = \\cos(3x^2+1) \\cdot 6x$.\n\n$(e^{x^2})' = 2x e^{x^2}$.\n\n$(\\ln(x^2+1))' = \\frac{2x}{x^2+1}$.\n\n**דפוס:** נגזרת חיצונית × נגזרת פנימית."),
        sec("worked_example", "Products and quotients", "מכפלות ומנות",
            "$f(x) = x\\sin x$: $f' = \\sin x + x\\cos x$ (product rule).\n\n$f(x) = \\frac{e^x}{x^2+1}$: quotient rule → $\\frac{e^x(x^2+1) - e^x \\cdot 2x}{(x^2+1)^2}$.\n\n$f(x) = e^{-x}\\cos x$: $f' = -e^{-x}\\cos x - e^{-x}\\sin x = -e^{-x}(\\cos x + \\sin x)$.",
            "$f(x) = x\\sin x$: $f' = \\sin x + x\\cos x$.\n\n$f(x) = e^{-x}\\cos x$: $f' = -e^{-x}(\\cos x + \\sin x)$."),
        sec("summary", "Function investigation: $e^{-x}\\sin x$", "חקירה: $e^{-x}\\sin x$",
            "On $[0, 2\\pi]$: zeros at $x = 0, \\pi, 2\\pi$.\n\n$f' = e^{-x}(\\cos x - \\sin x) = 0$ → $\\tan x = 1$ → $x = \\frac{\\pi}{4}, \\frac{5\\pi}{4}$.\n\nAt $\\pi/4$: max; at $5\\pi/4$: min. Classic 5pt **חקור ושרטט** question combining trig and exponential decay.",
            "ב-$[0, 2\\pi]$: אפסים ב-$0, \\pi, 2\\pi$.\n\n$f' = 0$ ב-$\\pi/4$ (מקס) ו-$5\\pi/4$ (מין). שאלת **חקור ושרטט** קלאסית ב-5 יח'."),
    ],
    [
        mcq(1, "easy", "Find $(\\sin(2x))'$.", "מצאו $(\\sin(2x))'$.",
            ["$\\cos(2x)$", "$2\\cos(2x)$", "$\\sin(2x)$", "$2\\sin(2x)$"],
            ["$\\cos(2x)$", "$2\\cos(2x)$", "$\\sin(2x)$", "$2\\sin(2x)$"], 1,
            "Chain: $\\cos(2x) \\cdot 2$.", "שרשרת: $\\cos(2x) \\cdot 2$."),
        mcq(2, "easy", "Find $(e^{3x})'$.", "מצאו $(e^{3x})'$.",
            ["$e^{3x}$", "$3e^{3x}$", "$3xe^{3x}$", "$e^{3}$"],
            ["$e^{3x}$", "$3e^{3x}$", "$3xe^{3x}$", "$e^{3}$"], 1,
            "$(e^{u})' = u' e^u$ with $u = 3x$.", "$(e^{u})' = u' e^u$."),
        mcq(3, "medium", "Find $(\\ln(x^2))'$.", "מצאו $(\\ln(x^2))'$.",
            ["$\\frac{1}{x^2}$", "$\\frac{2}{x}$", "$\\frac{2x}{x^2}$", "$\\ln 2$"],
            ["$\\frac{1}{x^2}$", "$\\frac{2}{x}$", "$\\frac{2x}{x^2}$", "$\\ln 2$"], 1,
            "$\\frac{1}{x^2} \\cdot 2x = 2/x$ (or $\\ln(x^2) = 2\\ln x$ → $2/x$).", "$2/x$."),
        mcq(4, "medium", "Find $(e^{x^2} \\sin x)'$.", "מצאו $(e^{x^2} \\sin x)'$.",
            ["$e^{x^2}(\\cos x + 2x\\sin x)$", "$e^{x^2}(2x\\sin x + \\cos x)$", "$2xe^{x^2}\\sin x$", "$e^{x^2}\\cos x$"],
            ["$e^{x^2}(\\cos x + 2x\\sin x)$", "$e^{x^2}(2x\\sin x + \\cos x)$", "$2xe^{x^2}\\sin x$", "$e^{x^2}\\cos x$"], 1,
            "Product: $2x e^{x^2}\\sin x + e^{x^2}\\cos x$.", "מכפלה + שרשרת."),
        mcq(5, "hard", "On $(0, 2\\pi)$, $f(x) = e^{-x}\\sin x$ has a local max at:", "ב-$(0, 2\\pi)$, ל-$f(x) = e^{-x}\\sin x$ מקס מקומי ב:",
            ["$x = \\pi/4$", "$x = \\pi/2$", "$x = \\pi$", "$x = 3\\pi/4$"],
            ["$x = \\pi/4$", "$x = \\pi/2$", "$x = \\pi$", "$x = 3\\pi/4$"], 0,
            "$f' = e^{-x}(\\cos x - \\sin x) = 0$ → $x = \\pi/4$; sign change + to −.", "$f' = 0$ ב-$\\pi/4$; שינוי סימן."),
    ],
    "Memorize (sin,cos,exp,ln)' and always apply chain rule on compositions. e^{-x}sin x is THE 5pt investigation template. Watch for product vs chain confusion on e^x · sin x.",
)

INTEGRATION_SUBSTITUTION = lesson(
    "integration_substitution",
    "high_school_math_5pt",
    "5pt",
    "Integration by Substitution (u-substitution)",
    "אינטגרציה בהצבה",
    "Reverse chain rule: recognize f(g(x))g'(x), change variables, and apply to definite integrals and area problems.",
    "הפיכת כלל השרשרת: זיהוי $f(g(x))g'(x)$, החלפת משתנה, ויישום לאינטגרל מסוים ושטחים.",
    25,
    [
        sec("intro", "The substitution idea", "רעיון ההצבה",
            "Substitution reverses the chain rule. If the integrand has the form $f(g(x)) \\cdot g'(x)$, let $u = g(x)$, $du = g'(x)\\,dx$:\n\n$$\\int f(g(x)) g'(x)\\,dx = \\int f(u)\\,du.$$\n\n**When it works:** you see an \"inner function\" and (up to a constant) its derivative as a factor.",
            "הצבה הופכת את כלל השרשרת. אם יש $f(g(x)) \\cdot g'(x)$, נקבע $u = g(x)$:\n\n$$\\int f(g(x)) g'(x)\\,dx = \\int f(u)\\,du.$$\n\n**מתי זה עובד:** רואים \"פונקציה פנימית\" ואת הנגזרת שלה כגורם."),
        sec("worked_example", "Indefinite integral substitution", "אינטגרל לא מסוים בהצבה",
            "$\\int 2x(x^2+1)^3\\,dx$: $u = x^2+1$, $du = 2x\\,dx$ → $\\int u^3\\,du = \\frac{u^4}{4}+C = \\frac{(x^2+1)^4}{4}+C$.\n\n$\\int \\frac{x}{x^2+3}\\,dx$: $u = x^2+3$ → $\\frac{1}{2}\\ln|x^2+3|+C$.",
            "$\\int 2x(x^2+1)^3\\,dx = \\frac{(x^2+1)^4}{4}+C$.\n\n$\\int \\frac{x}{x^2+3}\\,dx = \\frac{1}{2}\\ln(x^2+3)+C$."),
        sec("worked_example", "Substitution with trig/exp", "הצבה עם trig/exp",
            "$\\int e^{3x}\\,dx = \\frac{1}{3}e^{3x}+C$.\n\n$\\int \\cos(2x+1)\\,dx = \\frac{1}{2}\\sin(2x+1)+C$.\n\n$\\int \\sin x \\cos x\\,dx$: $u = \\sin x$ → $\\frac{\\sin^2 x}{2}+C$.\n\n$\\int \\frac{\\ln x}{x}\\,dx$: $u = \\ln x$ → $\\frac{(\\ln x)^2}{2}+C$.\n\n$\\int x e^{x^2}\\,dx = \\frac{1}{2}e^{x^2}+C$.",
            "דוגמאות trig/exp/log — כולן עם $u = $\"פנימי\"."),
        sec("theory", "Definite integral substitution", "אינטגרל מסוים בהצבה",
            "**Method 1:** Change limits when substituting.\n\n$\\int_0^1 2x\\sqrt{x^2+1}\\,dx$: $u = x^2+1$, limits $u: 1 \\to 2$ → $\\int_1^2 \\sqrt{u}\\,du = \\frac{2}{3}(2^{3/2}-1)$.\n\n**Method 2:** Find indefinite antiderivative, then evaluate at original limits.\n\nBoth are valid — pick whichever is cleaner.",
            "**שיטה 1:** החלפת גבולות.\n\n**שיטה 2:** פונקציה קדומה + הצבה בגבולות המקוריים.\n\nשתיהן תקפות."),
        sec("summary", "Area calculations with substitution", "חישובי שטח עם הצבה",
            "$\\int_0^1 x\\sqrt{1-x^2}\\,dx$: $u = 1-x^2$, $du = -2x\\,dx$ → equals $\\frac{1}{3}$ (semicircle quarter area check: $\\pi/4$ for unit disk quarter... verify numerically).\n\n**Between curves:** area between $y = e^{-x}$ and $y = e^{-2x}$ on $[0,1]$:\n\n$$\\int_0^1 (e^{-x} - e^{-2x})\\,dx = [-e^{-x} + \\frac{1}{2}e^{-2x}]_0^1 = (1 - \\frac{1}{2}) - (-1 + \\frac{1}{2}) = 1 - e^{-1} + \\frac{1}{2}e^{-2}.$$\n\n(Or substitute $u = e^{-x}$ for the second term.)",
            "שטח בין $e^{-x}$ ו-$e^{-2x}$ ב-$[0,1]$ — דורש הצבה או אינטגרציה ישירה של ההפרש."),
    ],
    [
        mcq(1, "easy", "Best substitution for $\\int x(x^2+5)^4\\,dx$:", "ההצבה הטובה ל-$\\int x(x^2+5)^4\\,dx$:",
            ["$u = x$", "$u = x^2+5$", "$u = x^4$", "$u = 5x$"],
            ["$u = x$", "$u = x^2+5$", "$u = x^4$", "$u = 5x$"], 1,
            "Inner function $x^2+5$, derivative $2x$ present (adjust constant).", "פנימי $x^2+5$."),
        mcq(2, "medium", "$\\int 2x(x^2+1)^3\\,dx = ?$", "$\\int 2x(x^2+1)^3\\,dx = ?$",
            ["$\\frac{(x^2+1)^4}{4}+C$", "$\\frac{(x^2+1)^3}{3}+C$", "$(x^2+1)^4+C$", "$4(x^2+1)^3+C$"],
            ["$\\frac{(x^2+1)^4}{4}+C$", "$\\frac{(x^2+1)^3}{3}+C$", "$(x^2+1)^4+C$", "$4(x^2+1)^3+C$"], 0,
            "$u = x^2+1$ → $\\frac{u^4}{4}$.", "$u = x^2+1$ → $\\frac{u^4}{4}$."),
        mcq(3, "medium", "$\\int \\cos(3x)\\,dx = ?$", "$\\int \\cos(3x)\\,dx = ?$",
            ["$\\sin(3x)+C$", "$\\frac{1}{3}\\sin(3x)+C$", "$3\\sin(3x)+C$", "$-\\frac{1}{3}\\sin(3x)+C$"],
            ["$\\sin(3x)+C$", "$\\frac{1}{3}\\sin(3x)+C$", "$3\\sin(3x)+C$", "$-\\frac{1}{3}\\sin(3x)+C$"], 1,
            "$u = 3x$, $du = 3\\,dx$ → $\\frac{1}{3}\\sin u$.", "$u = 3x$."),
        mcq(4, "hard", "$\\int_0^1 2x\\sqrt{x^2+1}\\,dx = ?$", "$\\int_0^1 2x\\sqrt{x^2+1}\\,dx = ?$",
            ["$\\frac{2}{3}(2\\sqrt{2}-1)$", "$\\frac{2}{3}(\\sqrt{2}-1)$", "$2\\sqrt{2}-1$", "$\\frac{4}{3}$"],
            ["$\\frac{2}{3}(2\\sqrt{2}-1)$", "$\\frac{2}{3}(\\sqrt{2}-1)$", "$2\\sqrt{2}-1$", "$\\frac{4}{3}$"], 0,
            "$u: 1\\to 2$, $\\int \\sqrt{u}\\,du = \\frac{2}{3}(2^{3/2}-1)$.", "גבולות $u: 1\\to 2$."),
        mcq(5, "hard", "$\\int_0^1 x\\sqrt{1-x^2}\\,dx$ equals:", "$\\int_0^1 x\\sqrt{1-x^2}\\,dx$ שווה:",
            ["$\\frac{1}{3}$", "$\\frac{\\pi}{4}$", "$\\frac{1}{2}$", "$\\frac{\\pi}{8}$"],
            ["$\\frac{1}{3}$", "$\\frac{\\pi}{4}$", "$\\frac{1}{2}$", "$\\frac{\\pi}{8}$"], 0,
            "$u = 1-x^2$, limits $1\\to 0$: $\\frac{1}{2}\\int_0^1 \\sqrt{u}\\,du = \\frac{1}{3}$.", "$u = 1-x^2$ → $\\frac{1}{3}$."),
    ],
    "Look for inner function + its derivative. Missing constant? Divide/multiply to match du. For definite integrals, changing limits avoids back-substitution errors.",
)

COMBINATORICS_5PT = lesson(
    "combinatorics_5pt",
    "high_school_math_5pt",
    "5pt",
    "Combinatorics — Permutations, Combinations & Binomial Theorem",
    "קומבינטוריקה — תמורות, צירופים ומשפט הבינום",
    "Counting principle, permutations, combinations, binomial theorem, and probability — essential 5pt Bagrut combinatorics.",
    "עקרון הספירה, תמורות, צירופים, משפט הבינום והסתברות — קומבינטוריקה חיונית ב-5 יח'.",
    30,
    [
        sec("intro", "Fundamental counting principle", "עקרון הספירה הבסיסי",
            "If task 1 has $m$ outcomes and task 2 has $n$ outcomes, total **ordered** outcomes = $mn$.\n\n**License plate:** 3 letters × 3 digits = $26^3 \\times 10^3$ (with repetition).\n\n**Key distinctions:** ordered vs unordered; with vs without repetition.",
            "משימה 1 עם $m$ תוצאות ומשימה 2 עם $n$ → סה\"כ $mn$.\n\n**לוחית רישוי:** $26^3 \\times 10^3$.\n\n**הבחנה:** סדר vs ללא סדר; עם vs בלי חזרות."),
        sec("theory", "Permutations", "תמורות",
            "**Ordered arrangements:** $P(n,k) = \\frac{n!}{(n-k)!}$.\n\nAll $n$ objects: $n!$.\n\n**Identical objects:** $\\frac{n!}{n_1! n_2! \\cdots n_k!}$.\n\n**MATHEMATICS:** $\\frac{11!}{2!2!2!1!1!1!1!1!1!} = 4989600$ arrangements.",
            "**סידורים עם סדר:** $P(n,k) = \\frac{n!}{(n-k)!}$.\n\n**עצמים זהים:** $\\frac{n!}{n_1! n_2! \\cdots}$.\n\n**MATHEMATICS:** $\\frac{11!}{2!2!2!}$."),
        sec("theory", "Combinations", "צירופים",
            "**Unordered selections:** $\\binom{n}{k} = \\frac{n!}{k!(n-k)!}$.\n\nSymmetry: $\\binom{n}{k} = \\binom{n}{n-k}$.\n\n$\\binom{n}{0} = \\binom{n}{n} = 1$.\n\n**Bagrut:** Choose committee of 4 from 10 with **at least 2 women** (6W, 4M): count cases $2W2M + 3W1M + 4W0M$.",
            "**בחירות ללא סדר:** $\\binom{n}{k}$.\n\n**בגרות:** וועדה של 4 מ-10 עם **לפחות 2 בנות**."),
        sec("worked_example", "Binomial theorem", "משפט הבינום",
            "$$(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k} b^k.$$\n\nCoefficient of $x^3$ in $(2x-1)^5$: term $k=3$: $\\binom{5}{3}(2x)^3(-1)^2 = 10 \\cdot 8 x^3 = 80x^3$ → coefficient **80**.\n\n$\\sum_{k=0}^{n}\\binom{n}{k} = 2^n$ (set $a=b=1$).",
            "$$(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k} b^k.$$\n\nמקדם $x^3$ ב-$(2x-1)^5$: **80**.\n\n$\\sum \\binom{n}{k} = 2^n$."),
        sec("summary", "Probability with combinatorics", "הסתברות עם קומבינטוריקה",
            "$P = \\frac{\\text{favorable}}{\\text{total}}$ using combinations.\n\n**Cards:** 3 hearts from 52: $\\frac{\\binom{13}{3}}{\\binom{52}{3}}$.\n\n**Committee:** 12 boys + 8 girls, choose 4. P(exactly 2 girls) = $\\frac{\\binom{8}{2}\\binom{12}{2}}{\\binom{20}{4}}$.",
            "**קלפים:** $\\frac{\\binom{13}{3}}{\\binom{52}{3}}$.\n\n**ועדה:** P(בדיוק 2 בנות) = $\\frac{\\binom{8}{2}\\binom{12}{2}}{\\binom{20}{4}}$."),
    ],
    [
        mcq(1, "easy", "A meal: 3 appetizers × 4 mains × 2 desserts. How many combos?", "ארוחה: 3 מנות × 4 עיקריות × 2 קינוחים. כמה אפשרויות?",
            ["$9$", "$12$", "$24$", "$36$"], ["$9$", "$12$", "$24$", "$36$"], 2,
            "$3 \\times 4 \\times 2 = 24$.", "$3 \\times 4 \\times 2 = 24$."),
        mcq(2, "medium", "Arrange 5 books on a shelf. How many orderings?", "5 ספרים על מדף. כמה סידורים?",
            ["$5$", "$25$", "$120$", "$720$"], ["$5$", "$25$", "$120$", "$720$"], 2,
            "$5! = 120$.", "$5! = 120$."),
        mcq(3, "medium", "Choose 3 from 10 (unordered). How many ways?", "בחרו 3 מ-10 (ללא סדר). כמה דרכים?",
            ["$30$", "$720$", "$120$", "$1000$"], ["$30$", "$720$", "$120$", "$1000$"], 2,
            "$\\binom{10}{3} = 120$.", "$\\binom{10}{3} = 120$."),
        mcq(4, "hard", "Coefficient of $x^2$ in $(1+x)^6$:", "מקדם $x^2$ ב-$(1+x)^6$:",
            ["$6$", "$15$", "$20$", "$30$"], ["$6$", "$15$", "$20$", "$30$"], 1,
            "$\\binom{6}{2} = 15$.", "$\\binom{6}{2} = 15$."),
        mcq(5, "hard", "Class: 8 girls, 12 boys. Committee of 4, P(exactly 2 girls)?", "כיתה: 8 בנות, 12 בנים. וועדה 4, P(בדיוק 2 בנות)?",
            ["$\\frac{\\binom{8}{2}\\binom{12}{2}}{\\binom{20}{4}}$", "$\\frac{\\binom{8}{2}}{\\binom{20}{2}}$", "$\\frac{8 \\cdot 12}{20 \\cdot 19}$", "$\\frac{\\binom{16}{2}}{\\binom{20}{4}}$"],
            ["$\\frac{\\binom{8}{2}\\binom{12}{2}}{\\binom{20}{4}}$", "$\\frac{\\binom{8}{2}}{\\binom{20}{2}}$", "$\\frac{8 \\cdot 12}{20 \\cdot 19}$", "$\\frac{\\binom{16}{2}}{\\binom{20}{4}}$"], 0,
            "Choose 2 girls AND 2 boys, divide by total committees.", "2 בנות ו-2 בנים חלקי סה\"כ."),
    ],
    "Permutation = order matters; combination = order doesn't. Binomial coefficient for (a+b)^n terms. Probability with combinations: count favorable/total equally likely outcomes. 'At least' problems → complement or casework.",
)

ALL_LESSONS = [
    LIMITS_4PT,
    FUNCTION_ANALYSIS_4PT,
    INTEGRALS_4PT,
    IMPLICIT_DIFFERENTIATION,
    DERIVATIVES_TRIG_EXP,
    INTEGRATION_SUBSTITUTION,
    COMBINATORICS_5PT,
]

INDEX_UPDATES = {
    "limits_4pt": {
        "title_en": "Limits — Intuitive Approach",
        "title_he": "גבולות — גישה אינטואיטיבית",
        "est_minutes": 25,
        "duration_min": 25,
        "subject": "high_school_math_4pt",
        "type": "interactive",
        "level_min": "4pt",
        "math_track": ["4pt"],
    },
    "function_analysis_4pt": {
        "title_en": "Function Analysis at 4pt Level",
        "title_he": "חקירת פונקציה — רמת 4 יחידות",
        "est_minutes": 30,
        "duration_min": 30,
        "subject": "high_school_math_4pt",
        "type": "interactive",
        "level_min": "4pt",
        "math_track": ["4pt"],
    },
    "integrals_4pt": {
        "title_en": "Integration at 4pt Level",
        "title_he": "אינטגרציה — רמת 4 יחידות",
        "est_minutes": 30,
        "duration_min": 30,
        "subject": "high_school_math_4pt",
        "type": "interactive",
        "level_min": "4pt",
        "math_track": ["4pt"],
    },
    "implicit_differentiation": {
        "title_en": "Implicit Differentiation",
        "title_he": "גזירה סתומה",
        "est_minutes": 25,
        "duration_min": 25,
        "subject": "high_school_math_5pt",
        "type": "interactive",
        "level_min": "5pt",
        "math_track": ["5pt"],
    },
    "derivatives_trig_exp": {
        "title_en": "Derivatives of Trigonometric & Exponential Functions",
        "title_he": "נגזרות של פונקציות טריגונומטריות ומעריכיות",
        "est_minutes": 30,
        "duration_min": 30,
        "subject": "high_school_math_5pt",
        "type": "interactive",
        "level_min": "5pt",
        "math_track": ["5pt"],
    },
    "integration_substitution": {
        "title_en": "Integration by Substitution (u-substitution)",
        "title_he": "אינטגרציה בהצבה",
        "est_minutes": 25,
        "duration_min": 25,
        "subject": "high_school_math_5pt",
        "type": "interactive",
        "level_min": "5pt",
        "math_track": ["5pt"],
    },
    "combinatorics_5pt": {
        "title_en": "Combinatorics — Permutations, Combinations & Binomial Theorem",
        "title_he": "קומבינטוריקה — תמורות, צירופים ומשפט הבינום",
        "est_minutes": 30,
        "duration_min": 30,
        "subject": "high_school_math_5pt",
        "type": "interactive",
        "level_min": "5pt",
        "math_track": ["5pt"],
    },
}


def update_index():
    with open(INDEX_PATH, "r", encoding="utf-8") as f:
        index = json.load(f)
    for entry in index:
        if entry["id"] in INDEX_UPDATES:
            entry.update(INDEX_UPDATES[entry["id"]])
            print("updated index:", entry["id"])
    with open(INDEX_PATH, "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("index saved")


if __name__ == "__main__":
    for les in ALL_LESSONS:
        path = os.path.join(LESSONS_DIR, les["concept_id"] + ".json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(les, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print("wrote", path)
    update_index()
