#!/usr/bin/env python3
"""Author 9 Calc 1 university lessons — full bilingual content."""
import json
import os

BASE = os.path.join(os.path.dirname(__file__), "seed_data", "lessons")
INDEX_PATH = os.path.join(
    os.path.dirname(__file__), "..", "apps", "web", "src", "lib", "lessons-index.generated.json"
)


def mcq(ord_, diff, stem_en, stem_he, opts_en, opts_he, correct, expl_en, expl_he, atoms):
    return {
        "ord": ord_,
        "kind": "mcq",
        "difficulty": diff,
        "stem_en": stem_en,
        "stem_he": stem_he,
        "options_en": opts_en,
        "options_he": opts_he,
        "correct_index": correct,
        "explanation_en": expl_en,
        "explanation_he": expl_he,
        "skill_atoms": atoms,
        "points_level_min": "calc1",
    }


def sec(kind, title_en, title_he, body_en, body_he):
    return {
        "kind": kind,
        "title_en": title_en,
        "title_he": title_he,
        "body_en_md": body_en,
        "body_he_md": body_he,
    }


def lesson(concept_id, title_en, title_he, summary_en, summary_he, minutes, sections, questions, hints):
    return {
        "concept_id": concept_id,
        "subject": "calculus_1",
        "level": "university",
        "math_track": ["calc1"],
        "title_en": title_en,
        "title_he": title_he,
        "summary_en": summary_en,
        "summary_he": summary_he,
        "est_minutes": minutes,
        "sections": sections,
        "questions": questions,
        "agent_hints": hints,
    }


LESSONS = [
    lesson(
        "number_sets_review",
        "Number Sets & Real Line",
        "קבוצות מספרים וציר המספרים הממשי",
        "The real number line, absolute value, intervals, and completeness — foundations for limits, continuity, and integration in Calc 1.",
        "ציר המספרים הממשי, ערך מוחלט, קטעים ושלמות — יסודות לגבולות, רציפות ואינטגרציה בחשבון 1.",
        20,
        [
            sec(
                "theory",
                "The real number system",
                "מערכת המספרים הממשיים",
                "The standard inclusion chain is:\n$$\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q} \\subset \\mathbb{R}.$$\n\n- **$\\mathbb{N}$** — natural numbers $\\{1,2,3,\\ldots\\}$ (counting).\n- **$\\mathbb{Z}$** — integers $\\{\\ldots,-2,-1,0,1,2,\\ldots\\}$.\n- **$\\mathbb{Q}$** — rationals $\\dfrac{p}{q}$ with $p,q\\in\\mathbb{Z}$, $q\\ne 0$.\n- **$\\mathbb{R}$** — reals; includes irrationals such as $\\sqrt{2}$, $\\pi$, $e$.\n\n**Density of rationals:** between any two distinct reals there is a rational. Yet $\\mathbb{Q}$ is *not* all of $\\mathbb{R}$ — the real line is a **continuum**.\n\n**Examples:** $\\dfrac{7}{3}\\in\\mathbb{Q}$; $\\sqrt{2}\\notin\\mathbb{Q}$; $0.333\\ldots = \\dfrac{1}{3}\\in\\mathbb{Q}$.",
                "שרשרת ההכללה הסטандартית:\n$$\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q} \\subset \\mathbb{R}.$$\n\n- **$\\mathbb{N}$** — מספרים טבעיים.\n- **$\\mathbb{Z}$** — שלמים.\n- **$\\mathbb{Q}$** — רציונליים $\\dfrac{p}{q}$, $q\\ne 0$.\n- **$\\mathbb{R}$** — ממשיים; כולל אי-רציונליים כמו $\\sqrt{2}$, $\\pi$, $e$.\n\n**צפיפות הרציונליים:** בין כל שני ממשיים שונים יש רציונלי. עם זאת $\\mathbb{Q}$ אינו כל $\\mathbb{R}$ — קו המספרים הוא **רצף**.\n\n**דוגמאות:** $\\dfrac{7}{3}\\in\\mathbb{Q}$; $\\sqrt{2}\\notin\\mathbb{Q}$.",
            ),
            sec(
                "theory",
                "Absolute value",
                "ערך מוחלט",
                "For $x\\in\\mathbb{R}$:\n$$|x| = \\max(x,-x) = \\begin{cases} x & x\\ge 0 \\\\ -x & x<0 \\end{cases}$$\n\n**Geometric meaning:** $|x-a|$ is the distance from $x$ to $a$ on the number line.\n\n**Neighborhood language:** $|x-a|<\\delta$ means $x\\in(a-\\delta,a+\\delta)$ — an open interval of radius $\\delta$ around $a$.\n\n**Triangle inequality:** for all $a,b\\in\\mathbb{R}$,\n$$|a+b|\\le |a|+|b|.$$\n\n**Worked examples:**\n- $| -5 | = 5$\n- Solve $|2x-3|<5$: $-5<2x-3<5 \\Rightarrow -2<2x<8 \\Rightarrow -1<x<4$\n- $|x-2|\\le 3 \\Rightarrow x\\in[-1,5]$",
                "ל-$x\\in\\mathbb{R}$:\n$$|x| = \\max(x,-x).$$\n\n**משמעות גאומטרית:** $|x-a|$ הוא המרחק מ-$x$ ל-$a$ על ציר המספרים.\n\n**שפת סביבות:** $|x-a|<\\delta$ פירושו $x\\in(a-\\delta,a+\\delta)$.\n\n**אי-שוויון המשולש:** $|a+b|\\le |a|+|b|$.\n\n**דוגמאות:**\n- $| -5 | = 5$\n- $|2x-3|<5 \\Rightarrow -1<x<4$\n- $|x-2|\\le 3 \\Rightarrow x\\in[-1,5]$",
            ),
            sec(
                "theory",
                "Intervals and neighborhoods",
                "קטעים וסביבות",
                "**Open interval:** $(a,b)=\\{x: a<x<b\\}$.\n**Closed interval:** $[a,b]=\\{x: a\\le x\\le b\\}$.\n**Half-open:** $[a,b)$ or $(a,b]$.\n\n**Deleted neighborhood** of $a$ (used in limits):\n$$0<|x-a|<\\delta \\quad\\Longleftrightarrow\\quad x\\in(a-\\delta,a+\\delta)\\setminus\\{a\\}.$$\n\n**Supremum / infimum (intuitive):** for a set $S\\subset\\mathbb{R}$ bounded above, $\\sup S$ is the *least* upper bound. For $S=(0,1)$, $\\sup S=1$ but the maximum is not attained. Similarly $\\inf S$ is the greatest lower bound.",
                "**קטע פתוח:** $(a,b)$. **סגור:** $[a,b]$. **חצי-פתוח:** $[a,b)$ או $(a,b]$.\n\n**סביבה מנוקבת** (בגבולות):\n$$0<|x-a|<\\delta \\quad\\Longleftrightarrow\\quad x\\in(a-\\delta,a+\\delta)\\setminus\\{a\\}.$$\n\n**סופרימום / אינפימום (אינטואיטיבי):** $\\sup S$ הוא חסם עליון מינימלי. ל-$S=(0,1)$, $\\sup S=1$ אך המקסימום לא מתקבל.",
            ),
            sec(
                "theory",
                "Bounds and completeness",
                "חסמים ושלמות",
                "A set $S\\subset\\mathbb{R}$ is **bounded above** if $\\exists M$ with $x\\le M$ for all $x\\in S$. **Bounded below** is analogous.\n\n**Archimedean property** (stated without proof): for every real $x>0$ there exists $n\\in\\mathbb{N}$ with $n>x$. Equivalently, $\\dfrac{1}{n}\\to 0$.\n\n**Completeness of $\\mathbb{R}$:** every bounded *increasing* sequence of reals converges to a real limit. This fails in $\\mathbb{Q}$ — e.g. a sequence of rationals approaching $\\sqrt{2}$ has no rational limit.\n\nThis property guarantees that limits you compute in Calc 1 actually land in $\\mathbb{R}$.",
                "קבוצה $S$ **חסומה מלמעלה** אם $\\exists M$ כך ש-$x\\le M$ לכל $x\\in S$.\n\n**תכונת ארכימדס** (ללא הוכחה): לכל $x>0$ קיים $n\\in\\mathbb{N}$ עם $n>x$.\n\n**שלמות $\\mathbb{R}$:** כל סדרה עולה וחסומה של ממשיים מתכנסת. ב-$\\mathbb{Q}$ זה נכשל — סדרה שמתקרבת ל-$\\sqrt{2}$ אין לה גבול רציונלי.\n\nתכונה זו מבטיחה שגבולות בחשבון 1 נחתים ב-$\\mathbb{R}$.",
            ),
            sec(
                "summary",
                "Why this matters for Calc 1",
                "למה זה חשוב לחשבון 1",
                "- **Limits** use $|x-a|<\\delta$ — absolute value and deleted neighborhoods.\n- **Continuity** is defined on intervals; endpoints need one-sided limits.\n- **Integration** on $[a,b]$ uses a closed, bounded domain — EVT and Riemann sums rely on completeness.\n- **Inequalities** like $|f(x)-L|<\\epsilon$ appear in every limit proof and error bound.\n\nMaster this language early — it is the vocabulary of every exam question at Technion, TAU, BGU, and HUJI.",
                "- **גבולות** משתמשים ב-$|x-a|<\\delta$ — ערך מוחלט וסביבות מנוקבות.\n- **רציפות** מוגדרת על קטעים; בקצוות צריך גבולות חד-צדדיים.\n- **אינטגרציה** על $[a,b]$ דורשת תחום סגור וחסום.\n- **אי-שוויונות** כמו $|f(x)-L|<\\epsilon$ מופיעים בכל הוכחת גבול.\n\nשלוטו בשפה הזו מוקדם — זה אוצר המילים של כל מבחן בטכניון, ת״א, בGU והUJI.",
            ),
        ],
        [
            mcq(1, "easy", "Which set does $\\sqrt{2}$ belong to?",
                 "לאיזו קבוצה שייך $\\sqrt{2}$?",
                 ["$\\mathbb{N}$", "$\\mathbb{Z}$", "$\\mathbb{Q}$", "$\\mathbb{R}\\setminus\\mathbb{Q}$"],
                 ["$\\mathbb{N}$", "$\\mathbb{Z}$", "$\\mathbb{Q}$", "$\\mathbb{R}\\setminus\\mathbb{Q}$"],
                 3, "$\\sqrt{2}$ is irrational — real but not rational.", "$\\sqrt{2}$ אי-רציונלי — ממשי אך לא רציונלי.", ["identify_number_set"]),
            mcq(2, "medium", "Solve $|2x-3|<5$. The solution set is:",
                 "פתרו $|2x-3|<5$. קבוצת הפתרונות:",
                 ["$(-1,4)$", "$(-4,1)$", "$[-1,4]$", "$(-\\infty,-1)\\cup(4,\\infty)$"],
                 ["$(-1,4)$", "$(-4,1)$", "$[-1,4]$", "$(-\\infty,-1)\\cup(4,\\infty)$"],
                 0, "$-5<2x-3<5 \\Rightarrow -1<x<4$.", "$-5<2x-3<5 \\Rightarrow -1<x<4$.", ["solve_absolute_value"]),
            mcq(3, "medium", "What is $\\sup(0,1)$?",
                 "מהו $\\sup(0,1)$?",
                 ["$0$", "$1$", "Does not exist", "$\\infty$"],
                 ["$0$", "$1$", "לא קיים", "$\\infty$"],
                 1, "Every number $<1$ is in $(0,1)$; $1$ is the least upper bound.", "כל מספר $<1$ ב-$(0,1)$; $1$ הוא חסם עליון מינימלי.", ["find_supremum"]),
            mcq(4, "easy", "Which notation describes $x$ with $0<|x-2|<\\delta$?",
                 "איזה סימון מתאר $x$ עם $0<|x-2|<\\delta$?",
                 ["Closed interval $[2-\\delta,2+\\delta]$", "Deleted neighborhood of $2$", "$x=2$", "Half-open interval"],
                 ["קטע סגור", "סביבה מנוקבת של $2$", "$x=2$", "קטע חצי-פתוח"],
                 1, "Strict inequality excludes $x=2$ — a punctured neighborhood.", "אי-שוויון חזק שולל $x=2$ — סביבה מנוקבת.", ["identify_interval"]),
            mcq(5, "medium", "If $|a|=3$ and $|b|=4$, what is the largest possible value of $|a+b|$?",
                 "אם $|a|=3$ ו-$|b|=4$, מה הערך המקסימלי האפשרי של $|a+b|$?",
                 ["$1$", "$7$", "$5$", "$12$"],
                 ["$1$", "$7$", "$5$", "$12$"],
                 1, "Maximum when $a,b$ have the same sign: $|3+4|=7$. Triangle inequality gives $|a+b|\\le7$.", "מקסימום כשסימנים זהים: $|3+4|=7$.", ["triangle_inequality"]),
        ],
        {
            "key_insights": [
                "$\\mathbb{Q}$ is dense in $\\mathbb{R}$ but incomplete.",
                "$|x-a|<\\delta$ is the language of limits.",
                "$\\sup$ may not be attained; $\\max$ must be an element of the set.",
            ],
            "common_misconceptions": [
                {"wrong": "Every bounded set has a maximum", "correction": "It has a supremum; e.g. $(0,1)$ has no max.", "detect_phrase_en": "maximum of open interval", "detect_phrase_he": "מקסימום של קטע פתוח"},
            ],
            "tutor_pacing_hint": "Draw the number line before introducing $\\delta$-neighborhoods.",
            "skill_atoms_unlocked": ["identify_number_set", "solve_absolute_value", "find_supremum", "identify_interval", "triangle_inequality"],
        },
    ),
    lesson(
        "function_basics_uni",
        "Functions — Domain, Range & Elementary Families",
        "פונקציות — תחום, טווח ומשפחות אלמנטריות",
        "Domain, range, injectivity, surjectivity, and the standard families (polynomial, rational, exponential, logarithmic, trigonometric) used throughout engineering Calc 1.",
        "תחום, טווח, חד-חד-ערכיות, עליות ומשפחות הפונקציות הסטנדרטיות (פולינום, רציונלית, מעריכית, לוגריתמית, טריגונומטרית) בחשבון 1 להנדסה.",
        25,
        [
            sec(
                "intro",
                "What is a function?",
                "מהי פונקציה?",
                "A **function** $f$ from set $A$ to set $B$, written $f:A\\to B$, assigns **exactly one** output $f(x)\\in B$ to each input $x\\in A$.\n\n- **Domain** $D_f=A$: allowed inputs.\n- **Codomain** $B$: target set (may contain values never hit).\n- **Range** $R_f=\\{f(x):x\\in D_f\\}\\subseteq B$: values actually attained.\n\n**Vertical line test** (graphs in $\\mathbb{R}^2$): a curve is a function of $x$ iff no vertical line meets it more than once.\n\n**Example:** $f(x)=\\sqrt{x-1}$ requires $x-1\\ge 0$, so $D_f=[1,\\infty)$ and $R_f=[0,\\infty)$.",
                "פונקציה $f$ מקבוצה $A$ ל-$B$, $f:A\\to B$, מקצה **בדיוק ערך אחד** $f(x)\\in B$ לכל קלט $x\\in A$.\n\n- **תחום** $D_f=A$: קלטים מותרים.\n- **קד-טווח** $B$: קבוצת יעד.\n- **טווח** $R_f=\\{f(x):x\\in D_f\\}$: ערכים שמתקבלים בפועל.\n\n**מבחן הקו האנכי:** גרף הוא פונקציה של $x$ אם ורק אם אין קו אנכי שחותך אותו יותר מפעם אחת.\n\n**דוגמה:** $f(x)=\\sqrt{x-1}$ דורש $x\\ge 1$, לכן $D_f=[1,\\infty)$, $R_f=[0,\\infty)$.",
            ),
            sec(
                "theory",
                "Injectivity, surjectivity, bijectivity",
                "חד-חד-ערכיות, עליות ובייקטיביות",
                "**Injective (one-to-one):** $f(x_1)=f(x_2)\\Rightarrow x_1=x_2$. Equivalently, distinct inputs give distinct outputs.\n\n**Surjective (onto $B$):** for every $y\\in B$ there exists $x\\in A$ with $f(x)=y$. Then $R_f=B$.\n\n**Bijective:** both injective and surjective — admits an inverse $f^{-1}:B\\to A$.\n\n**Horizontal line test:** $f$ is injective on an interval iff every horizontal line meets the graph at most once.\n\n**Examples:**\n- $f(x)=x^3$ is bijective $\\mathbb{R}\\to\\mathbb{R}$.\n- $f(x)=x^2$ is not injective on $\\mathbb{R}$; restricted to $[0,\\infty)$ it is injective onto $[0,\\infty)$.\n- $f(x)=e^x$ is injective, range $(0,\\infty)$, not surjective onto $\\mathbb{R}$.",
                "**חד-חד-ערכית:** $f(x_1)=f(x_2)\\Rightarrow x_1=x_2$.\n\n**על ($B$):** לכל $y\\in B$ קיים $x\\in A$ עם $f(x)=y$.\n\n**בייקטיבית:** חד-חד-ערכית ועל — קיימת פונקציה הפוכה $f^{-1}$.\n\n**מבחן הקו האופקי:** $f$ חד-חד-ערכית בקטע אם כל קו אופקי חותך את הגרף לכל היותר פעם אחת.\n\n**דוגמאות:**\n- $f(x)=x^3$ בייקטיבית $\\mathbb{R}\\to\\mathbb{R}$.\n- $f(x)=x^2$ אינה חד-חד-ערכית על $\\mathbb{R}$.\n- $f(x)=e^x$ חד-חד-ערכית, טווח $(0,\\infty)$.",
            ),
            sec(
                "worked_example",
                "Finding domain and range",
                "מציאת תחום וטווח",
                "**Example 1.** $f(x)=\\dfrac{x+1}{x-2}$\n- Domain: denominator $\\ne 0$ $\\Rightarrow$ $D_f=\\mathbb{R}\\setminus\\{2\\}$.\n- Range: solve $y=\\dfrac{x+1}{x-2}$ for $x$: $y(x-2)=x+1 \\Rightarrow x(y-1)=2y+1 \\Rightarrow x=\\dfrac{2y+1}{y-1}$. Need $y\\ne 1$, so $R_f=\\mathbb{R}\\setminus\\{1\\}$.\n\n**Example 2.** $g(x)=\\ln(3-x)$\n- Need $3-x>0 \\Rightarrow D_g=(-\\infty,3)$.\n- Since $\\ln u$ covers $(-\\infty,\\infty)$ as $u\\in(0,\\infty)$, $R_g=\\mathbb{R}$.\n\n**Example 3.** $h(x)=\\sqrt{4-x^2}$\n- Need $4-x^2\\ge 0 \\Rightarrow x\\in[-2,2]$.\n- Maximum $\\sqrt{4}=2$, minimum $0$ $\\Rightarrow$ $R_h=[0,2]$.",
                "**דוגמה 1.** $f(x)=\\dfrac{x+1}{x-2}$\n- תחום: $x\\ne 2$ $\\Rightarrow$ $D_f=\\mathbb{R}\\setminus\\{2\\}$.\n- טווח: $y\\ne 1$ $\\Rightarrow$ $R_f=\\mathbb{R}\\setminus\\{1\\}$.\n\n**דוגמה 2.** $g(x)=\\ln(3-x)$\n- $3-x>0 \\Rightarrow D_g=(-\\infty,3)$, $R_g=\\mathbb{R}$.\n\n**דוגמה 3.** $h(x)=\\sqrt{4-x^2}$\n- $x\\in[-2,2]$, $R_h=[0,2]$.",
            ),
            sec(
                "theory",
                "Elementary function families",
                "משפחות פונקציות אלמנטריות",
                "| Family | Typical form | Domain notes |\n|---|---|---|\n| Polynomial | $a_n x^n+\\cdots+a_0$ | $\\mathbb{R}$ |\n| Rational | $P(x)/Q(x)$ | exclude zeros of $Q$ |\n| Exponential | $a^x$, $e^x$ | $\\mathbb{R}$; range $(0,\\infty)$ if $a>0,a\\ne 1$ |\n| Logarithm | $\\log_a x$, $\\ln x$ | $(0,\\infty)$ |\n| Trigonometric | $\\sin x,\\cos x,\\tan x$ | $\\tan x$: exclude odd multiples of $\\pi/2$ |\n\n**Composition:** $(f\\circ g)(x)=f(g(x))$. Domain requires $x\\in D_g$ and $g(x)\\in D_f$.\n\n**Even / odd:** $f(-x)=f(x)$ (symmetric about $y$-axis); $f(-x)=-f(x)$ (origin symmetry). Useful in integration and Fourier courses later.",
                "| משפחה | צורה | הערות תחום |\n|---|---|---|\n| פולינום | $a_n x^n+\\cdots$ | $\\mathbb{R}$ |\n| רציונלית | $P/Q$ | לא ב-0 של $Q$ |\n| מעריכית | $e^x$ | $\\mathbb{R}$, טווח $(0,\\infty)$ |\n| לוגריתמית | $\\ln x$ | $(0,\\infty)$ |\n| טריגונומטרית | $\\sin,\\cos,\\tan$ | $\\tan$: לא ב-$\\pi/2$ אי-זוגי |\n\n**הרכבה:** $(f\\circ g)(x)=f(g(x))$.\n\n**זוגיות:** $f(-x)=f(x)$ זוגית; $f(-x)=-f(x)$ אי-זוגית.",
            ),
            sec(
                "summary",
                "Checklist for exam problems",
                "צ'ק-ליסט לבחינה",
                "1. Write $D_f$ first — denominators, even roots, logs.\n2. Sketch or recall graph shape for standard families.\n3. For injectivity on an interval, use monotonicity or horizontal line test.\n4. Inverse functions swap domain and range: $D_{f^{-1}}=R_f$, $R_{f^{-1}}=D_f$.\n\nThese skills appear in limits (domain near singularities), derivatives (chain rule on compositions), and integrals (substitution domains).",
                "1. כתבו $D_f$ תחילה — מכנים, שורשים, לוג.\n2. זכרו צורת גרף של משפחות סטנדרטיות.\n3. לחד-חד-ערכיות — מונוטוניות או מבחן קו אופקי.\n4. הפונקציה ההפוכה מחליפה תחום וטווח.\n\nמיומנויות אלו מופיעות בגבולות, נגזרות ואינטגרציה.",
            ),
        ],
        [
            mcq(1, "easy", "What is the domain of $f(x)=\\dfrac{1}{x-3}$?",
                 "מה תחום $f(x)=\\dfrac{1}{x-3}$?",
                 ["$\\mathbb{R}$", "$\\mathbb{R}\\setminus\\{3\\}$", "$(3,\\infty)$", "$[3,\\infty)$"],
                 ["$\\mathbb{R}$", "$\\mathbb{R}\\setminus\\{3\\}$", "$(3,\\infty)$", "$[3,\\infty)$"],
                 1, "Denominator zero at $x=3$.", "מכנה מתאפס ב-$x=3$.", ["find_function_domain"]),
            mcq(2, "medium", "Which function is injective on $\\mathbb{R}$?",
                 "איזו פונקציה חד-חד-ערכית על $\\mathbb{R}$?",
                 ["$f(x)=x^2$", "$f(x)=|x|$", "$f(x)=x^3$", "$f(x)=\\cos x$"],
                 ["$f(x)=x^2$", "$f(x)=|x|$", "$f(x)=x^3$", "$f(x)=\\cos x$"],
                 2, "$x^3$ is strictly increasing on $\\mathbb{R}$.", "$x^3$ עולה מונוטונית על $\\mathbb{R}$.", ["test_injectivity"]),
            mcq(3, "medium", "If $f(x)=e^x$, what is $R_f$?",
                 "אם $f(x)=e^x$, מה $R_f$?",
                 ["$\\mathbb{R}$", "$(0,\\infty)$", "$[0,\\infty)$", "$(-\\infty,0)$"],
                 ["$\\mathbb{R}$", "$(0,\\infty)$", "$[0,\\infty)$", "$(-\\infty,0)$"],
                 1, "$e^x>0$ for all $x$; every positive value is hit.", "$e^x>0$ תמיד; כל ערך חיובי מתקבל.", ["find_function_range"]),
            mcq(4, "easy", "Domain of $g(x)=\\ln(x-2)$?",
                 "תחום $g(x)=\\ln(x-2)$?",
                 ["$\\mathbb{R}$", "$(2,\\infty)$", "$[2,\\infty)$", "$(-\\infty,2)$"],
                 ["$\\mathbb{R}$", "$(2,\\infty)$", "$[2,\\infty)$", "$(-\\infty,2)$"],
                 1, "Need $x-2>0$.", "צריך $x-2>0$.", ["find_function_domain"]),
            mcq(5, "hard", "$f(x)=\\sqrt{x-1}$ is bijective from $[1,\\infty)$ to which set?",
                 "$f(x)=\\sqrt{x-1}$ בייקטיבית מ-$[1,\\infty)$ ל:",
                 ["$\\mathbb{R}$", "$[0,\\infty)$", "$(0,\\infty)$", "$[1,\\infty)$"],
                 ["$\\mathbb{R}$", "$[0,\\infty)$", "$(0,\\infty)$", "$[1,\\infty)$"],
                 1, "Square root is increasing on $[1,\\infty)$; range $[0,\\infty)$.", "שורש עולה על $[1,\\infty)$; טווח $[0,\\infty)$.", ["test_bijectivity"]),
        ],
        {
            "key_insights": [
                "Domain restrictions come from denominators, logs, and even roots.",
                "Injectivity on an interval often follows from strict monotonicity.",
                "Inverse functions swap domain and range.",
            ],
            "common_misconceptions": [
                {"wrong": "Domain of $1/(x-2)$ is all reals except where numerator is zero", "correction": "Exclude zeros of the denominator, not numerator.", "detect_phrase_en": "numerator zero", "detect_phrase_he": "מונה מתאפס"},
            ],
            "tutor_pacing_hint": "Start with domain of rational and log functions before injectivity proofs.",
            "skill_atoms_unlocked": ["find_function_domain", "find_function_range", "test_injectivity", "test_bijectivity"],
        },
    ),
    lesson(
        "limits_at_infinity",
        "Limits at Infinity & Asymptotes",
        "גבולות באינסוף ואסימטוטות",
        "Limits as $x\\to\\pm\\infty$, comparing growth rates, rational limits, and vertical/oblique asymptotes — essential for graph sketching and engineering approximations.",
        "גבולות כאשר $x\\to\\pm\\infty$, השוואת קצבי גדילה, גבולות של פונקציות רציונליות ואסימטוטות אנכיים/אלכסוניים — חיוני לשרטוט גרפים וקירובים בהנדסה.",
        30,
        [
            sec(
                "theory",
                "Limits at infinity",
                "גבולות באינסוף",
                "We write $\\lim_{x\\to\\infty} f(x)=L$ if outputs approach $L$ as $x$ grows without bound. Similarly $\\lim_{x\\to-\\infty} f(x)=L$.\n\n**Formal definition:** $\\lim_{x\\to\\infty}f(x)=L$ means $\\forall\\,\\epsilon>0\\,\\exists\\,N>0: x>N\\Rightarrow|f(x)-L|<\\epsilon$.\n\n**Basic limits:**\n$$\\lim_{x\\to\\infty}\\frac{1}{x}=0,\\quad \\lim_{x\\to\\infty}e^{-x}=0,\\quad \\lim_{x\\to\\infty}\\arctan x=\\frac{\\pi}{2}.$$\n\n**Infinite limits:** $\\lim_{x\\to a^+}f(x)=+\\infty$ means $f(x)$ exceeds any bound as $x\\to a$ from the right.",
                "כותבים $\\lim_{x\\to\\infty} f(x)=L$ אם הפלט מתקרב ל-$L$ כש-$x$ גדל ללא גבול.\n\n**הגדרה:** $\\forall\\,\\epsilon>0\\,\\exists\\,N: x>N\\Rightarrow|f(x)-L|<\\epsilon$.\n\n**גבולות בסיסיים:**\n$$\\lim_{x\\to\\infty}\\frac{1}{x}=0,\\quad \\lim_{x\\to\\infty}e^{-x}=0,\\quad \\lim_{x\\to\\infty}\\arctan x=\\frac{\\pi}{2}.$$\n\n**גבולות אינסופיים:** $\\lim_{x\\to a^+}f(x)=+\\infty$ — הפונקציה חורגת מכל חסם.",
            ),
            sec(
                "theory",
                "Growth rate hierarchy",
                "היררכיית קצבי גדילה",
                "For $x\\to\\infty$ (slowest to fastest among standard Calc 1 families):\n$$\\ln x \\ll x^\\alpha \\ll a^x \\ll x^x \\text{ (beyond course)}$$\nfor any fixed $\\alpha>0$, $a>1$.\n\n**Consequences:**\n- $\\lim_{x\\to\\infty}\\dfrac{\\ln x}{x}=0$\n- $\\lim_{x\\to\\infty}\\dfrac{x^{100}}{e^x}=0$\n- Exponentials dominate polynomials.\n\n**Technion exam tip:** when comparing $\\dfrac{P(x)}{Q(x)}$ at infinity, divide numerator and denominator by the **highest power** of $x$.",
                "ל-$x\\to\\infty$ (מאיט ל מהיר):\n$$\\ln x \\ll x^\\alpha \\ll a^x.$$\n\n**מסקנות:**\n- $\\lim_{x\\to\\infty}\\dfrac{\\ln x}{x}=0$\n- $\\lim_{x\\to\\infty}\\dfrac{x^{100}}{e^x}=0$\n- מעריכיות שולטות על פולינומים.\n\n**טיפ לבחינה:** בחלוקת $P/Q$ באינסוף — חלקו במעלה $x$ הגבוהה ביותר.",
            ),
            sec(
                "worked_example",
                "Rational limits at infinity",
                "גבולות רציונליים באינסוף",
                "**Rule:** for $f(x)=\\dfrac{a_n x^n+\\cdots}{b_m x^m+\\cdots}$ with $a_n,b_m\\ne 0$:\n- If $n<m$: limit $=0$\n- If $n=m$: limit $=\\dfrac{a_n}{b_m}$\n- If $n>m$: limit $=\\pm\\infty$ (sign from leading coefficients)\n\n**Example.** $\\lim_{x\\to\\infty}\\dfrac{3x^2-2x+1}{5x^2+x}=\\dfrac{3}{5}$.\n\nDivide by $x^2$:\n$$\\frac{3-2/x+1/x^2}{5+1/x}\\to\\frac{3}{5}.$$\n\n**Example.** $\\lim_{x\\to\\infty}\\dfrac{2x+1}{x^3-4}=0$ (degree numerator $<$ denominator).",
                "**כלל:** ל-$f(x)=\\dfrac{a_n x^n+\\cdots}{b_m x^m+\\cdots}$:\n- $n<m$: גבול $=0$\n- $n=m$: גבול $=\\dfrac{a_n}{b_m}$\n- $n>m$: $\\pm\\infty$\n\n**דוגמה.** $\\lim_{x\\to\\infty}\\dfrac{3x^2-2x+1}{5x^2+x}=\\dfrac{3}{5}$.\n\nחלוקה ב-$x^2$ נותנת $\\dfrac{3}{5}$.\n\n**דוגמה.** $\\lim_{x\\to\\infty}\\dfrac{2x+1}{x^3-4}=0$.",
            ),
            sec(
                "theory",
                "Vertical and oblique asymptotes",
                "אסימטוטות אנכיים ואלכסוניים",
                "**Vertical asymptote** $x=a$: $\\lim_{x\\to a^\\pm}f(x)=\\pm\\infty$. Common at zeros of denominators.\n\n**Horizontal asymptote** $y=L$: $\\lim_{x\\to\\pm\\infty}f(x)=L$.\n\n**Oblique (slant) asymptote** $y=mx+b$: occurs when degree of numerator exceeds denominator by exactly 1. Find via long division:\n$$\\frac{x^2+1}{x-1}=x+1+\\frac{2}{x-1}\\Rightarrow y=x+1.$$\n\n**Engineering use:** asymptotes describe long-term or singular behavior — beam loads near supports, circuit response at extremes.",
                "**אנכי** $x=a$: $\\lim_{x\\to a^\\pm}f(x)=\\pm\\infty$.\n\n**אופקי** $y=L$: $\\lim_{x\\to\\pm\\infty}f(x)=L$.\n\n**אלכסוני** $y=mx+b$: כשמעלת המונה גדולה ב-1. חלוקה ארוכה:\n$$\\frac{x^2+1}{x-1}=x+1+\\frac{2}{x-1}\\Rightarrow y=x+1.$$\n\n**שימוש הנדסי:** התנהגות בקיצוניות — עומסים, תגובת מערכות.",
            ),
            sec(
                "summary",
                "Quick reference",
                "סיכום מהיר",
                "| Task | Method |\n|---|---|\n| Rational at $\\infty$ | Divide by highest power of $x$ |\n| $e^x$ vs polynomial | Exponential wins |\n| Vertical asymptote | Check denominator zeros |\n| Oblique asymptote | Long division if deg num = deg den + 1 |\n\nAlways check **both** $+\\infty$ and $-\\infty$ when relevant (e.g. $\\arctan x$).",
                "| משימה | שיטה |\n|---|---|\n| רציונלית ב-$\\infty$ | חלוקה במעלה $x$ |\n| $e^x$ מול פולינום | מעריכית מנצחת |\n| אנכי | אפסי מכנה |\n| אלכסוני | חלוקה ארוכה |\n\nבדקו **גם** $+\\infty$ וגם $-\\infty$.",
            ),
        ],
        [
            mcq(1, "easy", "$\\lim_{x\\to\\infty}\\dfrac{5x^3+1}{2x^3-x}=?$",
                 "$\\lim_{x\\to\\infty}\\dfrac{5x^3+1}{2x^3-x}=?$",
                 ["$0$", "$\\dfrac{5}{2}$", "$\\infty$", "$-\\infty$"],
                 ["$0$", "$\\dfrac{5}{2}$", "$\\infty$", "$-\\infty$"],
                 1, "Equal degrees: ratio of leading coefficients $5/2$.", "מעלות שוות: יחס מקדמים מובילים $5/2$.", ["rational_limit_infinity"]),
            mcq(2, "medium", "$\\lim_{x\\to\\infty}\\dfrac{\\ln x}{x}=?$",
                 "$\\lim_{x\\to\\infty}\\dfrac{\\ln x}{x}=?$",
                 ["$1$", "$0$", "$\\infty$", "Does not exist"],
                 ["$1$", "$0$", "$\\infty$", "לא קיים"],
                 1, "Log grows slower than any positive power of $x$.", "לוג גדל לאט מכל חזקה חיובית של $x$.", ["compare_growth_rates"]),
            mcq(3, "medium", "Vertical asymptote of $f(x)=\\dfrac{1}{x^2-4}$?",
                 "אסימטוטה אנכי של $f(x)=\\dfrac{1}{x^2-4}$?",
                 ["$x=0$", "$x=\\pm 2$", "$x=4$", "None"],
                 ["$x=0$", "$x=\\pm 2$", "$x=4$", "אין"],
                 1, "Denominator zero at $x=\\pm 2$.", "מכנה מתאפס ב-$x=\\pm 2$.", ["find_vertical_asymptote"]),
            mcq(4, "hard", "Oblique asymptote of $\\dfrac{x^2+3x}{x+1}$?",
                 "אסימטוטה אלכסוני של $\\dfrac{x^2+3x}{x+1}$?",
                 ["$y=x+2$", "$y=x+3$", "$y=x$", "$y=2x+1$"],
                 ["$y=x+2$", "$y=x+3$", "$y=x$", "$y=2x+1$"],
                 0, "Division: $x+2+\\dfrac{-2}{x+1}$.", "חלוקה: $x+2+\\dfrac{-2}{x+1}$.", ["find_oblique_asymptote"]),
            mcq(5, "medium", "$\\lim_{x\\to-\\infty}e^x=?$",
                 "$\\lim_{x\\to-\\infty}e^x=?$",
                 ["$0$", "$1$", "$-\\infty$", "$\\infty$"],
                 ["$0$", "$1$", "$-\\infty$", "$\\infty$"],
                 0, "$e^x\\to 0$ as $x\\to-\\infty$.", "$e^x\\to 0$ כאשר $x\\to-\\infty$.", ["exponential_limit_infinity"]),
        ],
        {
            "key_insights": [
                "Divide by highest power of $x$ for rational limits at infinity.",
                "Exponentials dominate polynomials and logs.",
                "Oblique asymptotes come from long division when degree gap is 1.",
            ],
            "common_misconceptions": [
                {"wrong": "$\\lim_{x\\to\\infty}(x^2-x)=\\infty$ always positive", "correction": "For $x\\to-\\infty$, $x^2-x\\to\\infty$ still, but check sign of rational leading ratio.", "detect_phrase_en": "always positive infinity", "detect_phrase_he": "תמיד פלוס אינסוף"},
            ],
            "tutor_pacing_hint": "Practice dividing by $x^n$ before introducing oblique asymptotes.",
            "skill_atoms_unlocked": ["rational_limit_infinity", "compare_growth_rates", "find_vertical_asymptote", "find_oblique_asymptote", "exponential_limit_infinity"],
        },
    ),
    lesson(
        "continuity_discontinuity",
        "Continuity & Discontinuity",
        "רציפות ואי-רציפות",
        "Continuity at a point and on intervals, classification of discontinuities, and the Intermediate Value and Extreme Value theorems — pillars of existence proofs in engineering.",
        "רציפות בנקודה ועל קטעים, סיווג סוגי אי-רציפות, ומשפטי הערך הממוצע והקיצון — עמודי תווך להוכחות קיום בהנדסה.",
        25,
        [
            sec(
                "theory",
                "Definition of continuity",
                "הגדרת רציפות",
                "$f$ is **continuous at $a$** if:\n1. $a\\in D_f$\n2. $\\lim_{x\\to a}f(x)$ exists\n3. $\\lim_{x\\to a}f(x)=f(a)$\n\nEquivalently: $\\forall\\,\\epsilon>0\\,\\exists\\,\\delta>0: |x-a|<\\delta\\Rightarrow|f(x)-f(a)|<\\epsilon$.\n\n**Continuous on $[a,b]$:** continuous at every interior point, continuous from right at $a$, from left at $b$.\n\n**Elementary functions** (polynomials, rational on domain, $e^x$, $\\ln x$, trig on domain) are continuous wherever defined.",
                "$f$ **רציפה ב-$a$** אם:\n1. $a\\in D_f$\n2. $\\lim_{x\\to a}f(x)$ קיים\n3. $\\lim_{x\\to a}f(x)=f(a)$\n\n**רציפה על $[a,b]$:** רציפה בפנים, מימין ב-$a$, משמאל ב-$b$.\n\n**פונקציות אלמנטריות** רציפות בכל מקום שהן מוגדרות.",
            ),
            sec(
                "theory",
                "Types of discontinuity",
                "סוגי אי-רציפות",
                "**Removable:** limit exists but $\\ne f(a)$ or $f(a)$ undefined. Fix by redefining $f(a)=\\lim_{x\\to a}f(x)$. Example: $\\dfrac{\\sin x}{x}$ at $0$.\n\n**Jump:** one-sided limits exist but differ. Example: $\\text{sgn}(x)$ at $0$.\n\n**Infinite:** at least one one-sided limit is $\\pm\\infty$. Example: $1/x$ at $0$.\n\n**Essential (oscillatory):** limit does not exist (neither finite nor infinite). Example: $\\sin(1/x)$ at $0$.",
                "**ניתנת לתיקון:** הגבול קיים אך $\\ne f(a)$. דוגמה: $\\dfrac{\\sin x}{x}$ ב-0.\n\n**קפיצה:** גבולות חד-צדדיים קיימים ושונים. דוגמה: $\\text{sgn}(x)$.\n\n**אינסופית:** גבול חד-צדדי $\\pm\\infty$. דוגמה: $1/x$ ב-0.\n\n**עיקרית:** הגבול לא קיים. דוגמה: $\\sin(1/x)$ ב-0.",
            ),
            sec(
                "worked_example",
                "Testing continuity",
                "בדיקת רציפות",
                "**Example.** $f(x)=\\begin{cases}x^2 & x\\ne 1\\\\ 3 & x=1\\end{cases}$\n\n$\\lim_{x\\to 1}x^2=1\\ne f(1)=3$ — **removable** discontinuity.\n\n**Example.** $g(x)=\\dfrac{x^2-1}{x-1}$ for $x\\ne 1$. Factor: $g(x)=x+1$. Extend continuously: $\\tilde g(1)=2$.\n\n**Piecewise at join:** for $h(x)=\\begin{cases}ax+1 & x<2\\\\ x^2 & x\\ge 2\\end{cases}$, continuity at $2$ requires $2a+1=4 \\Rightarrow a=3/2$.",
                "**דוגמה.** $f(1)=3$ אך $\\lim_{x\\to 1}x^2=1$ — **ניתנת לתיקון**.\n\n**דוגמה.** $g(x)=\\dfrac{x^2-1}{x-1}=x+1$ ל-$x\\ne 1$; הרחבה רציפה: $\\tilde g(1)=2$.\n\n**קטעית:** רציפות ב-$2$ דורשת $2a+1=4 \\Rightarrow a=3/2$.",
            ),
            sec(
                "theory",
                "IVT and EVT",
                "משפט ערך ביניים (IVT) ומשפט ערך קיצון (EVT)",
                "**Intermediate Value Theorem:** If $f$ is continuous on $[a,b]$ and $N$ is strictly between $f(a)$ and $f(b)$, then $\\exists\\,c\\in(a,b)$ with $f(c)=N$.\n\n**Corollary — root existence:** if $f(a)$ and $f(b)$ have opposite signs, $\\exists\\,c\\in(a,b): f(c)=0$.\n\n**Extreme Value Theorem:** If $f$ is continuous on **closed bounded** $[a,b]$, then $f$ attains absolute maximum and minimum on $[a,b]$.\n\n**Note:** EVT needs closed interval; IVT needs continuity but interval can be open if endpoints handled.",
                "**IVT:** $f$ רציפה על $[a,b]$, $N$ בין $f(a)$ ל-$f(b)$ $\\Rightarrow$ $\\exists\\,c: f(c)=N$.\n\n**מסקנה — שורש:** סימנים מנוגדים בקצוות $\\Rightarrow$ שורש ב-$(a,b)$.\n\n**EVT:** $f$ רציפה על $[a,b]$ **סגור וחסום** $\\Rightarrow$ מקסימום ומינימום מוחלטים מתקבלים.\n\n**הערה:** EVT דורש קטע סגור.",
            ),
            sec(
                "summary",
                "Exam strategy",
                "אסטרטגיה לבחינה",
                "1. Check domain first — continuity only where defined.\n2. For piecewise functions, equate left/right limits at junctions.\n3. IVT for existence (roots, intermediate values) — no need to find $c$ explicitly.\n4. EVT guarantees extrema on closed intervals — sets up optimization on $[a,b]$.\n\nThese theorems justify bisection methods, safety margins, and guaranteed peak loads in engineering models.",
                "1. בדקו תחום תחילה.\n2. בפונקציות קטעיות — השוו גבולות בנקודת החיבור.\n3. IVT לקיום — לא חייבים למצוא $c$.\n4. EVT מבטיח קיצונים בקטע סגור.\n\nמשפטים אלו מצדיקים bisection, מרווחי בטיחות ועומסי שיא.",
            ),
        ],
        [
            mcq(1, "easy", "Which condition is NOT required for continuity at $a$?",
                 "איזה תנאי לא נדרש לרציפות ב-$a$?",
                 ["$f(a)$ is defined", "$\\lim_{x\\to a}f(x)$ exists", "$f'(a)$ exists", "$\\lim_{x\\to a}f(x)=f(a)$"],
                 ["$f(a)$ מוגדר", "$\\lim_{x\\to a}f(x)$ קיים", "$f'(a)$ קיים", "$\\lim_{x\\to a}f(x)=f(a)$"],
                 2, "Differentiability implies continuity, but continuity does not require derivative.", "גזירות $\\Rightarrow$ רציפות, לא להפך.", ["continuity_definition"]),
            mcq(2, "medium", "$f(x)=\\dfrac{|x|}{x}$ for $x\\ne 0$. What discontinuity at $0$?",
                 "$f(x)=\\dfrac{|x|}{x}$ ל-$x\\ne 0$. איזה סוג אי-רציפות ב-0?",
                 ["Removable", "Jump", "Infinite", "Essential"],
                 ["ניתנת לתיקון", "קפיצה", "אינסופית", "עיקרית"],
                 1, "Right limit 1, left limit $-1$.", "גבול ימני 1, שמאלי $-1$.", ["classify_discontinuity"]),
            mcq(3, "medium", "IVT applies when $f$ is continuous on $[0,4]$, $f(0)=-1$, $f(4)=3$. Which is guaranteed?",
                 "IVT: $f$ רציפה על $[0,4]$, $f(0)=-1$, $f(4)=3$. מה מובטח?",
                 ["$f(x)=0$ for some $x\\in(0,4)$", "$f$ has a maximum at $x=4$", "$f'(c)=0$ for some $c$", "$f$ is increasing"],
                 ["$f(c)=0$ ל-$c\\in(0,4)$", "מקסימום ב-4", "$f'(c)=0$", "$f$ עולה"],
                 0, "Sign change guarantees a root by IVT.", "שינוי סימן $\\Rightarrow$ שורש.", ["apply_ivt"]),
            mcq(4, "easy", "EVT guarantees extrema on:",
                 "EVT מבטיח קיצונים על:",
                 ["$(a,b)$ open", "$[a,b]$ closed", "$\\mathbb{R}$", "Any interval"],
                 ["$(a,b)$ פתוח", "$[a,b]$ סגור", "$\\mathbb{R}$", "כל קטע"],
                 1, "Must be continuous on closed bounded interval.", "רציפות על קטע סגור וחסום.", ["apply_evt"]),
            mcq(5, "hard", "For $f(x)=\\begin{cases}x^2 & x<1\\\\ 2x-1 & x\\ge 1\\end{cases}$, is $f$ continuous at $1$?",
                 "$f(x)=\\begin{cases}x^2 & x<1\\\\ 2x-1 & x\\ge 1\\end{cases}$ — רציפה ב-1?",
                 ["No — jump", "No — removable", "Yes", "No — infinite"],
                 ["לא — קפיצה", "לא — ניתנת לתיקון", "כן", "לא — אינסופית"],
                 2, "Left limit $1$, right value $2(1)-1=1$, $f(1)=1$.", "גבול שמאל 1, ערך ימין 1.", ["test_piecewise_continuity"]),
        ],
        {
            "key_insights": [
                "Continuity requires limit equals function value.",
                "IVT proves existence; EVT proves extrema on closed intervals.",
                "Removable discontinuities can be fixed by redefining one point.",
            ],
            "common_misconceptions": [
                {"wrong": "IVT finds the exact value of c", "correction": "IVT only guarantees existence of c, not its value.", "detect_phrase_en": "find c exactly", "detect_phrase_he": "מצא c בדיוק"},
            ],
            "tutor_pacing_hint": "Classify discontinuity types with graphs before IVT/EVT proofs.",
            "skill_atoms_unlocked": ["continuity_definition", "classify_discontinuity", "apply_ivt", "apply_evt", "test_piecewise_continuity"],
        },
    ),
    lesson(
        "lhopital_rule",
        "L'Hopital's Rule & Indeterminate Forms",
        "כלל לופיטל וצורות לא קבועות",
        "Indeterminate forms $0/0$, $\\infty/\\infty$, and transformations for $0\\cdot\\infty$, $\\infty-\\infty$, and exponential indeterminates — the workhorse for tough limits in Calc 1.",
        "צורות לא קבועות $0/0$, $\\infty/\\infty$, והמרות ל-$0\\cdot\\infty$, $\\infty-\\infty$ ומעריכיות — כלי מרכזי לגבולות קשים בחשבון 1.",
        30,
        [
            sec(
                "intro",
                "When direct substitution fails",
                "כשהצבה ישירה נכשלת",
                "Substituting $x\\to a$ may yield **indeterminate forms** — expressions that do not determine the limit:\n$$\\frac{0}{0},\\quad \\frac{\\infty}{\\infty},\\quad 0\\cdot\\infty,\\quad \\infty-\\infty,\\quad 0^0,\\quad 1^\\infty,\\quad \\infty^0.$$\n\n**L'Hopital's rule** handles $0/0$ and $\\infty/\\infty$ under hypotheses: $f,g$ differentiable near $a$, $g'(x)\\ne 0$, and the limit of $\\dfrac{f'(x)}{g'(x)}$ exists (or is $\\pm\\infty$).\n\nThen:\n$$\\lim_{x\\to a}\\frac{f(x)}{g(x)}=\\lim_{x\\to a}\\frac{f'(x)}{g'(x)}.$$\n\nApplies also as $x\\to\\pm\\infty$.",
                "הצבה ישירה עלולה לתת **צורות לא קבועות**:\n$$\\frac{0}{0},\\quad \\frac{\\infty}{\\infty},\\quad 0\\cdot\\infty,\\quad \\infty-\\infty.$$\n\n**כלל לופיטל** ל-$0/0$ ו-$\\infty/\\infty$: אם $\\lim \\dfrac{f'(x)}{g'(x)}$ קיים,\n$$\\lim\\frac{f(x)}{g(x)}=\\lim\\frac{f'(x)}{g'(x)}.$$\n\nתקף גם ב-$x\\to\\pm\\infty$.",
            ),
            sec(
                "theory",
                "Applying L'Hopital correctly",
                "יישום נכון של לופיטל",
                "**Check form first:** verify $0/0$ or $\\infty/\\infty$ before differentiating.\n\n**Differentiate numerator and denominator separately** — never use quotient rule on $\\dfrac{f}{g}$ for L'Hopital.\n\n**Repeat** if result is still indeterminate (may apply multiple times).\n\n**Example.** $\\lim_{x\\to 0}\\dfrac{\\sin x}{x}$: form $0/0$.\n$$\\lim\\frac{\\cos x}{1}=1.$$\n\n**Example.** $\\lim_{x\\to\\infty}\\dfrac{x}{e^x}$: form $\\infty/\\infty$.\n$$\\lim\\frac{1}{e^x}=0.$$\n\n**When it fails:** $\\lim_{x\\to\\infty}\\dfrac{x+\\sin x}{x}$ — L'Hopital gives non-existent $\\lim(1+\\cos x)$; use algebra instead: $1+\\dfrac{\\sin x}{x}\\to 1$.",
                "**בדקו צורה:** $0/0$ או $\\infty/\\infty$.\n\n**גזרו מונה ומכנה בנפרד** — לא כלל מנה!\n\n**חזרו** אם עדיין לא קבוע.\n\n**דוגמה.** $\\lim_{x\\to 0}\\dfrac{\\sin x}{x}=\\lim\\dfrac{\\cos x}{1}=1$.\n\n**דוגמה.** $\\lim_{x\\to\\infty}\\dfrac{x}{e^x}=0$.\n\n**כישלון:** $\\dfrac{x+\\sin x}{x}$ — השתמשו באלגברה.",
            ),
            sec(
                "worked_example",
                "Transforming other indeterminate forms",
                "המרת צורות לא קבועות אחרות",
                "**$0\\cdot\\infty$:** rewrite as $\\dfrac{0}{1/\\infty}$ or $\\dfrac{\\infty}{1/0}$.\n\n$\\lim_{x\\to 0^+} x\\ln x$: write $\\dfrac{\\ln x}{1/x}$ ($-\\infty/\\infty$), L'Hopital $\\Rightarrow \\dfrac{1/x}{-1/x^2}=-x\\to 0$.\n\n**$\\infty-\\infty$:** combine algebraically or use common denominator.\n\n$\\lim_{x\\to 0}\\left(\\dfrac{1}{x}-\\dfrac{1}{\\sin x}\\right)$: common denominator $\\dfrac{\\sin x-x}{x\\sin x}$ — then $0/0$, L'Hopital (twice may be needed).\n\n**Exponential forms** $0^0,1^\\infty,\\infty^0$: take $\\ln$ first, then exponentiate result.",
                "**$0\\cdot\\infty$:** כתבו כ-$\\dfrac{\\ln x}{1/x}$.\n\n$\\lim x\\ln x=0$.\n\n**$\\infty-\\infty$:** מכנה משותף.\n\n**מעריכיות:** $\\ln$ ואז חזרה ב-$e^{(\\cdot)}$.",
            ),
            sec(
                "pitfall",
                "Common mistakes",
                "טעויות נפוצות",
                "1. **Using quotient rule** instead of separate derivatives.\n2. **Applying when limit of $f'/g'$ does not exist** — rule does not apply.\n3. **Differentiating before confirming indeterminate form** — e.g. $\\dfrac{x}{x^2+1}\\to 0$ at $\\infty$ without L'Hopital.\n4. **Forgetting to exponentiate** after $\\ln$ for $1^\\infty$ forms.\n\n**Exam tip (Technion 104031):** show the indeterminate form explicitly before invoking L'Hopital.",
                "1. **כלל מנה** במקום גזירה נפרדת.\n2. **יישום כש-$\\lim f'/g'$ לא קיים**.\n3. **גזירה לפני בדיקת צורה**.\n4. **שכחת $e^{(\\cdot)}$** אחרי $\\ln$.\n\n**טיפ:** הציגו את הצורה הלא קבועה במפורש.",
            ),
            sec(
                "summary",
                "Decision flowchart",
                "תרשים זרימה",
                "1. Try direct substitution.\n2. If $0/0$ or $\\infty/\\infty$ — L'Hopital (check derivative ratio limit exists).\n3. If $0\\cdot\\infty$, $\\infty-\\infty$ — algebra first.\n4. If $1^\\infty$ etc. — use $\\ln$.\n5. If L'Hopital fails — factor, conjugates, known limits ($\\sin x/x$).",
                "1. הצבה ישירה.\n2. $0/0$ או $\\infty/\\infty$ — לופיטל.\n3. $0\\cdot\\infty$, $\\infty-\\infty$ — אלגברה.\n4. $1^\\infty$ — $\\ln$.\n5. כישלון — פירוק, גבולות ידועים.",
            ),
        ],
        [
            mcq(1, "easy", "$\\lim_{x\\to 0}\\dfrac{e^x-1}{x}=?$",
                 "$\\lim_{x\\to 0}\\dfrac{e^x-1}{x}=?$",
                 ["$0$", "$1$", "$e$", "$\\infty$"],
                 ["$0$", "$1$", "$e$", "$\\infty$"],
                 1, "Form $0/0$; L'Hopital: $e^x/1\\to 1$.", "צורה $0/0$; לופיטל: $e^x\\to 1$.", ["lhopital_basic"]),
            mcq(2, "medium", "$\\lim_{x\\to\\infty}\\dfrac{\\ln x}{x}=?$",
                 "$\\lim_{x\\to\\infty}\\dfrac{\\ln x}{x}=?$",
                 ["$1$", "$0$", "$\\infty$", "$-\\infty$"],
                 ["$1$", "$0$", "$\\infty$", "$-\\infty$"],
                 1, "$\\infty/\\infty$; derivative ratio $1/x\\to 0$.", "$\\infty/\\infty$; $(1/x)/1\\to 0$.", ["lhopital_infinity"]),
            mcq(3, "medium", "$\\lim_{x\\to 0^+}x\\ln x=?$",
                 "$\\lim_{x\\to 0^+}x\\ln x=?$",
                 ["$0$", "$1$", "$-\\infty$", "DNE"],
                 ["$0$", "$1$", "$-\\infty$", "לא קיים"],
                 0, "Rewrite $\\ln x/(1/x)$, L'Hopital gives $-x\\to 0$.", "כתיבה כ-$\\ln x/(1/x)$, לופיטל $\\Rightarrow -x\\to 0$.", ["indeterminate_zero_times_inf"]),
            mcq(4, "hard", "Which is WRONG when using L'Hopital?",
                 "מה שגוי בשימוש בלופיטל?",
                 ["Verify $0/0$ first", "Differentiate numerator and denominator", "Apply quotient rule to $f/g$", "May repeat if still indeterminate"],
                 ["בדוק $0/0$", "גזור מונה ומכנה", "השתמש בכלל מנה", "חזור אם צריך"],
                 2, "Never use quotient rule — differentiate top and bottom separately.", "אל תשתמשו בכלל מנה.", ["lhopital_pitfalls"]),
            mcq(5, "hard", "$\\lim_{x\\to\\infty}\\left(1+\\dfrac{1}{x}\\right)^x=?$",
                 "$\\lim_{x\\to\\infty}\\left(1+\\dfrac{1}{x}\\right)^x=?$",
                 ["$1$", "$e$", "$\\infty$", "$0$"],
                 ["$1$", "$e$", "$\\infty$", "$0$"],
                 1, "Classic $1^\\infty$ form; limit is $e$.", "צורה $1^\\infty$; הגבול $e$.", ["indeterminate_exponential"]),
        ],
        {
            "key_insights": [
                "L'Hopital applies only to 0/0 and infinity/infinity with valid derivative ratio limit.",
                "Transform 0·infinity and infinity-infinity algebraically first.",
                "For 1^infinity, use ln then exponentiate.",
            ],
            "common_misconceptions": [
                {"wrong": "L'Hopital always works for any limit", "correction": "Requires indeterminate form and limit of f'/g' must exist.", "detect_phrase_en": "always use L'Hopital", "detect_phrase_he": "תמיד לופיטל"},
            ],
            "tutor_pacing_hint": "Drill 0/0 cases before exponential indeterminates.",
            "skill_atoms_unlocked": ["lhopital_basic", "lhopital_infinity", "indeterminate_zero_times_inf", "lhopital_pitfalls", "indeterminate_exponential"],
        },
    ),
    lesson(
        "function_investigation_uni",
        "Full Function Investigation",
        "חקירת פונקציה מלאה",
        "Systematic curve sketching: domain, intercepts, asymptotes, $f'$, $f''$, monotonicity, concavity, inflection — with worked examples $f(x)=\\dfrac{x^2-1}{x^2+1}$ and $f(x)=xe^{-x}$.",
        "שרטוט גרף שיטתי: תחום, חיתוכים, אסימטוטות, $f'$, $f''$, מונוטוניות, קמירות, נקודות פיתול — עם דוגמאות $f(x)=\\dfrac{x^2-1}{x^2+1}$ ו-$f(x)=xe^{-x}$.",
        35,
        [
            sec(
                "intro",
                "Investigation checklist",
                "צ'ק-ליסט לחקירה",
                "**Standard checklist** (Technion / TAU style):\n1. **Domain** and symmetry (even/odd)\n2. **Intercepts** ($y$-intercept $f(0)$; $x$-zeros)\n3. **Asymptotes** (vertical, horizontal/oblique)\n4. **$f'(x)$** — critical points, intervals of increase/decrease\n5. **$f''(x)$** — inflection points, concavity\n6. **Key values** and sketch\n\nMark each finding on a number line before drawing — avoids sign errors.",
                "**צ'ק-ליסט סטנדרטי:**\n1. **תחום** וסימטריה\n2. **חיתוכים**\n3. **אסימטוטות**\n4. **$f'$** — נקודות קיצון, עלייה/ירידה\n5. **$f''$** — פיתול, קמירות\n6. **ערכים** ושרטוט\n\nסמנו על ציר מספרים לפני הגרף.",
            ),
            sec(
                "worked_example",
                "Example: $f(x)=\\dfrac{x^2-1}{x^2+1}$",
                "דוגמה: $f(x)=\\dfrac{x^2-1}{x^2+1}$",
                "**Domain:** $\\mathbb{R}$ (denominator always positive).\n\n**Intercepts:** $f(0)=-1$; zeros at $x=\\pm 1$.\n\n**Asymptotes:** horizontal $y=1$ (degrees equal, ratio $1/1$).\n\n**$f'(x)$:** quotient rule gives\n$$f'(x)=\\frac{4x}{(x^2+1)^2}.$$\nCritical point $x=0$; decreasing on $(-\\infty,0)$, increasing on $(0,\\infty)$; **local min** $f(0)=-1$.\n\n**$f''(x)$:** after simplification, sign changes at $x=0,\\pm\\sqrt{3}$ — inflection points; concave down on $(-\\infty,-\\sqrt{3})\\cup(0,\\sqrt{3})$.",
                "**תחום:** $\\mathbb{R}$.\n\n**חיתוכים:** $f(0)=-1$; אפסים ב-$\\pm 1$.\n\n**אסימטוטה אופקי:** $y=1$.\n\n**$f'$:** $f'(x)=\\dfrac{4x}{(x^2+1)^2}$; מינימום ב-0.\n\n**$f''$:** פיתול ב-$0,\\pm\\sqrt{3}$.",
            ),
            sec(
                "worked_example",
                "Example: $f(x)=xe^{-x}$",
                "דוגמה: $f(x)=xe^{-x}$",
                "**Domain:** $\\mathbb{R}$.\n\n**Intercepts:** $(0,0)$.\n\n**Limits:** $\\lim_{x\\to\\infty}xe^{-x}=0$ (horizontal asymptote $y=0$); $\\lim_{x\\to-\\infty}xe^{-x}=-\\infty$.\n\n**$f'(x)=e^{-x}(1-x)$:** critical at $x=1$; max $f(1)=1/e$; increasing $(-\\infty,1)$, decreasing $(1,\\infty)$.\n\n**$f''(x)=e^{-x}(x-2)$:** inflection at $x=2$; concave down $(-\\infty,2)$, up $(2,\\infty)$.\n\n**Engineering link:** $xe^{-x}$ models damped impulse response — peak at $x=1$, decay thereafter.",
                "**תחום:** $\\mathbb{R}$; חיתוך $(0,0)$.\n\n**גבולות:** $y=0$ ב-$+\\infty$.\n\n**$f'=e^{-x}(1-x)$:** מקסימום $1/e$ ב-$x=1$.\n\n**$f''$:** פיתול ב-$x=2$.\n\n**הנדסה:** תגובת מערכת מרוסנת.",
            ),
            sec(
                "practice_tip",
                "Sign charts without guessing",
                "טבלאות סימן בלי ניחוש",
                "Build **sign charts** for $f'$ and $f''$:\n- Find zeros and undefined points.\n- Test one value in each sub-interval.\n\n**Pitfall:** forgetting that $f'$ undefined often means vertical asymptote — affects domain intervals.\n\n**Second derivative test:** at critical $c$ with $f'(c)=0$:\n- $f''(c)>0$ $\\Rightarrow$ local min\n- $f''(c)<0$ $\\Rightarrow$ local max\n- $f''(c)=0$ $\\Rightarrow$ inconclusive — use first derivative test.",
                "**טבלאות סימן:**\n- מצאו אפסים ונקודות לא מוגדרות.\n- בדקו נקודה בכל תת-קטע.\n\n**מלכודת:** $f'$ לא מוגדר $\\Rightarrow$ אולי אסימטוטה אנכי.\n\n**מבחן נגזרת שנייה:** $f''(c)>0$ מינימום; $f''(c)<0$ מקסימום.",
            ),
            sec(
                "summary",
                "From data to sketch",
                "מנתונים לשרטוט",
                "Combine all information: plot intercepts, asymptotes as dashed lines, mark extrema and inflection with coordinates, then draw a smooth curve respecting monotonicity and concavity.\n\nOn exams, **partial credit** comes from correct $f'$, $f''$, and sign analysis even if the sketch is imperfect.",
                "שלבו הכל: חיתוכים, אסימטוטות מקווקווים, קיצונים ופיתול עם קוואורדינטות, עקומה חלקה.\n\n**ניקוד חלקי** ל-$f'$, $f''$ וניתוח סימן.",
            ),
        ],
        [
            mcq(1, "medium", "For $f(x)=xe^{-x}$, where is the maximum?",
                 "ל-$f(x)=xe^{-x}$, איפה המקסימום?",
                 ["$x=0$", "$x=1$", "$x=e$", "$x=2$"],
                 ["$x=0$", "$x=1$", "$x=e$", "$x=2$"],
                 1, "$f'=e^{-x}(1-x)=0 \\Rightarrow x=1$.", "$f'=0 \\Rightarrow x=1$.", ["find_critical_points"]),
            mcq(2, "medium", "$f(x)=\\dfrac{x^2-1}{x^2+1}$ has horizontal asymptote:",
                 "ל-$f(x)=\\dfrac{x^2-1}{x^2+1}$ אסימטוטה אופקי:",
                 ["$y=-1$", "$y=0$", "$y=1$", "None"],
                 ["$y=-1$", "$y=0$", "$y=1$", "אין"],
                 2, "Equal degrees: limit ratio $1/1=1$.", "מעלות שוות: $1/1=1$.", ["find_horizontal_asymptote"]),
            mcq(3, "easy", "If $f'>0$ on $(a,b)$, then $f$ is:",
                 "אם $f'>0$ ב-$(a,b)$, אז $f$:",
                 ["Decreasing", "Increasing", "Concave up", "Constant"],
                 ["יורדת", "עולה", "קמורה למעלה", "קבועה"],
                 1, "Positive derivative means increasing.", "נגזרת חיובית $\\Rightarrow$ עולה.", ["interpret_first_derivative"]),
            mcq(4, "hard", "Inflection point of $xe^{-x}$?",
                 "נקודת פיתול של $xe^{-x}$?",
                 ["$x=0$", "$x=1$", "$x=2$", "$x=e$"],
                 ["$x=0$", "$x=1$", "$x=2$", "$x=e$"],
                 2, "$f''=e^{-x}(x-2)=0 \\Rightarrow x=2$.", "$f''=0 \\Rightarrow x=2$.", ["find_inflection"]),
            mcq(5, "medium", "Second derivative test: $f'(3)=0$, $f''(3)=4$. At $x=3$:",
                 "מבחן $f''$: $f'(3)=0$, $f''(3)=4$. ב-$x=3$:",
                 ["Local max", "Local min", "Inflection", "Saddle"],
                 ["מקסימום", "מינימום", "פיתול", "אוכף"],
                 1, "$f''>0$ concave up $\\Rightarrow$ local minimum.", "$f''>0$ $\\Rightarrow$ מינימום מקומי.", ["second_derivative_test"]),
        ],
        {
            "key_insights": [
                "Always complete domain and asymptotes before derivatives.",
                "Sign charts prevent monotonicity errors.",
                "Second derivative test fails when f''(c)=0 — use first derivative test.",
            ],
            "common_misconceptions": [
                {"wrong": "Critical point always means extremum", "correction": "f'(c)=0 or undefined is critical; may be inflection with horizontal tangent.", "detect_phrase_en": "critical means max or min", "detect_phrase_he": "קריטית אומרת קיצון"},
            ],
            "tutor_pacing_hint": "Walk through xe^{-x} completely before assigning rational investigation homework.",
            "skill_atoms_unlocked": ["find_critical_points", "find_horizontal_asymptote", "interpret_first_derivative", "find_inflection", "second_derivative_test"],
        },
    ),
    lesson(
        "absolute_extrema",
        "Absolute Extrema on Closed Intervals",
        "ערכי קיצון מוחלטים על קטע סגור",
        "The Extreme Value Theorem, closed-interval method (candidates test), and applications — including $f(x)=x^3-3x+2$ on $[-2,3]$ and beam deflection.",
        "משפט הערך הקיצוני, שיטת המועמדים על קטע סגור, ויישומים — $f(x)=x^3-3x+2$ על $[-2,3]$ וכפיפת קורה.",
        20,
        [
            sec(
                "theory",
                "EVT and the candidates test",
                "EVT ושיטת המועמדים",
                "On **closed** $[a,b]$, continuous $f$ attains **absolute** max and min (EVT).\n\n**Closed Interval Method:**\n1. Find critical points of $f$ in $(a,b)$.\n2. Evaluate $f$ at each critical point and at **endpoints** $a,b$.\n3. Largest value = abs max; smallest = abs min.\n\n**Why endpoints matter:** $f(x)=x$ on $[0,1]$ has max at $x=1$ (endpoint), no interior critical point.",
                "על $[a,b]$ **סגור**, $f$ רציפה $\\Rightarrow$ מקסימום ומינימום מוחלטים (EVT).\n\n**שיטת המועמדים:**\n1. נקודות קריטיות ב-$(a,b)$.\n2. חשבו $f$ בקריטיות **ובקצוות**.\n3. הגדול = מקס; הקטן = מינ.\n\n**קצוות חשובים:** $f(x)=x$ על $[0,1]$ — מקס בקצה.",
            ),
            sec(
                "worked_example",
                "$f(x)=x^3-3x+2$ on $[-2,3]$",
                "$f(x)=x^3-3x+2$ על $[-2,3]$",
                "$f'(x)=3x^2-3=3(x^2-1)=0 \\Rightarrow x=\\pm 1$ (both in interval).\n\n| $x$ | $f(x)$ |\n|---|---|\n| $-2$ | $0$ |\n| $-1$ | $4$ |\n| $1$ | $0$ |\n| $3$ | $20$ |\n\n**Absolute max** $=20$ at $x=3$; **absolute min** $=0$ at $x=-2$ and $x=1$.\n\nLocal max at $x=-1$ ($f=4$) is not the global max.",
                "$f'=3(x^2-1)=0 \\Rightarrow x=\\pm 1$.\n\n$f(-2)=0$, $f(-1)=4$, $f(1)=0$, $f(3)=20$.\n\n**מקס מוחלט** $20$ ב-$x=3$; **מין מוחלט** $0$ ב-$-2$ ו-$1$.",
            ),
            sec(
                "worked_example",
                "Beam deflection application",
                "יישום — כפיפת קורה",
                "Simply supported beam, uniform load: deflection profile may be modeled by $y(x)=-kx^2(x-L)^2$ on $[0,L]$ (symmetric, zero at supports).\n\nBy EVT, maximum deflection (most negative $y$ or $|y|$) occurs at an interior critical point or endpoint. Symmetry gives critical at $x=L/2$.\n\n**Engineering takeaway:** closed-interval optimization locates worst-case deflection without scanning infinitely many points.",
                "קורה על שני supports: פרופיל כפיפה $y(x)=-kx^2(x-L)^2$ על $[0,L]$.\n\nלפי EVT, כפיפה מקסימלית בנקודה קריטית או בקצה. סימטריה $\\Rightarrow$ $x=L/2$.\n\n**מסקנה:** אופטימיזציה על קטע סגור מוצאת כפיפה מקסימלית.",
            ),
            sec(
                "pitfall",
                "Open intervals and unconstrained domains",
                "קטעים פתוחים ותחומים לא חסומים",
                "**EVT fails on open intervals** — e.g. $f(x)=x$ on $(0,1)$ has no maximum.\n\nOn infinite domains, extrema may not exist; use limits at infinity plus interior critical points.\n\n**Don't confuse** local vs absolute extrema — a local min can be larger than another local max on a wide interval.",
                "**EVT נכשל בקטע פתוח** — $f(x)=x$ על $(0,1)$ ללא מקסימום.\n\nעל $\\mathbb{R}$ — בדקו גבולות באינסוף.\n\n**אל תבלבלו** מקומי ומוחלט.",
            ),
            sec(
                "summary",
                "Three-step recipe",
                "מתכון בשלושה שלבים",
                "1. Confirm **closed** interval and continuity.\n2. Solve $f'=0$ and note $f'$ undefined inside.\n3. Compare all candidate values.\n\nThis is the same logic used in design codes for peak stress, maximum heat flux, and worst-case error.",
                "1. קטע **סגור** + רציפות.\n2. $f'=0$ ובדיקת לא מוגדר.\n3. השוו מועמדים.\n\nאותה לוגיקה לעומס שיא, זרימת חום מקסימלית.",
            ),
        ],
        [
            mcq(1, "easy", "EVT requires interval:",
                 "EVT דורש קטע:",
                 ["Open $(a,b)$", "Closed $[a,b]$", "Infinite $(-\\infty,\\infty)$", "Any set"],
                 ["פתוח", "סגור $[a,b]$", "אינסופי", "כל קבוצה"],
                 1, "Closed and bounded interval required.", "סגור וחסום.", ["apply_evt_closed_interval"]),
            mcq(2, "medium", "$f(x)=x^2$ on $[-1,2]$. Absolute maximum?",
                 "$f(x)=x^2$ על $[-1,2]$. מקסימום מוחלט?",
                 ["$0$", "$1$", "$4$", "$2$"],
                 ["$0$", "$1$", "$4$", "$2$"],
                 2, "$f(-1)=1$, $f(0)=0$, $f(2)=4$; max at endpoint $x=2$.", "מקס $4$ ב-$x=2$.", ["candidates_test"]),
            mcq(3, "medium", "For $x^3-3x+2$ on $[-2,3]$, abs min value?",
                 "$x^3-3x+2$ על $[-2,3]$, מין מוחלט?",
                 ["$0$", "$4$", "$20$", "$-4$"],
                 ["$0$", "$4$", "$20$", "$-4$"],
                 0, "Minimum value 0 at $x=-2$ and $x=1$.", "מינימום 0.", ["candidates_test"]),
            mcq(4, "hard", "Why is $f(x)=1/x$ on $(0,1)$ not covered by EVT?",
                 "למה $f(x)=1/x$ על $(0,1)$ לא ב-EVT?",
                 ["Not continuous", "Interval not closed", "No derivative", "Always increasing"],
                 ["לא רציפה", "קטע לא סגור", "אין נגזרת", "תמיד עולה"],
                 1, "Open interval — supremum may not be attained.", "קטע פתוח — עלול שלא להתקבל.", ["evt_limitations"]),
            mcq(5, "easy", "Critical points for candidates test include:",
                 "נקודות קריטיות כוללות:",
                 ["Only $f'=0$", "$f'=0$ or $f'$ undefined in $(a,b)$", "Only endpoints", "Only inflection points"],
                 ["רק $f'=0$", "$f'=0$ או $f'$ לא מוגדר", "רק קצוות", "רק פיתול"],
                 1, "Both stationary and singular interior points.", "עמדות ונקודות singular.", ["identify_critical_points"]),
        ],
        {
            "key_insights": [
                "Always evaluate endpoints on closed intervals.",
                "EVT guarantees existence, candidates test finds values.",
                "Local extrema are not necessarily global.",
            ],
            "common_misconceptions": [
                {"wrong": "Critical point always gives absolute extremum", "correction": "Compare all candidates including endpoints.", "detect_phrase_en": "critical is the max", "detect_phrase_he": "קריטית היא המקסימום"},
            ],
            "tutor_pacing_hint": "Tabulate f at all candidates — students skip endpoints most often.",
            "skill_atoms_unlocked": ["apply_evt_closed_interval", "candidates_test", "evt_limitations", "identify_critical_points"],
        },
    ),
    lesson(
        "antiderivatives",
        "Antiderivatives & Integration Techniques",
        "פונקציה קדומה וטכניקות אינטגרציה",
        "Antiderivatives, basic integral table, u-substitution, integration by parts, and initial-value problems — the inverse of differentiation for engineering models.",
        "פונקציה קדומה, טבלת אינטגרלים, החלפת $u$, אינטגרציה בחלקים ובעיות ערך התחלתי — היפוך הנגזרות למודלים הנדסיים.",
        35,
        [
            sec(
                "theory",
                "Antiderivatives and the constant $C$",
                "פונקציה קדומה והקבוע $C$",
                "$F$ is an **antiderivative** of $f$ on interval $I$ if $F'(x)=f(x)$ for all $x\\in I$.\n\n**General antiderivative:** if $F$ is one antiderivative, then all others are $F(x)+C$.\n\n**Notation:** $\\displaystyle\\int f(x)\\,dx = F(x)+C$.\n\n**Basic table:**\n$$\\int x^n\\,dx=\\frac{x^{n+1}}{n+1}+C\\ (n\\ne -1),\\quad \\int e^x\\,dx=e^x+C,\\quad \\int \\frac{1}{x}\\,dx=\\ln|x|+C$$\n$$\\int \\sin x\\,dx=-\\cos x+C,\\quad \\int \\cos x\\,dx=\\sin x+C$$",
                "$F$ **קדומה** של $f$ אם $F'=f$.\n\n**כל הקדומות:** $F(x)+C$.\n\n**סימון:** $\\displaystyle\\int f\\,dx = F(x)+C$.\n\n**טבלה:**\n$$\\int x^n\\,dx=\\frac{x^{n+1}}{n+1}+C,\\quad \\int e^x\\,dx=e^x+C,\\quad \\int \\frac{1}{x}\\,dx=\\ln|x|+C$$",
            ),
            sec(
                "theory",
                "u-substitution",
                "החלפת $u$",
                "If $u=g(x)$, then $\\displaystyle\\int f(g(x))g'(x)\\,dx = \\int f(u)\\,du$.\n\n**Example.** $\\int 2x\\cos(x^2)\\,dx$. Let $u=x^2$, $du=2x\\,dx$:\n$$\\int \\cos u\\,du = \\sin u + C = \\sin(x^2)+C.$$\n\n**Example.** $\\int \\dfrac{x}{x^2+1}\\,dx$. Let $u=x^2+1$:\n$$\\frac{1}{2}\\int \\frac{1}{u}\\,du = \\frac{1}{2}\\ln|u|+C = \\frac{1}{2}\\ln(x^2+1)+C.$$\n\n**Tip:** look for inner function whose derivative (up to constant) appears as factor.",
                "אם $u=g(x)$: $\\displaystyle\\int f(g(x))g'(x)\\,dx = \\int f(u)\\,du$.\n\n**דוגמה.** $\\int 2x\\cos(x^2)\\,dx = \\sin(x^2)+C$.\n\n**דוגמה.** $\\int \\dfrac{x}{x^2+1}\\,dx = \\frac{1}{2}\\ln(x^2+1)+C$.\n\n**טיפ:** חפשו פונקציה פנימית שנגזרתה מופיעה כגורם.",
            ),
            sec(
                "theory",
                "Integration by parts",
                "אינטגרציה בחלקים",
                "$$\\int u\\,dv = uv - \\int v\\,du$$\n\nChoose $u$ via **LIATE** priority: Log, Inverse trig, Algebraic, Trig, Exponential — $u$ is earlier in list.\n\n**Example.** $\\int x e^x\\,dx$. Take $u=x$, $dv=e^x dx$:\n$$=xe^x-\\int e^x\\,dx = xe^x-e^x+C = e^x(x-1)+C.$$\n\n**Example.** $\\int \\ln x\\,dx$. Take $u=\\ln x$, $dv=dx$:\n$$=x\\ln x - \\int x\\cdot\\frac{1}{x}\\,dx = x\\ln x - x + C.$$\n\n**Tabular method** helps repeated IBP (e.g. $x^2 e^x$).",
                "$$\\int u\\,dv = uv - \\int v\\,du$$\n\n**LIATE:** Log, Inverse, Algebraic, Trig, Exp.\n\n**דוגמה.** $\\int x e^x\\,dx = e^x(x-1)+C$.\n\n**דוגמה.** $\\int \\ln x\\,dx = x\\ln x - x + C$.",
            ),
            sec(
                "worked_example",
                "Initial value problems",
                "בעיות ערך התחלתי",
                "Given $f'(x)$ and one point on $f$, find $f$.\n\n**Example.** $f'(x)=3x^2-2$, $f(1)=4$.\n$$f(x)=x^3-2x+C,\\quad f(1)=1-2+C=4 \\Rightarrow C=5.$$\nSo $f(x)=x^3-2x+5$.\n\n**Engineering:** velocity $v(t)$ from acceleration $a(t)$ with $v(0)=v_0$; position from velocity — two integration steps + constants from ICs.",
                "נתון $f'$ ונקודה — מצאו $f$.\n\n**דוגמה.** $f'=3x^2-2$, $f(1)=4$ $\\Rightarrow$ $f(x)=x^3-2x+5$.\n\n**הנדסה:** $v$ מ-$a$; $s$ מ-$v$ — שני שלבי אינטגרציה + תנאי התחלה.",
            ),
            sec(
                "summary",
                "Technique selection guide",
                "מדריך בחירת טכניקה",
                "| Integrand pattern | Try |\n|---|---|\n| Composite with inner derivative factor | $u$-sub |\n| Product of unlike types ($x e^x$, $\\ln x$) | Parts |\n| Rational simple | Partial fractions (later) or algebra |\n| Trig product | Identities or parts |\n\nAlways **check by differentiating** your answer — catches missing $+C$ and sign errors.",
                "| דפוס | טכניקה |\n|---|---|\n| הרכבה + נגזרת פנימית | $u$-sub |\n| מכפלה | חלקים |\n| רציונלית | שברים חלקיים |\n\n**אמתו בגזירה** — תופסים $+C$ חסר.",
            ),
        ],
        [
            mcq(1, "easy", "$\\int 3x^2\\,dx=?$",
                 "$\\int 3x^2\\,dx=?$",
                 ["$x^3$", "$x^3+C$", "$6x+C$", "$x^2+C$"],
                 ["$x^3$", "$x^3+C$", "$6x+C$", "$x^2+C$"],
                 1, "Antiderivative of $3x^2$ is $x^3$; never forget $+C$.", "קדומה $x^3+C$.", ["basic_antiderivative"]),
            mcq(2, "medium", "$\\int 2x\\cos(x^2)\\,dx=?$",
                 "$\\int 2x\\cos(x^2)\\,dx=?$",
                 ["$\\sin(x^2)+C$", "$-\\cos(x^2)+C$", "$2\\sin(x^2)+C$", "$\\cos(x^2)+C$"],
                 ["$\\sin(x^2)+C$", "$-\\cos(x^2)+C$", "$2\\sin(x^2)+C$", "$\\cos(x^2)+C$"],
                 0, "$u=x^2$ gives $\\int\\cos u\\,du=\\sin u$.", "$u=x^2$ $\\Rightarrow$ $\\sin(x^2)+C$.", ["u_substitution"]),
            mcq(3, "medium", "$\\int x e^x\\,dx=?$",
                 "$\\int x e^x\\,dx=?$",
                 ["$xe^x+C$", "$e^x(x-1)+C$", "$\\frac{x^2 e^x}{2}+C$", "$e^x+C$"],
                 ["$xe^x+C$", "$e^x(x-1)+C$", "$\\frac{x^2 e^x}{2}+C$", "$e^x+C$"],
                 1, "IBP: $u=x$, $dv=e^x dx$.", "חלקים: $u=x$.", ["integration_by_parts"]),
            mcq(4, "hard", "$f'(x)=2x$, $f(0)=3$. Then $f(x)=?$",
                 "$f'(x)=2x$, $f(0)=3$. אז $f(x)=?$",
                 ["$x^2+3$", "$x^2$", "$2x+3$", "$x^2+3x$"],
                 ["$x^2+3$", "$x^2$", "$2x+3$", "$x^2+3x$"],
                 0, "$f=x^2+C$, $f(0)=3 \\Rightarrow C=3$.", "$f=x^2+3$.", ["initial_value_antiderivative"]),
            mcq(5, "medium", "$\\int \\dfrac{1}{x}\\,dx=?$",
                 "$\\int \\dfrac{1}{x}\\,dx=?$",
                 ["$\\ln x + C$", "$\\ln|x| + C$", "$\\dfrac{1}{x^2}+C$", "$x\\ln x + C$"],
                 ["$\\ln x + C$", "$\\ln|x| + C$", "$\\dfrac{1}{x^2}+C$", "$x\\ln x + C$"],
                 1, "Domain requires $|x|$ for negative $x$.", "צריך $|x|$ ל-$x<0$.", ["log_antiderivative"]),
        ],
        {
            "key_insights": [
                "Every antiderivative includes +C unless initial data fixes it.",
                "u-sub needs inner function derivative as factor.",
                "LIATE guides integration by parts choice.",
            ],
            "common_misconceptions": [
                {"wrong": "Integral of 1/x is ln(x) without absolute value", "correction": "Use ln|x| for all x≠0.", "detect_phrase_en": "ln x only", "detect_phrase_he": "ln x בלי ערך מוחלט"},
            ],
            "tutor_pacing_hint": "Verify every antiderivative by differentiation on the board.",
            "skill_atoms_unlocked": ["basic_antiderivative", "u_substitution", "integration_by_parts", "initial_value_antiderivative", "log_antiderivative"],
        },
    ),
    lesson(
        "definite_integral_area",
        "Definite Integrals, FTC & Area",
        "אינטגרל מסוים, FTC ושטחים",
        "Riemann sums, Fundamental Theorem of Calculus, integral properties, area between curves, and engineering applications — connecting accumulation to area under graphs.",
        "סכומי רימן, המשפט היסודי, תכונות האינטגרל, שטח בין עקומות ויישומים הנדסיים — חיבור הצטברות לשטח תחת גרף.",
        30,
        [
            sec(
                "theory",
                "Riemann sums and definition",
                "סכומי רימן והגדרה",
                "Partition $[a,b]$ into subintervals, choose sample points $\\xi_i$, form\n$$S_n=\\sum_{i=1}^n f(\\xi_i)\\,\\Delta x_i.$$\n\nIf $f$ integrable, $\\displaystyle\\int_a^b f(x)\\,dx = \\lim_{\\|P\\|\\to 0} S_n$.\n\n**Interpretation:** signed area under $y=f(x)$ — regions below $x$-axis contribute negative area.\n\n**Special cases:** left/right/midpoint sums; for monotonic $f$, upper and lower sums bracket the integral.",
                "חלוקת $[a,b]$, נקודות $\\xi_i$:\n$$S_n=\\sum f(\\xi_i)\\,\\Delta x_i.$$\n\n$\\displaystyle\\int_a^b f = \\lim S_n$.\n\n**פרשנות:** שטח עם סימן — מתחת לציר $x$ שלילי.\n\n**מקרים:** סכומים שמאל/ימין/אמצע.",
            ),
            sec(
                "theory",
                "Fundamental Theorem of Calculus",
                "המשפט היסודי של החשבון (FTC)",
                "**Part 1:** If $f$ continuous on $[a,b]$, $F(x)=\\displaystyle\\int_a^x f(t)\\,dt$ is differentiable and $F'(x)=f(x)$.\n\n**Part 2:** If $F'=f$ on $[a,b]$, then\n$$\\boxed{\\int_a^b f(x)\\,dx = F(b)-F(a)}.$$\n\n**Example.** $\\displaystyle\\int_0^1 2x\\,dx = [x^2]_0^1 = 1$.\n\n**Example.** $\\displaystyle\\int_1^e \\frac{1}{x}\\,dx = [\\ln x]_1^e = 1$.\n\nFTC links **accumulation** (integral) to **net change** (antiderivative difference).",
                "**חלק 1:** $F(x)=\\int_a^x f$ $\\Rightarrow$ $F'=f$.\n\n**חלק 2:**\n$$\\int_a^b f = F(b)-F(a).$$\n\n**דוגמה.** $\\int_0^1 2x\\,dx = 1$.\n\nFTC מחבר הצטברות לשינוי נטו.",
            ),
            sec(
                "theory",
                "Properties and area between curves",
                "תכונות ושטח בין עקומות",
                "**Linearity:** $\\int (af+bg)=a\\int f + b\\int g$.\n**Additivity:** $\\int_a^b f + \\int_b^c f = \\int_a^c f$.\n**Order:** $f\\le g \\Rightarrow \\int f \\le \\int g$.\n\n**Area between** $f,g$ on $[a,b]$ where $f\\ge g$:\n$$A=\\int_a^b [f(x)-g(x)]\\,dx.$$\n\nIf curves cross, split at intersection points and use $|f-g|$ on each subinterval.\n\n**Example.** Area between $y=x$ and $y=x^2$ on $[0,1]$: $\\int_0^1 (x-x^2)\\,dx = \\dfrac{1}{2}-\\dfrac{1}{3}=\\dfrac{1}{6}$.",
                "**לינאריות, חיבוריות, סדר.**\n\n**שטח בין** $f,g$: $\\int [f-g]$ כש-$f\\ge g$.\n\n**דוגמה.** $y=x$ ו-$y=x^2$ על $[0,1]$: שטח $\\dfrac{1}{6}$.",
            ),
            sec(
                "worked_example",
                "Engineering: total work from variable force",
                "הנדסה: עבודה מכוח משתנה",
                "Work $W=\\displaystyle\\int_a^b F(x)\\,dx$ when force depends on position (spring $F=kx$, etc.).\n\n**Example.** $F(x)=3x^2$ N from $x=0$ to $x=2$ m:\n$$W=\\int_0^2 3x^2\\,dx = [x^3]_0^2 = 8\\text{ J}.$$\n\nSimilarly: charge from current $Q=\\int I\\,dt$; mass from density — all **accumulation integrals**.",
                "עבודה $W=\\int F\\,dx$.\n\n**דוגמה.** $F=3x^2$, $0\\to 2$: $W=8$ J.\n\nגם: $Q=\\int I\\,dt$ — הצטברות.",
            ),
            sec(
                "summary",
                "Problem-type map",
                "מפת סוגי בעיות",
                "| Question | Method |\n|---|---|\n| Evaluate $\\int_a^b f$ | Find antiderivative, apply FTC |\n| Area under one curve | $\\int |f|$ if needed for sign |\n| Area between curves | Split at intersections, $\\int|f-g|$ |\n| Net vs total quantity | Net = signed integral; total = $\\int|f|$ |\n\nUnits: integral of rate gives total change in accumulated quantity.",
                "| שאלה | שיטה |\n|---|---|\n| חישוב $\\int_a^b f$ | קדומה + FTC |\n| שטח תחת עקומה | $\\int |f|$ |\n| בין עקומות | פיצול בחיתוכים |\n| נטו מול כולל | signed vs $\\int|f|$ |",
            ),
        ],
        [
            mcq(1, "easy", "$\\displaystyle\\int_0^2 3x^2\\,dx=?$",
                 "$\\displaystyle\\int_0^2 3x^2\\,dx=?$",
                 ["$4$", "$8$", "$12$", "$6$"],
                 ["$4$", "$8$", "$12$", "$6$"],
                 1, "$[x^3]_0^2=8$.", "$[x^3]_0^2=8$.", ["ftc_evaluate"]),
            mcq(2, "medium", "FTC Part 2 requires:",
                 "FTC חלק 2 דורש:",
                 ["$f$ continuous and $F'=f$", "$f$ only bounded", "$F$ any function", "$f$ differentiable"],
                 ["$f$ רציפה ו-$F'=f$", "$f$ חסומה בלבד", "$F$ כלשהי", "$f$ גזירה"],
                 0, "Need antiderivative whose derivative is $f$.", "קדומה עם נגזרת $f$.", ["ftc_conditions"]),
            mcq(3, "medium", "Area between $y=x^2$ and $y=x$ on $[0,1]$?",
                 "שטח בין $y=x^2$ ו-$y=x$ על $[0,1]$?",
                 ["$1/2$", "$1/3$", "$1/6$", "$1/12$"],
                 ["$1/2$", "$1/3$", "$1/6$", "$1/12$"],
                 2, "$\\int_0^1(x-x^2)dx=1/2-1/3=1/6$.", "$\\int_0^1(x-x^2)dx=1/6$.", ["area_between_curves"]),
            mcq(4, "hard", "If $f(x)<0$ on $[a,b]$, then $\\int_a^b f(x)\\,dx$ is:",
                 "אם $f(x)<0$ על $[a,b]$, האינטגרל:",
                 ["Positive area", "Negative (signed area below axis)", "Zero", "Undefined"],
                 ["שטח חיובי", "שלילי (מתחת לציר)", "אפס", "לא מוגדר"],
                 1, "Integral is signed; negative where graph below $x$-axis.", "אינטגרל signed — שלילי מתחת לציר.", ["signed_area"]),
            mcq(5, "medium", "$\\dfrac{d}{dx}\\displaystyle\\int_2^x t^3\\,dt=?$",
                 "$\\dfrac{d}{dx}\\displaystyle\\int_2^x t^3\\,dt=?$",
                 ["$x^3$", "$x^3-8$", "$3x^2$", "$\\int_2^x t^3\\,dt$"],
                 ["$x^3$", "$x^3-8$", "$3x^2$", "$\\int_2^x t^3\\,dt$"],
                 0, "FTC Part 1: derivative of integral with variable upper limit is integrand at $x$.", "FTC חלק 1: $f(x)=x^3$.", ["ftc_part1"]),
        ],
        {
            "key_insights": [
                "FTC Part 2: antiderivative evaluated at endpoints.",
                "Area between curves needs top minus bottom; split at crossings.",
                "Integral of rate equals net accumulated change.",
            ],
            "common_misconceptions": [
                {"wrong": "Integral always equals geometric area", "correction": "Integral is signed; use absolute value for total area.", "detect_phrase_en": "integral is area always positive", "detect_phrase_he": "אינטגרל תמיד שטח חיובי"},
            ],
            "tutor_pacing_hint": "Draw shaded regions before setting up area integrals.",
            "skill_atoms_unlocked": ["ftc_evaluate", "ftc_conditions", "area_between_curves", "signed_area", "ftc_part1"],
        },
    ),
]

INDEX_UPDATES = {
    les["concept_id"]: {
        "id": les["concept_id"],
        "title_en": les["title_en"],
        "title_he": les["title_he"],
        "est_minutes": les["est_minutes"],
        "duration_min": les["est_minutes"],
        "subject": les["subject"],
        "level_min": "university",
        "type": "interactive",
        "math_track": les["math_track"],
    }
    for les in LESSONS
}

for les in LESSONS:
    path = os.path.join(BASE, les["concept_id"] + ".json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(les, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Saved {les['concept_id']}")

with open(INDEX_PATH, encoding="utf-8") as f:
    index = json.load(f)

ids = {e["id"] for e in index}
new_index = []
for entry in index:
    cid = entry["id"]
    new_index.append(INDEX_UPDATES[cid] if cid in INDEX_UPDATES else entry)

for cid, entry in INDEX_UPDATES.items():
    if cid not in ids:
        new_index.append(entry)

new_index.sort(key=lambda x: x["id"])

with open(INDEX_PATH, "w", encoding="utf-8") as f:
    json.dump(new_index, f, ensure_ascii=False, indent=2)
    f.write("\n")

print(f"Updated index ({len(new_index)} lessons); added: {[c for c in INDEX_UPDATES if c not in ids]}")