/**
 * Static fallback for authored lessons when Neon is unavailable or stale.
 * Generated by `node scripts/generate-lessons-artifacts.mjs`.
 */
import bundle from './lessons-bundle.generated.json';
import { CONCEPT_ID_ALIASES, resolveConceptAlias } from './concept-aliases';
import type { LessonAgentHints, LessonSection, LessonWithQuestions } from './neon-db';

export type BundledAgentHintsRow = {
  concept_id: string;
  title_en: string;
  title_he: string;
  agent_hints: LessonAgentHints;
};

/** True when agent_hints carries at least one field tutors/coaches consume. */
export function hasMeaningfulAgentHints(hints: LessonAgentHints | null | undefined): boolean {
  if (!hints) return false;
  if ((hints.key_insights?.length ?? 0) > 0) return true;
  if ((hints.common_misconceptions?.length ?? 0) > 0) return true;
  if ((hints.skill_atoms_unlocked?.length ?? 0) > 0) return true;
  if ((hints.prerequisites_to_check_before_teaching?.length ?? 0) > 0) return true;
  if ((hints.coach_drill_skills?.length ?? 0) > 0) return true;
  if ((hints.next_recommended?.length ?? 0) > 0) return true;
  if (hints.tutor_pacing_hint?.trim()) return true;
  if (hints.diagnostic_signals && Object.keys(hints.diagnostic_signals).length > 0) return true;
  return false;
}

/**
 * Prefer Neon row when it has usable hints; otherwise fall back to the static bundle
 * (same source as mergeLessonWithBundle). Returns null when neither source has hints.
 */
export function resolveAgentHintsRow(
  conceptId: string,
  fromDb: BundledAgentHintsRow | null | undefined,
): BundledAgentHintsRow | null {
  if (fromDb && hasMeaningfulAgentHints(fromDb.agent_hints)) {
    return fromDb;
  }

  const bundled = getBundledLesson(conceptId);
  if (!bundled || !hasMeaningfulAgentHints(bundled.lesson.agent_hints)) {
    return null;
  }

  return {
    concept_id: fromDb?.concept_id ?? bundled.lesson.concept_id ?? conceptId,
    title_en: fromDb?.title_en ?? bundled.lesson.title_en,
    title_he: fromDb?.title_he ?? bundled.lesson.title_he,
    agent_hints: bundled.lesson.agent_hints,
  };
}

type BundleEntry = LessonWithQuestions;

const byConceptId = bundle as unknown as Record<string, BundleEntry>;

function sectionContentScore(sections: LessonSection[]): number {
  if (!sections?.length) return 0;
  let score = sections.length;
  const kinds = new Set(sections.map((s) => s.kind));
  if (kinds.has('worked_example')) score += 3;
  if (kinds.has('definition')) score += 1;
  if (kinds.has('exercise_set')) score += 2;
  const bodyHe = sections.reduce((n, s) => n + (s.body_he_md?.length ?? 0), 0);
  if (bodyHe > 500) score += 2;
  return score;
}

/** Reverse map: alias slug → canonical lesson concept_id in bundle. */
const aliasToCanonical = new Map<string, string>();
for (const [alias, canonical] of Object.entries(CONCEPT_ID_ALIASES)) {
  if (byConceptId[canonical]) aliasToCanonical.set(alias, canonical);
}

export function getBundledLesson(conceptId: string): LessonWithQuestions | null {
  const canonical = resolveConceptAlias(conceptId);
  if (byConceptId[conceptId]) return byConceptId[conceptId];
  if (byConceptId[canonical]) return byConceptId[canonical];
  const mapped = aliasToCanonical.get(conceptId);
  return mapped ? byConceptId[mapped] ?? null : null;
}

/** Prefer Neon when it has rich Goren/Geva content; otherwise use the static bundle. */
export function mergeLessonWithBundle(
  fromDb: LessonWithQuestions | null,
  conceptId: string,
): LessonWithQuestions | null {
  const bundled = getBundledLesson(conceptId);
  if (!fromDb) return bundled;
  if (!bundled) return fromDb;

  const dbScore = sectionContentScore(fromDb.lesson.sections ?? []);
  const bundleScore = sectionContentScore(bundled.lesson.sections ?? []);

  if (bundleScore > dbScore + 2) return bundled;

  // DB row exists but may lack Hebrew titles — merge metadata from bundle when richer
  const lesson = { ...fromDb.lesson };
  const b = bundled.lesson;
  if ((b.title_he?.length ?? 0) > (lesson.title_he?.length ?? 0)) {
    lesson.title_he = b.title_he;
  }
  if ((b.summary_he?.length ?? 0) > (lesson.summary_he?.length ?? 0)) {
    lesson.summary_he = b.summary_he;
  }
  if (bundleScore > dbScore) {
    lesson.sections = b.sections;
  }

  return {
    lesson,
    questions: fromDb.questions.length >= bundled.questions.length
      ? fromDb.questions
      : bundled.questions,
  };
}

export function isConceptInBundle(conceptId: string): boolean {
  return Boolean(getBundledLesson(conceptId));
}
